### ISSUE TITLE
Serenity reports for Jest (without protractor)

### ISSUE THREAD

**Issue by voidgit** [serenity-js/serenity-js#100]
Hi all, @jan-molak,

It would be really great opportunity to use Serenity reports with Jest.

Best regards,
Vadym

**Comment by souadghiri** [comment]
Hi @jan-molak,
I would also be highly interested in this one. Could it come soon? Can I start already using some work-around/any doc? As the mocha one was closed in late september, i am hoping Jest can follow soon :).
San.

**Comment by jan-molak** [comment]
Hey @voidgit and @san-ouadghiri - Serenity/JS 2.0 has now been released and offers completely re-written adapters for both Jasmine and Cucumber, which can run either with or without Protractor. If anyone would like to work on an adapter for Jest I'd be happy to guide them through the process?

**Comment by jan-molak** [comment]
Closing in favour of #164 which has a bit more context.
