### ISSUE TITLE
✗ LogicError: Make sure to perform a HTTP API call before checking on the response

### ISSUE THREAD

**Issue by LayMui** [serenity-js/serenity-js#1016]
```
export const VerifyFarmerDetails = {
    hasSuccessfulStatus: (actor: Actor, statusCode: number) =>
        Task.where(`#actor verify farmer details is successful`,
            Ensure.that(LastResponse.status(), equals(statusCode)),
          0 --->  Ensure.that(
                Property.of(LastResponse.body<Farmer>()).status.answeredBy(actor), equals('SUCCESS')
            ), 
```
_0 ---> calling this line will throw the above error_
but yet I can see the LastResponse.body() output

the above Task function is called at the Step definitions
```
When('{pronoun} create a farmer using a unique UserID', (actor: Actor) => {
    let UserID = uuid.v4();
      actor.attemptsTo(
        TakeNote.of(
            Question.about<string>(`UserID`, actor => {
              return `UserID`; 
            })).as('UserID'),
        
          **CreateFarmer.usingUserID(UserID),**   
         1 --->  VerifyFarmerDetails.hasSuccessfulStatus(actor, 201),
          // Log.the(LastResponse.body())
       
)});

Then('{pronoun} should able to get the details of the new farmer profile', async (actor: Actor) => 
  actor.attemptsTo(
 // Log.the(Note.of('UserID').answeredBy(actor)),
2---> await VerifyFarmerDetails.hasSuccessfulStatus(actor, 201),

 ));  
```
1 -> calling this verification function works but it's not what I should verify at the When steps
2-> calling the verification here will throw the LogicError: Make sure to perform a HTTP API call before checking on the response.

**Comment by LayMui** [comment]
this is resolved by this code
```
When('{pronoun} create a farmer using a unique UserID', (actor: Actor) => 
    //let UserID = uuid.v4();
      actor.attemptsTo(
        TakeNote.of(
            Question.about<string>(`UserID`, actor => {
              return `UserID`; 
            })).as('UserID'),
        
          CreateFarmer.usingUserID(uuid.v4()),   
          // VerifyFarmerDetails.hasSuccessfulStatus(actor, 201),
          // Log.the(LastResponse.body())
       
//)});
));
```

**Comment by jan-molak** [comment]
Hi @LayMui - I've allowed myself to [format the code samples](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) you've provided to make them easier to read.

But regarding your original post, I'm not sure if I understand. Is there an issue in the framework, or was it an issue in the test?

**Comment by LayMui** [comment]
@jan-molak  this is due to missing the async and await 

this is resolved, so this is not serenityJS library issue

here is code snippet
When('{pronoun} create a farmer using a unique UserID', async (actor: Actor) => {
    let UserID = uuid.v4();
      await actor.attemptsTo(
        TakeNote.of(
            Question.about<string>(`UserID`, actor => {
              return `UserID`; 
            })).as('UserID'),
        
          CreateFarmer.usingUserID(uuid.v4()),   
     )});
