### ISSUE TITLE
Serenity/JS 3.0 - Support Wait in API-only tests

### ISSUE THREAD

**Issue by eyesopen** [serenity-js/serenity-js#1035]
Hi,
In my API tests I need to wait for a specific period of time, however standard Wait.for(duration) requires BrowseTheWeb ability which my API using actors do not have.

As discussed in SerenityJs lobby, there is a workaround, but this functionality would be good to have.
> Jan Molak @jan-molak Oct 11 11:08
> ```
> const Sleep = (duration: Duration) => 
>     Interaction.where(`#actor waits for ${ duration }`, actor => {
>         return Promise((resolve, reject) => {
>             setTimeout(resolve, duration.inMilliseconds())
>         });
>     })  
> ```

**Comment by jan-molak** [comment]
Released in `3.0.0-rc.20`
