### ISSUE TITLE
Update Serenity BDD CLI

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1047]
Update Serenity BDD CLI to version `3.0.2`

**Comment by viper3400** [comment]
@jan-molak I think version `3.0.2` is outdated by 773786af91f0aaab5a6deeba8b327fda0f5cfb9f and #1133 and #1129. 

I’d tended to close this issue. Though, there would be a pending update to version `3.2.0`. But it’s blocked by the issue in #1133. Shall we track this re-using this issue or creating a new one?

**Comment by viper3400** [comment]
I close this one and created #1147 .
