### ISSUE TITLE
packages/webdriverio compile failure

### ISSUE THREAD

**Issue by thu2004** [serenity-js/serenity-js#1057]
Run 'npm run compile' in packages/webdriverio give error.

Error message is:

node_modules/webdriverio/build/commands/element/getProperty.d.ts:17:4883 - error TS2304: Cannot find name 'ElementInternals'.

please investigate.

**Comment by jan-molak** [comment]
Hi @thu2004!

Please make sure that before running the compilation you install the dependencies, so:

```
git clone https://github.com/serenity-js/serenity-js.git
cd serenity-js
npm install             # installs node_modules in all the modules of the Serenity/JS monorepo
make clean compile      # re-compiles all the modules
```
After this initial setup you can then re-compile individual modules, for example:
```
cd packages/webdriverio
npm run compile
```

Let me know if this helps?

**Comment by thu2004** [comment]
Hi
I did exactly those commands 
make clean compile -> result failure

@integration/web-testing-tools: src/index.ts(1,26): error TS2307: Cannot find module 'express' or its corresponding type declarations.
lerna ERR! npm run compile exited 2 in '@integration/web-testing-tools'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
make: *** [compile] Error 2

**Comment by jan-molak** [comment]
Right, `Cannot find module 'express'` indicates that the NPM module has not been correctly installed.

I'd suggest removing all the node_modules folders in your local installation and then re-installing them again.

You can do this as follows:

```
npm run lerna clean
rm -rf node_modules
npm install
```

Hope this helps!

**Comment by thu2004** [comment]
same result. Can you please try it yourself ? I tried on my mac and linux machine. Same result.

**Comment by jan-molak** [comment]
Hey @thu2004 - apologies, there was a typo in my earlier comment, I meant `make install` rather than `npm install`, as per the [Contributor's Guide](https://serenity-js.org/contributing.html)

Having said that, I see that with a completely fresh master build I can reproduce the issue you're seeing. Let me see what's going on here.

**Comment by jan-molak** [comment]
@thu2004 - OK, I think I got to the bottom of it. Looks like the compilation failure was caused by one of the transitive dependencies.

Could you please try again with the latest master?

**Comment by thu2004** [comment]
Yes, the latest master works as expected. Thank you.

**Comment by jan-molak** [comment]
Cool, thanks for confirming
