### ISSUE TITLE
Serenity/JS 3.0 - Issue when using `Task`s from external lib with internal `Actors`

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1087]
Hi @jan-molak 

Based on the [gitter discussion](https://gitter.im/serenity-js/Contributors?at=61cdcd7f46529077f55e6ce3) I've created a reproducible example here: https://github.com/viper3400/serenity-js-actors-issue

The example is based on your very own todomvc example for main branch. Follow the instructions in the `README.md` to reproduce the issue.

For the completeness of this issue here in GitHub:
When using
- External tasks (page elements) with external Actors works!
- Internal tasks (page elements) with internal Actors works!
- Internal tasks (page elements) with external Actors fails!
- External tasks (page elements) with internal Actors fails!

Error:
```
ConfigurationError: Wendy can't BrowseTheWeb yet. Did you give them the ability to do so?
```
This pattern was functional with Serenity/JS 2.x and Protractor.

Thanks for having a look at it and don't hesitate to ask if there are any questions.

**Comment by viper3400** [comment]
Hi @jan-molak

After our gitter chat today I assume you are right with this:

> Jan Molak
10:55
the reason why the ability check might not work across different modules is because it uses an instanceof check
Jan Molak
10:56
so as long as the lib and the consuming project use the exact same version and serenity modules get correctly de-duped, the instanceof check should work
Jan Molak
11:58
basically, for instanceof check to work in node, the class being checked need to come from the exact same module, at the exact same version, and the exact same place on the file system

I created a npm package https://www.npmjs.com/package/@viper3400/test-wdio-lib for test and added this to the project and it seems to work.

(What I also tried before was an `npm install <complete_path> but that haven't worked either.)

So, obviously no change to test the library without uploading it to a repo.

I tried this just with the todo example and have to verify this with my real life project. Would appreciate if we could leave this issue open. I'll close it as soon as I've verified this.

**Comment by jan-molak** [comment]
Sure thing, please keep me posted. 
Also, please note that to test your library you could simply push it to a git-based version control system - see [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies). This should save you some trouble of building an actual package, doing a release, etc.

**Comment by viper3400** [comment]
I was not able to get it working with the direct git repo link but gave [yalc](https://www.npmjs.com/package/yalc) a try. This worked. I assume that this will work as well as soon I'm able to publish the library again.

As this is not a Serenity/JS 3.0 issue I'll close this one.
Thanks Jan for helping out here.
