### ISSUE TITLE
Ignore case sensitive in tags (@manual / @Manual)

### ISSUE THREAD

**Issue by metrophos** [serenity-js/serenity-js#110]
Hi Jan,

in the ticket https://github.com/jan-molak/serenity-js/issues/33 we discussed that tags like [@manual]() should also work when it starts with a capital letter like [@Manual](). So here is the ticket :)

Regards,
Daniel

**Comment by jan-molak** [comment]
Hi @metrophos! Both `@Manual` and `@manual` tags are recognised as of Serenity/JS 2.0.
Please check it out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
