### ISSUE TITLE
Serenity/JS 3.0 - Support for easier debugging

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1102]
Serenity/JS supports standard Node.js Promises, so in order to debug an actor flow, one can create an interaction to `SetABreakpoint` and run the test through a debugger:

```typescript
import { Interaction } from '@serenity-js/core';

export const SetABreakpoint = () =>
  Interaction.where(`#actor sets a breakpoint`, actor => {
    debugger;
  });
```

Then:
```typescript
import { actorCalled } from '@serenity-js/core';
import { Navigate } from '@serenity-js/web';

describe('using a debugger', () => {

  it('stops at a breakpoint', async () => {
    await actorCalled('Debbie').attemptsTo(
      Navigate.to('https://serenity-js.org'),
      SetABreakpoint(),
      // other activities
    );
  });
});

```

However, this doesn't seem like the most convenient way to do it.

So, Serenity/JS should:
- provide built-in interactions to help with debugging
- look into building on top of capabilities provided by the integration tools

**Comment by yaffol** [comment]
I don't know if this is in scope, but I really like the debugging offered by the Playwright test runner, in particular through the VS Code extension. That and the trace capturing are the most useful parts when working out what is going on/wrong with a test, for me.
