### ISSUE TITLE
Serenity/JS 3.0 - Public property cannot be named (TS 4029) in 3.0.0-rc.7 caused by #1099

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1106]
Hi @jan-molak , I open a new issue for this to keep #1099 clean. I tried to update to 3.0.0-rc.7 to test the changes from this issue. After updating I got typescript error for a lot of my `PageElement`s similar to the issue we had in https://github.com/serenity-js/serenity-js/issues/946:

```
Public property 'link' of exported class has or is using name 'QuestionStatement' from external module "C:/dev/git/cgm-ch-e2e-common/e2e-serenityjs-wdio/node_modules/@serenity-js/core/lib/screenplay/Question" but cannot be named.ts(4029)
```

This is again, because I use classes:

```ts
import { Question } from '@serenity-js/core';
import { By, PageElement } from '@serenity-js/web';

// when not in a class all is fine
const mainFeature = () =>
    PageElement.located(By.css('.xxx')).describedAs('list of features accessible for current user');

const link = (url: string) =>
    PageElement.located(By.css(`[href="${url}"]`))
        .of(mainFeature())
        .describedAs(`the feature url of ${url}`);

export class FeatureClass {
    mainFeature = () => PageElement.located(By.css('.xxx')).describedAs('list of features accessible for current user');

    // this throws the error when used in a class
    link = (url: string) =>
        PageElement.located(By.css(`[href="${url}"]`))
            .of(this.mainFeature())
            .describedAs(`the feature url of ${url}`);

    // would probably solve the problem
    linkWorking = (url: string): Question<Promise<PageElement>> =>
        PageElement.located(By.css(`[href="${url}"]`))
            .of(this.mainFeature())
            .describedAs(`the feature url of ${url}`);
}
```

So while importing `Question` and explicitly name the return type may solve the problem, you found another solution in #946 I think?

**Comment by jan-molak** [comment]
Ah, nice catch, thanks!

**Comment by viper3400** [comment]
Okay, so I assume this was not intended and you'll fix it? So I'll wait before changing all my `PageElement.of` locators and before testing #1099?

**Comment by jan-molak** [comment]
Yeah, looks like either ts-node didn't pick it up, or this example is missing from the specs

**Comment by jan-molak** [comment]
OK, I can reproduce it in a test. It's actually not the fact that you're using classes, it's that the question gets `export`ed.

**Comment by jan-molak** [comment]
3.0.0-rc.8 should address this issue

**Comment by viper3400** [comment]
Had a first look and it seems to work now. Will continue to test #1099, I expect valid results next week. Thanks, Jan!
