### ISSUE TITLE
Support interaction to Drag and Drop

### ISSUE THREAD

**Issue by Jidarofa** [serenity-js/serenity-js#1107]
Hi, 

I need to do drag and drop in my UI project, I'm using serenity Js 2.x and reading the documentation this interaction doesn't exist yet.

If is possible add this interaction to serenity JS would fantastic.

Drag and drop webdriver.io (https://webdriver.io/docs/api/element/dragAndDrop/)

**Comment by jan-molak** [comment]
Example implementation (Serenity/JS 2.x):

```typescript
const DragAndDrop = (source: Answerable<Element<'async'>>, destination: Answerable<Element<'async'>>) =>
  Interaction.where(`#actor drags ${ source } onto ${ destination }`,  async actor => {
    const sourceElement = await actor.answer(source);
    const destinationElement = await actor.answer(destination);

    await sourceElement.dragAndDrop(destinationElement)
  })
  
actorCalled('Jimmy').attemptsTo(
    DragAndDrop(Target.the('source').located(by....), Target.the('destination').located(by...))
)
```

**Comment by Jidarofa** [comment]
> 

Hella again :( @jan-molak  sorry me I'm trying to do taht but apper this:

![image](https://user-images.githubusercontent.com/25329752/152193377-8f63e825-484b-4c26-988b-4ee5733c8ee4.png)

Do you have any idea.. sorry me!

**Comment by Jidarofa** [comment]
> No worries, your editor seems to have picked up the wrong implementation of `Element`; we need the one from `webdriverio`. I've updated the imports.

So in this case I need to move my project to serenity JS to 3.x??

**Comment by Jidarofa** [comment]
Hello @jan-molak Thanks, the implementation work correctly, add evidence



https://user-images.githubusercontent.com/25329752/153018333-865a086f-7f5c-4dde-a42e-6f66f887749a.mov

**Comment by jan-molak** [comment]
Fab, thanks for confirming!

**Comment by jan-molak** [comment]
Folding into https://github.com/serenity-js/serenity-js/issues/1107
