### ISSUE TITLE
Support for serenity in cliptor- protractor's interactive cli

### ISSUE THREAD

**Issue by igniteram** [serenity-js/serenity-js#113]
This is not an issue, please mark it with the question tag

Would like to include serenity-js in [cliptor](https://github.com/igniteram/Cliptor.js) along with the other frameworks(jasmine,mocha,cucumber) which have support in protractor, currently serenity-js is a plugin which should be added to the config file. Just wanted to know will this change in future?

**Comment by jan-molak** [comment]
Hey @igniteram, it's great to hear from you!

I wasn't aware of Cliptor, but it does look really cool. Sure, it sounds like a great idea to include Serenity/JS there as well. How can I help you with that?

Jan

**Comment by jan-molak** [comment]
Hi @igniteram, I haven't heard from you in a while, so I'll close this ticket. If you'd still like to include Serenity/JS in cliptor, please feel free to open a new one.
