### ISSUE TITLE
Serenity/JS 3.0.0-rc.11 - Serenity BDD CLI to 3.2.0

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1133]
Hi Jan, you update to Serenity BDD CLI 3.2.0. When running the `webdriverio-mocha-todomvc` example from Serenity/JS repo the following report is created (Windows 10): [target.zip](https://github.com/serenity-js/serenity-js/files/8086483/target.zip)

When you scroll to the Tags section of the report and try to click on "Managing A Todo List" badge the referenced HTML page was not found. 

I'm not sure, if this is an issue of the Serenity BDD CLI or if there was a breaking change there which would require a change in the underlying JSON files generated by Serenity/JS.

Would it be possible to stay on 2.6 for  a while? In 3.2.0 the section "Functional Coverage Overview" is gone. When using mocha or jasmine this was always a good entry point if you had multiple spec files.

![grafik](https://user-images.githubusercontent.com/11006334/154428488-5e24fabc-fc4e-4e7f-b321-15c64a3dc94d.png)

**Comment by jan-molak** [comment]
OK, I can reproduce the issue; it looks like the CLI doesn't generate the feature-level reports (you can see that by running `serenity-bdd run --shortFilenames=false`). 

I'll need to investigate this. Thanks for reporting!

**Comment by jan-molak** [comment]
OK, it looks like a regression in Serenity BDD CLI version `3.1.1` that affects specs executed with Mocha (and potentially Jasmine). Cucumber scenarios are reported correctly.

**Comment by jan-molak** [comment]
I'll downgrade to 3.1.0 which works correctly.

**Comment by jan-molak** [comment]
Downgraded to Serenity BDD CLI 3.1.0 in Serenity/JS `3.0.0-rc12`.

@viper3400 - please take it for a spin and let me know if you come across any other issues! Thanks

**Comment by viper3400** [comment]
Thanks, looks much better!
👍
