### ISSUE TITLE
Update Serenity BDD CLI to version >= version 4.x when available

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1147]
Serenity BDD CLI should be updated to the latest version >= 3.2.0.

There was an attempt in #1129 but there was a regression in 3.1.1 (see #1133) and downgrade to 3.1.0 was necessary. Update to version > 3.1.0 is blocked by https://github.com/serenity-bdd/serenity-core/pull/2721.

**Comment by viper3400** [comment]
Retest today with Serenity BDD CLI v 3.2.5, issue is not solved.

**Comment by jan-molak** [comment]
Blocked by https://github.com/serenity-bdd/serenity-core/issues/3214

**Comment by jan-molak** [comment]
Adding Serenity BDD 4.0.19 JSON output for reference
[screenplay-tests.zip](https://github.com/serenity-js/serenity-js/files/13317705/screenplay-tests.zip)
