### ISSUE TITLE
Cannot disable redirects with maxRedirects: 0

### ISSUE THREAD

**Issue by yunwu-cn** [serenity-js/serenity-js#1181]
AxiosRequestConfig supports disable auto following redirect by setting maxRedirects to 0 in the config.

However, this config could not pass from code to serenity HTTPRequest config when the value is 0, due to the if logic here: https://github.com/serenity-js/serenity-js/blob/master/packages/rest/src/model/HTTPRequest.ts#L62-L64.

**Comment by jan-molak** [comment]
Hey @yunwu-cn!

I can't remember the rationale behind that logic, to be honest. I have a vague recollection of Axios not liking null config params, but this code is from a year ago, and whatever issue that was working around might no longer be there.

I think we could either explicitly check for `null` or `undefined`, or perhaps even remove [this whole block](https://github.com/serenity-js/serenity-js/blob/7de51df1c30ef2a09db47377e813b27692edf691/packages/rest/src/model/HTTPRequest.ts#L59-L67) altogether?

**Comment by yunwu-cn** [comment]
@jan-molak  I've opened a small PR for fix. Want to minimize the change, so just did explicit check for `null` and `undefined`.
Please help to take a look and merge if possible. I have some redirect tests rely on this to function properly.

Thank you.
