### ISSUE TITLE
Cucumber Integration: Update to Version >= 8.2

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1216]
Cucumber integration of Serenity/JS is tied to version 7.3.2 at the moment. Current version of [cucumber-js](https://github.com/cucumber/cucumber-js) is 8.2.0.

Cucumber 8 has backwards-incompatible changes, so it will require some work to integrate.

(An attempt to upgrade the package >= 8 will fail with: `TypeError: Cannot read property 'CUCUMBER_PUBLISH_ENABLED' of undefined`, at least when using WDIO and Serenity/JS 3 RC)

**Comment by jan-molak** [comment]
🚀 Support for Cucumber 8 is available as of `3.0.0-rc.24`
