### ISSUE TITLE
Serenity 3.0 - Type-safe Notepad

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1220]
A follow up to https://github.com/serenity-js/serenity-js/issues/817, cc: @viper3400

---

## Context

The current 3.0-rc implementation of the `Notepad` makes it easy for developers to create untyped notepads:

```typescript
actorCalled('Nate')
  .whoCan(TakeNotes.using(Notepad.empty()))
  .attemptsTo(
    Note.record('example_note', 'content'),
    Ensure.that(Note.of('example_note').isPresent(), true),
    Ensure.that(Note.of('example_note'), equals('content'),
  )
```

However, an untyped `Notepad` also makes it easy to:
- make typing errors when specifying the name of the note to be retrieved
- forget to update the name of the note, especially in deeply-nested tasks, when the name changes

It seems like using an (optionally) strongly-typed `Notepad` that defines the types of notes that can be stored in it would address this problem.

Here again the current 3.0-rc implementation allows us to define a strongly-typed Notepad.
For example, given the following structure of `MyNotes`:

```typescript
interface PersonalDetails {
  name: string;
  age:  number;
}

interface MyNotes {
  personal: PersonalDetails;
}
```

We can define the notepad as follows:

```typescript

Notepad.empty<MyNotes>()

Notepad.with<MyNotes>({
  personal: {
    name: 'Alice',
    age:  27,
  }
})
```

We can also retrieve the strongly-typed notes as follows:

```typescript
actorCalled('Alice')
  .whoCan(TakeNotes.using(Notepad.empty<MyNotes>()))
  .attemptsTo(
    Note.record<MyNotes>('personal', { name: 'Alice', age:  27 }),
    Ensure.that(Note.of<MyNotes>('personal').isPresent(), true),
    Ensure.that(Note.of<MyNotes>('personal'), equals({ name: 'Alice', age:  27 })),

    // using a QuestionAdapter    
    Ensure.that(Note.of<MyNotes>('personal').name, equals('Alice')),
    Ensure.that(Note.of<MyNotes>('personal').age,  isGreaterThan(18)),
  )
```

## The problem we're trying to solve

The problem arises when the notes contain multiple TypeScript types.

For example, if `MyNotes` were to be defined as follows:

```typescript
interface AuthDetails {
  username: string;
  password: string;
}

interface PersonalDetails {
  name: string;
  age:  number;
}

interface MyNotes {
  auth?:    AuthDetails;
  personal: PersonalDetails;
}
```

We will no longer be able to access `Note.of<MyNotes>('personal').name` and the following code will generate a type error: `TS2339: Property 'name' does not exist on type 'QuestionAdapter '`

```typescript
    Ensure.that(Note.of<MyNotes>('personal').name, equals('Alice')),
```

This is because of TypeScript's lack of support for partial type argument inference (see https://github.com/microsoft/TypeScript/issues/26242 and https://github.com/microsoft/TypeScript/issues/10571), which means that

```
Note.of<MyNotes>('personal')
```
is interpreted as `QuestionAdapter<AuthDetails | PersonalDetails>`, and since `name` is not present in type `AuthDetails` we get the type error.

### Option 1: explicitly property name

One way to solve this problem would be to provide an explicit name of the property we're planning to retrieve when we specify the interface describing the notes themselves:

```typescript
class Notes {
    static of<Notes extends Record<string, any>, Key extends keyof Notes>(subject: Key): QuestionAdapter<Notes[Key]> {
       // ...
    }
}
```

Advantages:
- Makes the Notepad more type-safe and allows for type-specific assertions and using `QuestionAdapter` to access properties and methods of the underlying type, e.g. `Note.of<MyNotes, 'personal'>('personal').name.toLocaleLowerCase()`

Disadvantages:
- The API doesn't look that great `Note.of<MyNotes, 'personal'>('personal').name` 🧐 
- Doesn't support dynamic subjects, e.g. `Note.of<MyNotes, ???>('my_note_' + test_case_name)`

## Option 2: make the whole notepad accessible

Another approach would be to separate the retrieval of the notepad or one of its "sections" from retrieving the specific note.

For example, while the below factory methods allow us to create a Notepad:
```
Notepad.empty<MyNotes>()         : Notepad<MyNotes>
Notepad.with<MyNotes>({ /* */ }) : Notepad<MyNotes>
```
we could have a factory method that retrieves the notepad associated with a given actor:

```
Notepad.notes<MyNotes>() : QuestionAdapter<MyNotes>
```
Since the above method returns a `QuestionAdapter<MyNotes>` we could then easily access specific notes:

```typescript
    Ensure.that(Notepad.notes<MyNotes>().personal.name, equals('Alice')),
    Ensure.that(Notepad.notes<MyNotes>()['personal']name, equals('Alice')),
    Ensure.that(Notepad.notes<MyNotes>()[`something-${ 'dynamic' }`].name, equals('Alice')) // returns `any`
```

Advantages:
- makes retrieval of notes super easy
- leverages `QuestionAdapter`
- allows for the name of the note to be determined dynamically to a degree

Disadvantages:
- doesn't allow for the name of the note to be determined based on the value of another `Question`
- I'm not sure what the API responsible for recording the notes should be 🤔 

#### Recording notes

We could potentially have `QuestionAdapter` add `.set(value: T): QuestionAdapter<T>` the same way it adds `.isPresent(): Question<Promise<boolean>>`.

This way we'd have:

- `Notepad.notes<MyNotes>().personal.name` returns `QuestionAdapter<string>`
- ~`Notepad.notes<MyNotes>().personal.name.set('Alex')` also returns `QuestionAdapter<string>` (not sure if this one's doable..)~ - it isn't

or perhaps better:

- `Notepad.notes<MyNotes>().personal.set('name', 'Alex')` returns `QuestionAdapter<PersonalDetails>`
- `Notepad.notes<MyNotes>().set('personal', { name: 'Alex', age: 34 })` returns `QuestionAdapter<MyNotes>`

Advantages:
- Makes the API reasonably intuitive
- The setter could support `Answerable<string>`, so would work with dynamic values
- Opens the doors to supporting default values, e.g. `Notepad.notes<MyNotes>().personal.name.orElse('Alex')`, which could be useful on its own

Disadvantages:
- changing `QuestionAdapter` would affect every other `QuestionAdapter`; this may or may not be desirable.
- potentially tricky to implement; consider:

```
Notepad.empty() // so initial state is {}
Notepad.notes().personal.set('name', 'Bob')    // should this throw?
Notepad.notes().personal.name.set('length', 2) // overriding a property of a string? uh.
```

What about `orElse()`? Should it just return the alternative?

**Comment by viper3400** [comment]
Hi  @jan-molak 

I thought about this a bit as well but I have to prepare some use cases first to be able give you a valuable feedback.

The old 2.x notepad had it's limitations but it was simple enough to take at least a note.  The more I think about it, the 3.x notepad feels to me like cracking the nut with the sledgehammer.

But as I said, I'll come back with some examples, maybe we use the notepad different.

👍

**Comment by jan-molak** [comment]
Sounds good, thanks!

I was thinking of supporting the following scenarios (assuming `T extends Record<any, any>`):

- Creating a notepad
   - Empty
       - Untyped: `Notepad.empty(): Notepad<Record<any, any>>`
       - Typed: `Notepad.empty<T>(): Notepad<T>`
       - 2.x-style (as a factory method on `TakeNotes`)
           - `TakeNotes.usingAnEmptyNotepad()` delegating to `Notepad.empty()`
           - `TakeNotes.usingAnEmptyNotepad<T>()` delegating to `Notepad.empty<T>()`
   - With initial state
       - Untyped: `Notepad.with({ some: 'initial value' }): Notepad<{ some: string }>`
       - Typed: `Notepad.with<T>({ ... }): Notepad<T>`
- Dynamically importing data into an existing notepad (e.g. loading data from a Cucumber table at runtime, or from an API response)
   - `Notepad.import<T>(notes: Partial<T>): Interaction`
- Recording a single note
    - Untyped: `Notepad.notes().set('my subject', 'some value'): Interaction`
    - Typed: `Notepad.notes<T>().set<K extends keyof T>(key: K, value: Answerable<T[K]>): Interaction`
    - 2.x-style:
        - Untyped: `Note.record('my subject', 'some value')`, delegating to `Notepad.notes().set('my subject', 'some value')`
        - Typed: not supported because of https://github.com/microsoft/TypeScript/issues/26242
- Reading a single note:
    - Untyped: `Notepad.notes()['my subject with spaces']: QuestionAdapter<any>`
    - Untyped: `Notepad.notes().someKeyIfItHasNoSpaces: QuestionAdapter<any>` 
    - Typed: `Notepad.notes<T>()[keyof T]: QuestionAdapter<T[K]>`
        - e.g. `Notepad.notes<MyNotes>().myNoteName`
- Reading the whole notepad:
   - Untyped: `Notepad.notes(): QuestionAdapter<Record<any, any>`
   - Typed: `Notepad.notes<T>(): QuestionAdapter<T>`

Let me know how you use it and let's see if the model above holds.

**Comment by viper3400** [comment]
Okay, let's start simple, lets just have one example at a time to allow us to stay focused:

# Use Case No. 1

Given 
* a shopping list, 
* when navigate to https://shoppinglist.com/add 
* you get a single input field to enter a shopping list item (one at a time)
* and a button to save. 
* After clicking on the save button,
* you get a confirmation in the UI, that the item was saved,
* with the date and the time (two separate `PageElement`s).
* `"Saved" - "05/21/2022" - "9:54"`
* when navigate to https://shoppinglist.com/list
* you see a list of all existing entries incl. date + time of their creation
* by a lack of specification  ;-) and the async loading of each item, the sort order of the list is not predictable.


Then
our  `PageElements` would look something like that:

```typescript
// the fields where we read the save date and time from on the add page
const DateFieldOnAddPage = () => PageElement(...).of(AddPage).describedAs('the date field on the page to add an item');
const TimeFieldOnAddPage = () => PageElement(...).of(AddPage).describedAs('the time field on the page to add an item');

// the item name field on the list page
const ItemNameFieldOnListPage = () => PageElement(...).of(ListPage).describedAs('the item name field on the list page')

// the row in our list where the item name field contains our given item
const RowForItemOnListPage = (itemName: string) => 	  	
	PageElements(...).of(ListPage)
		.where(Text.of(ItemNameFieldOnListPage()), equals(itemName)).first();

// the date field of the row with the current iten name
const DateFieldOnListPage = (itemName: string) => 
	PageElement(...).of(RowForItemOnListPage(itemName))
		.describedAs('the date field on the list page');

// the time field of the row with the current iten name		
const TimeFieldOnListPage = (itemName: string) => 
	PageElement(...).of(RowForItemOnListPage(itemName))
		.describedAs('the time field on the list page');

```

Today I would do something like that:

```typescript
Note.record('date_of_milk', Text.of(DateFieldOnListPage('milk'))
Note.record('time_of_milk', Text.of(DateFieldOnListPage('milk'))

Ensure.that(DateFieldOnListPage('milk'), equals(Note.of('date_of_milk'))
Ensure.that(TimeFieldOnListPage('milk'), equals(Note.of('time_of_milk'))
```

Well, to be honest, I would rather do some data driven magic and put some external object (in this simple case a string array) into the test:

```typescript
const CreateEntriesInAShoppingList = (items: string[]) => 
	Task.where('#actor creates entries in a shopping list',
		List.of<string[]>(items).forEach( (item) => item.actorAttempsTo(
			...,
			Note.record(`date_of_${item.value}`, Text.of(DateFieldOnListPage(item.value)),
			Note.record(`time_of_${item.value}`, Text.of(DateFieldOnListPage(item.value)),
			...			
		   )
		)		
	);

const EnsureEntriesInAShoppingList = (items: string[]) => 
	Task.where('#actor creates entries in a shopping list',
		List.of<string[]>(items).forEach( (item) => item.actorAttempsTo(
			...,
			Ensure.that(DateFieldOnListPage(item.value), equals(Note.of(`date_of_${item.value}`)),
			Ensure.that(TimeFieldOnListPage(item.value, equals(Note.of(`date_of_${item.value}`))
		   )
		)		
	);
	
// mocha spec.ts
...
const testData = [ 'milk', 'sugar', 'butter' ]

it('tests my shopping list', () =>
	actorCalled('Anna').attemptsTo(
		CreateEntriesInAShoppingList(testData),
		EnsureEntriesInAShoppingList(testData)
	)
	
);
```

I understand, that I still could use the untyped notepad. Though, I see the advantages of a typed one. But how would this look like for Use Case No. 1?

**Comment by viper3400** [comment]
# Use Case No. 2
This would be to add authentication to our shopping list. Users have to provide their credentials before they can use the shopping list. Initial data of the notepad shall be used. All other things are the same as in use case no. 1

# Use Case No 3.
Our app now shall be tested with different users - so different sets of credentials.

# Use Case No. 4
Our app gets an update. Users can now order the items in their list. They get a (not predictable) order number. This order number must be entered again at the next page for confirmation (so we have to take a note of it)

----
Writing down this use cases helped me to figure out my concerns about the notepad:

One concern ist about the mixup of typed and untyped notes in the same notepad, as well, as the mixup of initial / not initial data. But I think, that's something you covered?

The second concern is the ability to scale, when application grows. There may be a lot of different types needed in different places of the application. So you would spin up all this in the `actor`s object.

So maybe the second concern is not about the notepad at all and thats why it’s difficult for me to explain. It's probably about what you mention [here](https://github.com/serenity-js/serenity-js/blob/b6b4bd0d6074fd93739ea61edb5f4febbdf20045/documentation/website/src/handbook/release-notes/serenity-js-3.md?plain=1#L121).

Actually, I never thought about an `Actor` as kind of DI container. For now, I still init the `Actor` once in my whole test suite (given the possibility, you can init it in the [wdio.conf](https://github.com/serenity-js/serenity-js/blob/8bd28e99ef21ce0cf44e9c95e64761b0a89196fa/examples/webdriverio-mocha-todomvc/wdio.conf.ts#L16)).

Maybe the question (or the concern) is about the lifetime of a notepad and the [lifetime of an actor](https://github.com/serenity-js/playbooks/discussions/31).

The nature of the “first steps in Serenity/JS examples” is, that they cover straight forward use cases. Maybe some good practices for growing test suites can help.
