### ISSUE TITLE
Serenity/JS 3.0 - Migrate Serenity/JS templates to v3 and setup GitPod

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1242]
Adding Gitpod to Serenity/JS templates should make it easier for people to start with the framework.

Repositories:
- [x] [`serenity-js/serenity-js`](https://github.com/serenity-js/serenity-js)
- [x] [`serenity-js/serenity-js-cucumber-template`](https://github.com/serenity-js/serenity-js-cucumber-template)
- [x] [`serenity-js/serenity-js-mocha-webdriverio-template`](https://github.com/serenity-js/serenity-js-mocha-webdriverio-template)
- [x] [`serenity-js/serenity-js-mocha-protractor-template`](https://github.com/serenity-js/serenity-js-mocha-protractor-template)
- [x] [`serenity-js/serenity-js-cucumber-webdriverio-template`](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template)
- [x] [`serenity-js/serenity-js-cucumber-playwright-template`](https://github.com/serenity-js/serenity-js-cucumber-playwright-template)
- [x] [`serenity-js/serenity-js-jasmine-protractor-template`](https://github.com/serenity-js/serenity-js-jasmine-protractor-template)
- [x] [`serenity-js/serenity-js-mocha-template`](https://github.com/serenity-js/serenity-js-mocha-template)
- [x] [`serenity-js/serenity-js-playwright-test-template`](https://github.com/serenity-js/serenity-js-playwright-test-template)
- [x] [`serenity-js/serenity-js-cucumber-protractor-template`](https://github.com/serenity-js/serenity-js-cucumber-protractor-template)

**Comment by viper3400** [comment]
:+1:

I gave it a try to get [a working example](https://gitpod.io/#https://github.com/viper3400/jidaforu-serenitybug/tree/gitpod-integration) for issue in #1338. So it seems easy to implement, based on the configuration you already implemented for the Serenity/JS main project.
