### ISSUE TITLE
allow node 18

### ISSUE THREAD

**Issue by keradus** [serenity-js/serenity-js#1243]
Hey, I wanted to use node 18 for my app, but it failed to install dependencies as Serenity v3 is not allowing node 18. Would it be possible to bring support for it?

**Comment by jan-molak** [comment]
Hey, Serenity/JS support Node LTS (so 16) and LTS-1 (so 14).

It looks like Node 18 has [stabilised now](https://nodejs.org/en/about/releases/), so let's take it for a spin.

**Comment by jan-molak** [comment]
Hey @keradus, support for Node 18 has just shipped in [3.0.0-rc.23](https://github.com/serenity-js/serenity-js/compare/v2.33.10...v3.0.0-rc.23) 

Please give it a try and let me know what you think!

**Comment by keradus** [comment]
Thanks!
