### ISSUE TITLE
Serenity/JS 3.0.0-rc.23 - Issue with `Wait.until` in combination with `PageElements.where(Text, equals('some string'))`

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1255]
Follow up to the [gitter discussion](https://gitter.im/serenity-js/Lobby?at=62d8ef293bbb38488992719f):

Replace the `manage_a_todo_list.spec.ts` in the webdriver-mocha-todomvc from example folder:

```typescript
import { contain, Ensure } from "@serenity-js/assertions";
import { actorCalled, Wait } from "@serenity-js/core";
import { isVisible } from "@serenity-js/web";
import { describe, it } from "mocha";

import { RecordedItems, RecordItem, Start } from "../src";
import { TodoList } from "../src/todo-list/ui";

describe("Managing a Todo List", () => {
  describe("TodoMVC", () => {
    describe("actor", () => {
      it("records new items", () =>
        actorCalled("Wendy").attemptsTo(
          Start.withAnEmptyList(),
          RecordItem.called("Walk a dog"),
          Ensure.that(TodoList.itemCalled("Walk a dog"), isVisible()),
          Wait.until(TodoList.itemCalled("xxx"), isVisible()), // --> does not work
          //Wait.until(RecordedItems.names, contain("xxx")), --> works
          Ensure.that(RecordedItems.names, contain("Walk a dog"))
        ));
    });
  });
});
```

The test will fail in the `Wait.until` step _before_ the default timeout of 5 seconds is reached. 

In my example I just used _xxx_ as it is not there at all (cause the todo app has no real delay to demonstrate the issue). But at least I would expect the test to fail after the default timeout of 5 seconds - or a Wait.upTo(Duration.of(some time)) - not immediately. 

(I my tests I would wait until some delayed page element was loaded, before continue the tests.)

Can't see an effect of setting the `.pollingInterval`, as well.

I suspect a dependency to do with the locator strategy. To reproduce this in the https://github.com/serenity-js/serenity-js/blob/main/integration/web-specs/spec/screenplay/interactions/Wait.spec.ts something like:

```typescript
const statusHeaders = () => PageElements.located(By.id('status')).describedAs('all headers');
const statusHeaderWithText = (text: string) => statusHeaders.where(Text, equals(text));

Wait.until(statusHeaderWithText('Ready'), isVisible);
```

would be necessary. Given, the the display of the text _Ready_ would be delayed somehow.

Using `webdriver` and Serenity/JS 3.0.0-rc.23. Cannot reproduce this issue in 3.0.0-rc.19

**Comment by jan-molak** [comment]
🚀 Version 3.0.0-rc.24 addresses this issue by incorporating `isPresent` check into `isClickable`, `isVisible`, `isActive`, `isEnabled`, and `isSelected`.

This means all the above expectations can be used with `PageElements`, even if no `PageElement` objects are returned.

For example:

```typescript

const listItems = () => PageElements.located(By.css('li')).describedAs('list items')

await actorCalled('Alice').attemptsTo(
  Wait.until(listItems.first(), isVisible()),
  Ensure.that(listItems.first(), isClickable()),
)
```

@viper3400 - Please let me know if you spot any other issues or usage patterns I might have missed!

**Comment by viper3400** [comment]
@jan-molak - Had a first glance, but have to have a deeper look into this. The area I'm working in is still a bit flaky, have to drill down, where it comes from.

**Comment by viper3400** [comment]
Okay, works.
