### ISSUE TITLE
Returns a Question<string> after joining array elements.

### ISSUE THREAD

**Issue by luisaferco** [serenity-js/serenity-js#1304]
Hello everyone.

I'm figuring out how to get a new Question whose value is a result of applying `mapping`  function to join all array elements, like the split() function that divides a string in a list of substrings, however, I want to return a string from an array: 
```
Text.ofAll(SearchPage.optionsSelected).map(split(','))
// I would like to do for something like this ->
Text.ofAll(SearchPage.optionsSelected).map(join(','))

//finally...
actor.attemptsTo(TakeNote.of(
            Text.ofAll(
                SearchPage.optionsSelected).map(join(',')))
            .as('All checked options'))
...

actorInTheSpotlight().attemptsTo(
            Ensure.that(Text.of(SearchPage.optionsSelectedTxt)
        .map(join(',')), equals(Note.of('All checked options)
  )

```
The behavior of the system deals with selecting multiple options and seeing them separated by commas in once are selected.

Thanks in advance

**Comment by jan-molak** [comment]
Hi @luisaferco and welcome to the Serenity/JS community :-)

If this is a new project you've just started, I'd suggest using Serenity/JS 3.0 RC.

In Serenity/JS 3.0, joining the elements is as simple as this:
```typescript
Text.ofAll(SearchPage.optionsSelected).join(',') // returns QuestionAdapter<string>
```

Alternatively, in Serenity/JS 2 you can do this like this:
```typescript
Text.ofAll(SearchPage.optionsSelected).map(actor => items => items.join(',')))
```

Let me know if this helps!

Jan

**Comment by luisaferco** [comment]
Hi @jan-molak thank you, your suggestion works as expected, I didn't know of the new mapping function using SerenityJS 3.0
