### ISSUE TITLE
My automation it freezes

### ISSUE THREAD

**Issue by Jimmy-RF** [serenity-js/serenity-js#1338]
Hello I'm working with serenity js with cucumber and webdriverio, I was working normally but now I don't not what happen with my framework or PC because I have a very strange issue, I can identify that when I put Wait.for(Duration.ofSeconds(2)), > 2 my automation it freezes.

as you can see in the video when I change the timeout from 2 to 3, never finish my test :( I don't know what happen :( heplllme please.

MAC OS

https://user-images.githubusercontent.com/100356221/195711355-f2d3912f-cf4b-48d4-88fc-8fe5498cba51.mp4

**Comment by viper3400** [comment]
Hi, looks like there are 3 workers running in parallel. Can you limit your tests to run just the test under investigation.

You can enable the (StreamReporter)[https://serenity-js.org/handbook/reporting/stream-reporter.html] to get more information what is going on, as well to get more information.

**Comment by Jimmy-RF** [comment]
> 

Hello viper thank you for answer me, I don't know how to configure the number of instances.. actually open. new instance per every .feature file.

Here is the events document 
[events.ndjson.zip](https://github.com/serenity-js/serenity-js/files/9789569/events.ndjson.zip)

**Comment by viper3400** [comment]
You can limit the number of instances in your `wdio.conf`. Set both, `maxInstances` and `capabilties.maxInstances` to `1`. 

According to your video, you are running three tests:
- form_authentication.feature
- quarter.feature
- quarter-plan copy.feature

These three feature specs run in parallel for now. Not sure if this could be an issue.

Could you isolate the feature, that freezes your tests? You can isolate them, by putting just one filename / feature spec name in to `specs` setting in `wdio.conf`. So you can try out one by one. (I assume the form_authentication.feature is just the spec that comes with the template ...)

Please attach the complete terminal output as well.

**Comment by Jimmy-RF** [comment]
Hello @viper3400 , I was doing all things that you said me and here  is the new video, as you can see on the video, the problem is that the test never finish, the browser instances never close it. the test it's frezze I thought that was for the code: Wait.for(Duration.ofSeconds.....  but that has nothing to do.

The strange is that in the log: events.ndjson said that serenity do all things correctlly but as you can see never finish the test :( 


https://user-images.githubusercontent.com/100356221/195984172-611a6757-2fba-46df-8ead-bdd4cf560039.mp4

[events.ndjson.zip](https://github.com/serenity-js/serenity-js/files/9791915/events.ndjson.zip)


Note: This is little example that I created new to report my problem but our project is a little more big so for the moment we need continue with serenity js 2.xx but we need to talk here inside the company to migrate to serenity js 3.xxx

**Comment by viper3400** [comment]
Okay, so it's hard to judge without seeing the whole setup.

From what you've said:
- I assume you have more tests that run and now found this one that won't run. 
- You've tried to isolate the failing test from you project into this simple template.

Am I right? 

So what can we do next:
- Is the effect in you productive project the same, e.g. would the `events.ndjson`will say the same?
- Which automation protocol do you use to automate chrome, DevTools, WebDriver?
- Could you share your `wdio.conf`(you can anonymize sensible data)?
- Which `logLevel` is configured in `wdio.conf`? Can you set it to `trace` to get maybe more information?
- Would it be the same, if you would run `npm run test` from a terminal outside your Visual Code instance?
- What I see for now, you just put the `s` into the field and then continue just with some `Log`. Would automation continue if you'd try to enter another value into the login field or if you would try to put a password in?
- Would it be the same when you try to fill in the `s` into https://the-internet.herokuapp.com/login ?
- Could you provide your this test in a GitHub repo? If there are sensitive data, you can anonymize it. The test need not to run, it's just that we can see more of the project.

**Comment by Jimmy-RF** [comment]
The problem is that all my big project doesn't work because the automation is frezzes but you're OK I created this example because all my projects doesn't work now.. I don't know Why...... in bold all my commnents

Is the effect in you productive project the same, e.g. would the events.ndjsonwill say the same? --> **yes sr the same problem**
Which automation protocol do you use to automate chrome, DevTools, WebDriver? --> **I belive that WebDriver but i don't know sure, where i see that**
Could you share your wdio.conf(you can anonymize sensible data)? --> **yes no problem I can share this project witout problem.**
Which logLevel is configured in wdio.conf? Can you set it to trace to get maybe more information? --> **I dont know hot to configure that if you have a little example I can do that**
Would it be the same, if you would run npm run test from a terminal outside your Visual Code instance? --> **yes sr the same, I executed by Iterm from MAC and the result was the same**
What I see for now, you just put the s into the field and then continue just with some Log. Would automation continue if you'd try to enter another value into the login field or if you would try to put a password in? --> **Yes in the code that I shared I completed user and password inside the example page of the template**
Would it be the same when you try to fill in the s into https://the-internet.herokuapp.com/login ? **Yes sr the same problem in all pages**
Could you provide your this test in a GitHub repo? If there are sensitive data, you can anonymize it. The test need not to run, it's just that we can see more of the project. --> **Ofcourse all things that we need to try to solve this problem jejeje**

Here the repo :
https://github.com/Jidarofa/serenitybug

**Comment by Jimmy-RF** [comment]
I change the configuration about the page because our page is only access by VPN so this repo is whit the page example that serenity template has.

**Comment by viper3400** [comment]
The log level can be changed [here](https://github.com/Jidarofa/serenitybug/blob/d99d7a7d429706cd03ea24c6e38a4a9706ae3330/wdio.conf.ts#L11).

I had to remove the [tag](https://github.com/Jidarofa/serenitybug/blob/d99d7a7d429706cd03ea24c6e38a4a9706ae3330/wdio.conf.ts#L42) as well to get the example running.

I don't have the freeze effect that you describe, at all. At First, I ran into a cucumber timeout of 5 seconds coming from the [cucumber code](https://github.com/cucumber/cucumber-js/blob/5c57ee02d372d40bd1188aad4eef43b437b7a6d8/src/user_code_runner.ts#L80):

```
[test:execute] [0-0] Error in "Using username and password to log in"
[test:execute] Error: function timed out, ensure the promise resolves within 5000 milliseconds
[test:execute]     at Timeout._onTimeout (/Users/jan/Development/serenitybug/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
[test:execute]     at listOnTimeout (node:internal/timers:559:17)
[test:execute]     at processTimers (node:internal/timers:502:7)
```
But the I've seen that you already increased the timeout in your [step definitions](https://github.com/Jidarofa/serenitybug/blob/d99d7a7d429706cd03ea24c6e38a4a9706ae3330/features/step-definitions/quarter-plan.ts#L16). When adapting this to the example feature, it runs without issues on my site.

```
> serenity-js-cucumber-webdriverio-template@1.0.0 test
> failsafe clean test:execute

[clean] 
[clean] > serenity-js-cucumber-webdriverio-template@1.0.0 clean
[clean] > rimraf target
[clean] 
[failsafe] Script 'clean' exited with code 0
[test:execute] 
[test:execute] > serenity-js-cucumber-webdriverio-template@1.0.0 test:execute
[test:execute] > wdio wdio.conf.ts
[test:execute] 
[test:execute] 
[test:execute] Execution of 1 workers started at 2022-10-15T16:15:10.226Z
[test:execute] 
[test:execute] [0-0] RUNNING in chrome - /features/authentication/form_authentication.feature
[test:execute] [0-0] PASSED in chrome - /features/authentication/form_authentication.feature
[test:execute] 
[test:execute]  "@serenity-js/webdriverio" Reporter:
[test:execute] [0-0] --------------------------------------------------------------------------------
[test:execute] [0-0] features/authentication/form_authentication.feature:25
[test:execute] [0-0] 
[test:execute] [0-0] Form-Based Authentication: Using username and password to log in
[test:execute] [0-0] 
[test:execute] [0-0]   Given Alice starts with the "Form Authentication" example
[test:execute] [0-0]     ✓ Alice navigates to 'https://the-internet.herokuapp.com/' (1s 918ms)
[test:execute] [0-0]     Alice picks example called Form Authentication
[test:execute] [0-0]       ✓ Alice clicks on the first of available examples where Text property does equal 'Form Authentication' (90ms)
[test:execute] [0-0]     ✓ Alice waits for 5s (5s 1ms)
[test:execute] [0-0]   When she logs in using "tomsmith" and "SuperSecretPassword!"
[test:execute] [0-0]     Alice logs in as tomsmith
[test:execute] [0-0]       ✓ Alice enters 'tomsmith' into the username field (22ms)
[test:execute] [0-0]       ✓ Alice enters 'SuperSecretPassword!' into the password field (38ms)
[test:execute] [0-0]       ✓ Alice clicks on the login button (34ms)
[test:execute] [0-0]   Then she should see that authentication has succeeded
[test:execute] [0-0]     Alice verifies that authentication has succeeded
[test:execute] [0-0]       Alice verifies that flash alert is present
[test:execute] [0-0]         ✓ Alice ensures that the flash message does become visible (431ms)
[test:execute] [0-0]       ✓ Alice ensures that the text of the flash message does include 'You logged into a secure area!' (6ms)
[test:execute] [0-0] 
[test:execute] [0-0] ✓ Execution successful (7s 709ms)
[test:execute] [0-0] 
[test:execute] [0-0] --------------------------------------------------------------------------------
[test:execute] [0-0] features/authentication/form_authentication.feature:26
[test:execute] [0-0] 
[test:execute] [0-0] Form-Based Authentication: Using username and password to log in
[test:execute] [0-0] 
[test:execute] [0-0]   Given Alice starts with the "Form Authentication" example
[test:execute] [0-0]     ✓ Alice navigates to 'https://the-internet.herokuapp.com/' (193ms)
[test:execute] [0-0]     Alice picks example called Form Authentication
[test:execute] [0-0]       ✓ Alice clicks on the first of available examples where Text property does equal 'Form Authentication' (104ms)
[test:execute] [0-0]     ✓ Alice waits for 5s (5s 2ms)
[test:execute] [0-0]   When she logs in using "foobar" and "barfoo"
[test:execute] [0-0]     Alice logs in as foobar
[test:execute] [0-0]       ✓ Alice enters 'foobar' into the username field (14ms)
[test:execute] [0-0]       ✓ Alice enters 'barfoo' into the password field (12ms)
[test:execute] [0-0]       ✓ Alice clicks on the login button (49ms)
[test:execute] [0-0]   Then she should see that authentication has failed
[test:execute] [0-0]     Alice verifies that authentication has failed
[test:execute] [0-0]       Alice verifies that flash alert is present
[test:execute] [0-0]         ✓ Alice ensures that the flash message does become visible (412ms)
[test:execute] [0-0]       ✓ Alice ensures that the text of the flash message does include 'Your username is invalid!' (8ms)
[test:execute] [0-0] 
[test:execute] [0-0] ✓ Execution successful (5s 948ms)
[test:execute] [0-0] 
[test:execute] 
[test:execute] 
[test:execute] Spec Files:       1 passed, 1 total (100% completed) in 00:00:15 
[test:execute] 
[failsafe] Script 'test:execute' exited with code 0
```

What about the message `npm does not support Node.js v15.14.0` that can be seen in your video? 
Could you try with a supported [Node.js version](https://github.com/Jidarofa/serenitybug/blob/d99d7a7d429706cd03ea24c6e38a4a9706ae3330/package.json#L33) and npm version, just to make sure that this is not an issue here.

**Comment by viper3400** [comment]
Create a [gitpod](https://gitpod.io/#https://github.com/viper3400/jidaforu-serenitybug/tree/gitpod-integration) for this, so you can give it a try, directly. Just run `npm run test` at the terminal and the test should run.

**Comment by Jimmy-RF** [comment]
Do you have documentation and examples about types of logs? and where can I found it?


@ viper 3400v maybe do you have windows? because I tried to execute the same example in windows and all test executed correctly to me too and testing in gitpod headless mode work correctly too.

@viper 3400v It isn't posibele to have a little remote session in my computer?? 

or I don't know if you have another idea about my strange issue 

because also I sended  my project to another coworker and he had the same problem.. We have Mac os

**Comment by viper3400** [comment]
About the docs:

What do you mean with "types of logs"? Do you mean the available log levels? This is basically a feature of [WebdriverIO](https://webdriver.io/docs/options#loglevel).

For Serenity/JS you can enable the [ConsoleReporter](https://serenity-js.org/modules/console-reporter/), the [BDD Report](https://serenity-js.org/modules/serenity-bdd/) and the [StreamReporter](https://serenity-js.org/handbook/reporting/stream-reporter.html). But I think you are aware of all of this possibilities.

Obviously you can enable a more [verbose logging for npm](https://docs.npmjs.com/cli/v8/using-npm/logging), as well. (But be aware, that this docs are for npm v8. Not sure, since when this logging is in place, as this page does not exist in docs of v6 or v7, but yeah, maybe just the docs are missing.)

About the OS:

I tried it on MacOS Montery version 12.6.

What are your Node.JS and npm versions?

```
jan@MiniMac ~ % node --version
v16.17.0
jan@MiniMac ~ % npm --version
8.15.0
jan@MiniMac ~ % 
```

Does the example run for you on gitpod?

In the very first description of this issue you mentioned, that "it was working normally" for you, but than stopped working:

If you would do a fresh clone of the [template](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template), put the `Wait` and the `timeout` into the tests, would it run again on your machine?

Otherwise, please make sure you have a supported Node.JS and npm version.

@jan-molak : Something obvious I missed?

**Comment by Jimmy-RF** [comment]
Hello @viper3400  I was in holiday here in my country I'm back.. 

I saw that we have the same Mac OS version, also I tried gitpod and work correctly.

I was thinking and is possible that some antivirus policy is bloking our test? or chromedriver. version??

**Comment by Jimmy-RF** [comment]
Hello I was checking and I have chrome version: 106.0.5249.119, How can I change my path to execute with other chrome version because I maybe this is the problem.. because I saw that gitpod has chrome version 105

**Comment by jan-molak** [comment]
Hey @Jimmy-RF - hope you had a good holiday?

> I saw that we have the same Mac OS version, also I tried gitpod and work correctly.

Great, thanks for checking!

> I was thinking and is possible that some antivirus policy is bloking our test? or chromedriver. version??

It's hard to tell without seeing your setup I'm afraid; The suggestions from @viper3400 are sound; definitely check the type of protocol you're using, you can see [example configuration here](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/examples/webdriverio-mocha-todomvc/wdio.conf.ts#L49-L61).

If you're using the `webdriver` protocol, make sure the version of [`chromedriver`](https://www.npmjs.com/package/chromedriver) Node module defined in your `package.json` is compatible with the version of Chrome you're running - in your case you'll need `106.0.1`.

## Debugging

Apart from that, you might also want to run WebdriverIO through a [debugger](https://webdriver.io/docs/debugging/). This will allow you to pause the test after the first interaction and inspect the error log in the browser (you can interact with Chrome dev tools once the test is paused in the debugger).

Since I see you're on Serenity/JS 2, first you'll want to create an interaction to `Debug` like this  (Serenity/JS 3 has a built-in interaction for that):

```
const Debug = () => Interaction.where('#actor sets a breakpoint', actor => {
  debugger;
});
```

Then, you can add it to your workflow:

```typescript
actor.attemptsTo(
  Navigate.to(...),
  Enter.theValue('s').into(...),
  Debug(),
  // other activities
)
```
Once you run the test through a debugger, it will pause on the `debugger` statement with the browser window open and you should be able to inspect the browser's error log via dev tools tab.

Hope this helps!

**Comment by Jimmy-RF** [comment]
@jan-molak  and @viper3400  I was checking the branch: git checkout renovate/chromedriver-106.x inside [cucumber and berdriver template](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template)

if you put a Wait.for(Duration.ofSeconds(5)) inside file steps.ts like this example: 

Given('{actor} starts with the {string} example', async (actor: Actor, exampleName: string) =>
    actor.attemptsTo(
        Navigate.to('/'),
        PickExample.called(exampleName),
        Wait.for(Duration.ofSeconds(5))
    )
);

and your version chrome is: 106.0.5249.119 (Build oficial) (x86_64)

You can reproduce the problem... that is that.


[test:execute] [0-0] Error in "Using username and password to log in"
[test:execute] Error: function timed out, ensure the promise resolves within 5000 milliseconds
[test:execute]     at Timeout._onTimeout (/Users/jimrodriguez/Documents/exa106/serenity-js-cucumber-webdriverio-template/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
[test:execute]     at listOnTimeout (node:internal/timers:557:17)
[test:execute]     at processTimers (node:internal/timers:500:7)
[test:execute] [0-0] 2022-10-19T00:40:04.035Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/")
[test:execute] [0-0] 2022-10-19T00:40:04.035Z INFO webdriver: [POST] http://localhost:9515/session/d3f5c520301228ca9f1c914122da4ab7/url
[test:execute] [0-0] 2022-10-19T00:40:04.035Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/' }
[test:execute] [0-0] 2022-10-19T00:40:06.202Z INFO webdriver: COMMAND takeScreenshot()
[test:execute] [0-0] 2022-10-19T00:40:06.202Z INFO webdriver: [GET] http://localhost:9515/session/d3f5c520301228ca9f1c914122da4ab7/screenshot
[test:execute] [0-0] Error in "Using username and password to log in"
[test:execute] Error: function timed out, ensure the promise resolves within 5000 milliseconds
[test:execute]     at Timeout._onTimeout (/Users/jimrodriguez/Documents/exa106/serenity-js-cucumber-webdriverio-template/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
[test:execute]     at listOnTimeout (node:internal/timers:557:17)
[test:execute]     at processTimers (node:internal/timers:500:7)
[test:execute] [0-0] 2022-10-19T00:40:19.047Z ERROR @wdio/runner: Error: 1 async operation has failed to complete within a 5s cue timeout:
[test:execute] [0-0] 12s 845ms - [Photographer:TakePhotosOfInteractions] Taking screenshot of 'Alice waits for 5s'...
[test:execute] [0-0]     at Timeout._onTimeout (/Users/jimrodriguez/Documents/exa106/serenity-js-cucumber-webdriverio-template/node_modules/@serenity-js/core/src/stage/StageManager.ts:43:35)
[test:execute] [0-0]     at listOnTimeout (node:internal/timers:557:17)
[test:execute] [0-0]     at processTimers (node:internal/timers:500:7)
[test:execute] [0-0]  Error:  1 async operation has failed to complete within a 5s cue timeout:
[test:execute] 12s 845ms - [Photographer:TakePhotosOfInteractions] Taking screenshot of 'Alice waits for 5s'...
[test:execute] [0-0] 2022-10-19T00:40:19.049Z INFO webdriver: COMMAND deleteSession()
[test:execute] [0-0] 2022-10-19T00:40:19.049Z INFO webdriver: [DELETE] http://localhost:9515/session/d3f5c520301228ca9f1c914122da4ab7

**Comment by viper3400** [comment]
Hi @Jimmy-RF , with the `Wait` you have to raise the timeout of the step as you (did before)[https://github.com/Jidarofa/serenitybug/blob/f9632206077cfe0c89c51e0bef6777451209c672/features/step-definitions/steps.ts#L17].

@jan-molak: Is there a global setting for this timeout? `waitForTimeout` in `wdio.conf` seems to have no effect here!?

**Comment by jan-molak** [comment]
> @jan-molak: Is there a global setting for this timeout? 

For `Wait.untul` - not yet, pending #1083

For Cucumber - it's [`setDefaultTimeout`](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/timeouts.md)

@Jimmy-RF - your step timeout has to be greater than `Wait.for(Duration)`

**Comment by Jimmy-RF** [comment]
Hi @jan-molak and @viper3400 firts thank you...

Finally I identified that there are a little issue with the chrome version: **106.0.5249.119**

Because I do downgrade to chrome version: **105.0.5195.52** and work perfectly.

So I don't know if it is possible to do something for this version.. for now I will to use this chrome version :)

Thank you guys.

**Comment by viper3400** [comment]
Hi @Jimmy-RF , great to hear that you are able to work again. Can we close this issue?

**Comment by Jimmy-RF** [comment]
> Hi @Jimmy-RF , great to hear that you are able to work again. Can we close this issue?

Yes yes @viper3400  and thank you for all your time  and also thank you @jan-molak
