### ISSUE TITLE
using sub-folder does not work with serenityJS-rest

### ISSUE THREAD

**Issue by LayMui** [serenity-js/serenity-js#1343]
I like to create a sub-folder called api-tests for my project to store all the API tests using serenityJS-rest
cos i like to share with the UI-based tests using serenityJS-webdriverio

however cucumber.js didn't pick up the feature file
https://github.com/LayMui/sh-user-management-api-tests/blob/master/Issue.md

how can I configure such that I can use a sub-folder within my project to run the serenityJS-rest tests?

**Comment by jan-molak** [comment]
As per our [conversation on Gitter](https://gitter.im/serenity-js/Lobby?at=6357d74acf41c67a5cc97738)

I think the issue is with how `test:report` script is invoked; have a look at this line in the log:
```
[test:report] > serenity-bdd run --features ./api-tests/features/*
```

I think shell might try to expand the `./api-tests/features/*` argument, which confuses Serenity BDD

Instead, try to define the `test:report` script in your `package.json`:
```
"test:report": "serenity-bdd run --features 'api-tests/features'"
```

**Comment by LayMui** [comment]
This helps and this is fixed. but when I run the test using yarn test:stage, it didn't get to run the test scenario see https://github.com/LayMui/sh-user-management-api-tests/blob/master/Issue.md

> As per our [conversation on Gitter](https://gitter.im/serenity-js/Lobby?at=6357d74acf41c67a5cc97738)
> 
> I think the issue is with how `test:report` script is invoked; have a look at this line in the log:
> 
> ```
> [test:report] > serenity-bdd run --features ./api-tests/features/*
> ```
> 
> I think shell might try to expand the `./api-tests/features/*` argument, which confuses Serenity BDD
> 
> Instead, try to define the `test:report` script in your `package.json`:
> 
> ```
> "test:report": "serenity-bdd run --features 'api-tests/features'"
> ```

this helps and this is fixed. but when I run the test using yarn test:stage, it didn't get to run the test scenario see https://github.com/LayMui/sh-user-management-api-tests/blob/master/Issue.md

**Comment by jan-molak** [comment]
> This helps and this is fixed.

Thanks for confirming.

> it didn't get to run the test scenario 

I see that you `test:test:stage` script invokes: `cross-env NODE_ENV=stage cucumber-js --tags="@api"`

At the first glance, this seems correct. I'd suggest checking that:
- there are scenarios tagged with `@api`
- cucumber-js is correctly configured to scan `api-tests/features` directory and not the default `features` directory.
 
Please see ["Finding your features"](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-features) in Cucumber docs, and make sure you configure the location of feature files either in a [Cucumber profile](https://github.com/cucumber/cucumber-js/blob/main/docs/profiles.md), or via command line:

```
cross-env NODE_ENV=stage cucumber-js './api-tests/features/**/*.feature' --tags='@api'
```

Note that you will need to do that for any [support code](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#options) as well
