### ISSUE TITLE
Serenity/JS 3.0 - LastResponse.body<Interface>.location / .description not accessible

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1344]
I create this issue to separate it from #1342.

Imagine an interface:
```ts
    interface Product {
        id: number;
        name: string;
        description?: string;
        location?: string;
    }
```

And a test:
```ts
 it('enables access to the response body if interface contains a property called description or location', () =>
       actor.attemptsTo(
       Send.a(GetRequest.to(productDetails)),
       Ensure.that(LastResponse.body<Product>().name, equals('apple')),
       Ensure.that(LastResponse.body<Product>().description, equals('a delicious fruit')),
       Ensure.that(LastResponse.body<Product>().location, equals('fruit bowl')),
       )
  );
```

Then `.description` and `.location` is not accessible as expected. It access the constructor of the `Activity` class instead of the response object.

```error TS2445: Property 'description' is protected and only accessible within class 'Activity' and its subclasses.```

Created a branch in my fork that reproduces this issue: https://github.com/viper3400/serenity-js/tree/repro/1342

https://github.com/viper3400/serenity-js/blob/db4340201fefa130743884fed43d284a2aeb06c6/packages/rest/spec/screenplay/questions/LastResponse.spec.ts#L60

**Comment by LayMui** [comment]
```
interface Forecast<T> {
    status: string,
    errors:  {
        msg: string[],
        errorCode: number
    },
    data: {
        geocode: string
        days: number,
        language: string,
        units: string,
        response: string,
        forecast: T
    }
}

export default Forecast;
```


```
interface DailyForecast {
    dayOfWeek: string,
    minTemp: string,
    maxTemp: string,
    sunriseTimeUtc: string,
    sunriseTimeLocal: string,
    sunsetTimeUtc: string,
    sunsetTimeLocal: string,
    moonrise: string,
    moonset: string,
    qpf: string,
    snowQpf: string,
    description: string,
    validTimeUtc: string,
    validTimeLocal: string,
    day: {
        temperature: string,
        precipChance: string,
        precipType: string,
        relativeHumidity: string,
        qpf: string,
        snowQpf: string,
        uvIndex: string,
        windSpeed: string,
        windDirection: string,
        cloudCover: string,
        description: string,
        shortcast: string,
        iconCode: string,
    },
    night: {
        temperature: string,
        precipChance: string,
        precipType: string,
        relativeHumidity: string,
        qpf: string,
        snowQpf: string,
        uvIndex: string,
        windSpeed: string,
        windDirection: string,
        cloudCover: string,
        description: string,
        shortcast: string,
        iconCode: string
    },
    expirationTimeUtc: string
}

export default DailyForecast;
```

**Comment by LayMui** [comment]
the error comes from this line 
```
  Ensure.that(
                LastResponse.body<Forecast<HourlyForecast>>().data.forecast[0].description.answeredBy(actor), matches(/(.*)/)
            ),
```

**Comment by viper3400** [comment]
@jan-molak, most likely introduced with https://github.com/serenity-js/serenity-js/commit/6c6b5379dfc324a4fb75d758daa7782109f1c5ab#diff-26b33fc130cf57dc7a94635df6d3479db5b302c36355b009dd8d3413a05237c7

**Comment by jan-molak** [comment]
Ah, that's an annoying side-effect. Well spotted, thanks!
I'll need to think about how to address that.

**Comment by jan-molak** [comment]
OK, so I think the best way to do it would be to rename the `location` and `description` fields in `Activity` to names that are _highly unlikely_ to ever exist in userland, e.g. `__activityInvocationLocation` and `__activityDescription` or similar:
https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/core/src/screenplay/Activity.ts#L18-L24

**Comment by viper3400** [comment]
Just not sure about the percentage of _highly unlikely_ 😄

Let me mention, that with the original issue we‘re in the context of API testing and if I look into our response body I can found entries like `__type`. In this context we‘re not always in the user world. When I think about out business domain, we have a concept and the expression `Activity` as well. Cannot predict, if someday someone has to access a field called `__activityDescription`.

Would it be possible to have something like 

```ts
LastResponse.body<Product>().get().location
```

Though this would mean a breaking change.

**Comment by jan-molak** [comment]
Yeah, that's a good point; we could call it something like `__internal_serenity_js_location_do_not_touch_it`, but this looks just terrible ;-)

There's another ES6 feature that could help us out here, though - [`# names`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)

Since `location` field is already marked as `private`, refactoring it into `#location` should be easy. `description` is protected, so I'll need to check where else it's being used. We could turn it into a `private` `#description` field, or worst-case scenario - add a `protected` setter.

**Comment by viper3400** [comment]
Hmm, the `#names` thing looks promising. I guess, you have to try out, if it works within a constructor. Just by strolling through the docs I saw no example where they do it. There is just the last chapter about private constructors. But I guess, you instantiate the `Activity` from somewhere outside the class, as well. And there you need to access both fields. One would to have to try out if this still is possible when using `#names`.

**Comment by jan-molak** [comment]
`#names` should do the trick; To make them work, I had to overcome a challenge with [ES `Proxy` limitations around `#names`](https://javascript.info/proxy#private-fields), that I think you might find interesting as well.
