### ISSUE TITLE
@serenity-js/webdriverio Not able to Switch to Iframe

### ISSUE THREAD

**Issue by chaitanyachekuru** [serenity-js/serenity-js#1345]
I'm using serenity-js/webdriverIO framework and I'm unable to Switch to Iframe. When  I looked at the serenity-js documentation, Switch is supported by Protractor  and couldn't find anything in webdriverIO.
Please help me how to implement Swicthing to Iframes in webdriverIO framework.

**Comment by jan-molak** [comment]
Hi @chaitanyachekuru and welcome to the Serenity/JS Community!
You're right, Serenity/JS 2.0 had support for `Switch` only for Protractor, not for WebdriverIO.

Serenity/JS 3.0 RC, which I'd recommend for any new projects, has a portable interaction to `Switch` that works with all the supported web integration tools, Protractor, WebdriverIO+Webdriver Protocol, WebdriverIO+Devtools Protocol, as well as Playwright.

You'll find plenty of usage examples in the [web specs](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/integration/web-specs/spec/screenplay/models/PageElement.spec.ts#L54-L171). 

Hope this helps!

**Comment by chaitanyachekuru** [comment]
Hi @jan-molak 
Is there any way that I can implement Switching to Iframes in Serenity/JS 2.0 as we have already built the test framework. Please let me know if there are any other alternatives that can be used in webdriverIO framework.

**Comment by jan-molak** [comment]
Sure, you could quite literally copy and paste `Switch` from `@serenity-js/protractor` and replace the protractor API calls with WebdriverIO equivalents

**Comment by chaitanyachekuru** [comment]
Thank you
