### ISSUE TITLE
How to switch to new windows in a test and close browser sessions after the test is completed in @serenity-js/webdriverio

### ISSUE THREAD

**Issue by chaitanyachekuru** [serenity-js/serenity-js#1346]
In my test I have a link when clicked will open in new window and I'm unable to interact with it and close the window. Also how to close the browser session after the test is completed?
There is nothing related to this is available in Serenity/JS WebdriverIO documentation
https://serenity-js.org/modules/webdriverio/
Please help me out. Thanks

**Comment by jan-molak** [comment]
Hi again @chaitanyachekuru!

Same as with my suggestion regarding #1345, if you're using Serenity/JS 2.x, you can implement it based on the interaction to [`Switch.toWindow(nameOrHandleOrIndex)`](https://github.com/serenity-js/serenity-js/blob/0a7c900eea7d29e1647ea915150d7b66450126be/packages/protractor/src/screenplay/interactions/Switch.ts#L162) and the interaction to [`Close`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Close.ts~Close.html)

In Serenity/JS 3.0, there are several nice mechanisms built in that enable you to easily switch between windows:
- [`Page.whichName(expectation)`](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/web/src/screenplay/models/Page.ts#L161)
- [`Page.whichTitle(expectation)`](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/web/src/screenplay/models/Page.ts#L191)
- [`Page.whichUrl(expectation)`](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/web/src/screenplay/models/Page.ts#L221)

There's also a method [`Page#close()`](https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/web/src/screenplay/models/Page.ts#L525) you can use to close a specific window, for example:
```typescript
await actor.attemptsTo(
  Page.whichTitle(includes('pop up')).close(),
)
```
Hope this helps!

**Comment by chaitanyachekuru** [comment]
Hi @jan-molak, this will work if we use serenity-js/protractor, where as I'm using serenity-js/webdriverIO and none of these imports are available for use and not possible to implement these.

**Comment by jan-molak** [comment]
Hey @chaitanyachekuru!

> none of these imports are available for use and not possible to implement these

I'm not sure what imports you're referring to, could you please elaborate some more?

WebdriverIO APIs for interacting with windows are very similar to what Protractor uses.

**Comment by jan-molak** [comment]
Hi, @chaitanyachekuru. I haven't heard from you in a while, so I'm assuming that I've answered your question and will close this ticket. If you have more questions about Serenity/JS, please feel free to join [Serenity/JS Community Chat](https://gitter.im/serenity-js/Lobby).
