### ISSUE TITLE
Wdio after  hooks are not working  in serenity/wdio

### ISSUE THREAD

**Issue by enliltom004** [serenity-js/serenity-js#1368]
### Issue
I am trying to run wdio after hooks in the wdio.conf.ts file and nothing works except OnPrepare and OnComplete.
Hooks which are not working
1. Aftertest
2. After
3. AfterSuite

Node Version :16.16.0

### Dependencies
```
 "devDependencies": {
    "@serenity-js/assertions": "^2.33.10",
    "@serenity-js/console-reporter": "^2.33.10",
    "@serenity-js/core": "^2.33.10",
    "@serenity-js/jasmine": "^2.32.5",
    "@serenity-js/rest": "^2.33.10",
    "@serenity-js/serenity-bdd": "^2.33.10",
    "@serenity-js/webdriverio": "^2.33.10",
    "@wdio/cli": "^7.26.0",
    "@wdio/jasmine-framework": "^7.19.0",
    "@wdio/local-runner": "^7.26.0",
    "@wdio/mocha-framework": "^7.26.0",
    "@wdio/spec-reporter": "^7.26.0",
}
```

**Comment by jan-molak** [comment]
Hi @enliltom004, could you please provide [some more details](https://serenity-js.org/contributing.html#reporting-defects) to help us reproduce the issue?

Ideally, could you please create a minimal reproducible example using one of the [Serenity/JS template projects](https://github.com/serenity-js?q=template&type=all&language=&sort=)?

**Comment by jan-molak** [comment]
Hey @enliltom004! I haven't heard from you for a while, so I'm assuming you managed to solve the issue you encountered. Feel free to open another ticket if you spot any issues with Serenity/JS.
