### ISSUE TITLE
How to build serenityJS locally to test an improvement?

### ISSUE THREAD

**Issue by lufecir** [serenity-js/serenity-js#137]
Hi,

I am working on an extension of the Target class and would like to test it out locally, but I am unable to build SerenityJS locally. 
I am running 'npm run verify' from the root folder, but the build fails on 'core' with the message 

> TSError: ⨯ Unable to compile TypeScript
> lerna ERR! execute src\io\attempt_require.ts (3,16): Cannot find name 'require'. (2304)

Tried tons of things, but nothing seems to work. Is there a specific procedure to follow to build SerenityJS locally? Could not find anything in the documentation.

Regards,

Luc Feys

**Comment by jan-molak** [comment]
Hi Luc!

Serenity/JS uses [Lerna](https://github.com/lerna/lerna) to build all the modules, so, like you say, `npm run verify` needs to be invoked in the root folder. The [main build script](https://github.com/jan-molak/serenity-js/blob/master/.travis.yml) is [defined here](https://github.com/jan-molak/serenity-js/blob/master/scripts/travis/script.sh) and it runs just that one command.

If the TypeScript compiler complains about the absence of [`require`](https://nodejs.org/api/modules.html#modules_require) it could mean that it's somehow unaware of the [node type definitions](https://www.npmjs.com/package/@types/node) ([required here](https://github.com/jan-molak/serenity-js/blob/0534bb96044a135361ff7fb321baba0c261b1f23/package.json#L44)).

I don't see any obvious reason why that would happen but as a sanity check maybe you could check if:
- you're using [node 6](https://github.com/jan-molak/serenity-js/blob/0534bb96044a135361ff7fb321baba0c261b1f23/package.json#L90) (node 8 is supported, but node 6 is what Travis CI is [configured to use](https://github.com/jan-molak/serenity-js/blob/0534bb96044a135361ff7fb321baba0c261b1f23/.travis.yml#L6) at the moment)
- you have no global node modules that could interfere with the serenity-js projects
- you execute the `npm install` in the project root - a `postinstal` script [invokes lerna bootstrap](https://github.com/jan-molak/serenity-js/blob/0534bb96044a135361ff7fb321baba0c261b1f23/package.json#L38) and installs the child modules' dependencies

Could you please let me know what have you tried so far and what results you have observed?

Thanks,
Jan

**Comment by lufecir** [comment]
Hi Jan,

Thank you for the reply.
I tried again from a fresh clone of the repo with a fresh version of node
(so no global dependencies installed), but the same problem occurs.
I am using windows 10.

Here is the output of npm install, beause I think that is where something
goes wrong:

lerna info version 2.0.0
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info lifecycle preinstall
lerna WARN EHOIST_PKG_VERSION "@serenity-js/cucumber-2" package depends on
@types/cucumber@2.0.0, which differs from the hoisted @types/
cucumber@0.0.35.
lerna WARN EHOIST_PKG_VERSION "@serenity-js/cucumber" package depends on
@types/cucumber@1.3.3, which differs from the hoisted @types/
cucumber@0.0.35.
lerna WARN EHOIST_PKG_VERSION "@serenity-js/cucumber-2" package depends on
cucumber@2.0.0-rc.9, which differs from the hoisted cucumber@1.3.2.
lerna WARN EHOIST_PKG_VERSION "@serenity-js/cucumber" package depends on
cucumber@1.3.3, which differs from the hoisted cucumber@1.3.2.
lerna WARN EHOIST_PKG_VERSION "@serenity-js/rest" package depends on
nock@9.1.4, which differs from the hoisted nock@9.0.5.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna success Bootstrapped 7 packages
[2017-12-29 08:32:16.747] [INFO] ParentBinLinker - Linking dependencies
["@types/chai","@types/chai-as-promised","@types/mocha","@
types/node","@types/sinon","@types/sinon-chai","chai","
chai-as-promised","commitizen","coveralls","cz-lerna-changelog","gh-pages","
gitbook-cli","gitbook-plugin-addcssjs","gitbook-plugin-
advanced-emoji","gitbook-plugin-anchors","gitbook-plugin-editlink","gitbook-
plugin-ga","gitbook-plugin-github","gitbook-plugin-
include-codeblock","gitbook-plugin-rss","gitbook-plugin-
sitemap","gitbook-plugin-styles-less","gitbook-plugin-
youtube","istanbul","istanbul-merge","lerna","lerna-semantic-release","link-
parent-bin","mocha","mocha-testdata","nyc","rimraf","
sinon","sinon-chai","ts-helper","ts-node","tslint","
tslint-microsoft-contrib","typescript"] under children
["core","cucumber","cucumber-2","integration-testing","
mocha","rest","serenity-js"]
added 33 packages, removed 227 packages and updated 6 packages in 107.598s

In the end it mentions 'linking dependencies', but in the node_modules
folders of the packages I only see a '.bin' folder containing scripts.
Anything else I am supposed to see there? Symlinks to dependencies?


Regards,

Luc

**Comment by lufecir** [comment]
Hi Jan,

I have been able to make some progress. 

* Upgrading ts-node to 4.1.0 fixed the 'require' problem I mentioned above.

* Then I ran into an issue with Mocha on windows: https://github.com/mochajs/mocha/issues/2895
No fix is released yet, but I could use a workaround specified in one of the comments in the issue to use escaped double quotes instead of single quotes..

* The next problem was then that some of the tests in package 'core' are OS specific: 
Example: 

`AssertionError: expected 'c:\\Users\\jan\\projects\\serenityjs\\outlet\\some.json' to equal '/Users/jan/projects/serenityjs/outlet/some.json'`

For now, I have just disabled running the tests for 'core', since I don't need to make any changes there. If I do have to make changes in core, I will see if I can make the tests OS agnostic.

* Now I am still running into problems with the tests on 'serenity-js' package. Still need to figure out what is going wrong there. 

Regards,

Luc

**Comment by jan-molak** [comment]
Brilliant, thanks for the update! Let me know which tests are failing on Windows and maybe we could sort them out together?

Thanks,
Jan

**Comment by lufecir** [comment]
Hi Jan,

Some update:
* I have fixed the failing unit tests on core
* I now still have 2 problems in the build:
** Some failing tests in the 'rest' package: all POST and PUT tests are failing
** All Protractor tests are failing in the integration section of the 'serenity-js' package

I have attached the log output of the build. Maybe it rings a bell for you and you could provide me with some pointers where I could start looking. I will be glad to try to help fix this where I can,

I would like to now how I can proceed now. I have two local branches, and would like to know how you would like me to share them:
* one with the fixes for the build on windows
* one with an extension to the Target class that allows nesting targets. I have created unit tests for this, and did manual tests in Protractor tests, but cannot add automated tests since all Protractor tests on the 'serenity-js' package are failing for me. I still would like to create a pull request for this. 

Regards,

Luc
[serentiy-build.log](https://github.com/jan-molak/serenity-js/files/1617670/serentiy-build.log)

**Comment by jan-molak** [comment]
Thanks Luc,

I noticed there's a problem with how [nock](https://www.npmjs.com/package/nock) and [axios](https://www.npmjs.com/package/axios) might sometimes interact so I've [recently replaced nock with axios-mock-adapter](https://github.com/jan-molak/serenity-js/commit/fe7e4c84aaebbadaaac1601aaec98c095442bf7a). Hopefully if you pull the latest changes that should address the issue with @serenity-js/rest tests.

The protractor-related failure looks unusual... 

Maybe if you could raise those two PRs you mention I could try to reproduce the issue locally? I'd be happy to have a look at your extension to the Target class too.

Thanks,
Jan

**Comment by lufecir** [comment]
Hi Jan,

I have created both pull requests.
Have a nice weekend.

Regards,

Luc

**Comment by lufecir** [comment]
Hi Jan,

I was wondering if you had already found some time to look into my pull requests?
I'm looking forward to hear your feedback.

Regards,

Luc

**Comment by jan-molak** [comment]
Apologies, Luc, not yet, but it's on my radar. I'll let you know as soon as I can. Sorry for the delay.

**Comment by lufecir** [comment]
Hi Jan,

Think I will be going back to simple Page Objects. Too bad. Serenity looked quite promising to me, but I need to move on with this. People are breathing down my neck. :-) 
Good luck with this library or any other projects you might be working on.

Regards,

Luc

**Comment by jan-molak** [comment]
Hi @lufecir, sorry, I've been flat out over the last couple of weeks. I'll have more time to review and merge the pull requests this month, so will keep you posted.

One suggestion if you're planning to use page objects - if you keep them small and focused on users' interactions with the system rather than the structure of the system it should be easy to refactor them to follow the screenplay pattern.

Thanks for supporting Serenity/JS!
Jan

**Comment by jan-molak** [comment]
Hi @lufecir!

I realise that last time we spoke you had to use Page Objects to deliver your project. I've been focusing on Serenity/JS 2.0, and unfortunately, didn't have enough capacity to support you with your PR.

Serenity/JS 2.0 is now live and with a [brand new website](https://serenity-js.org) where you can find instructions on how to [build and test the project locally](https://serenity-js.org/contributing.html#the-serenity-js-framework), should you wish to contribute it the future.

I do sincerely hope that you haven't given up on the framework and will find the time to take the new version for a spin!

Best,
Jan
