### ISSUE TITLE
 NoSuchElementError: No element found using locator: By(css selector, *[id="new-todo"])

### ISSUE THREAD

**Issue by anuradhadande** [serenity-js/serenity-js#144]
Got run into an error while executing the feature file provided in the tutorial:
http://serenity-js.org/from-scripts-to-serenity/writing-what-you-would-like-to-read.html

Step Definition: features/step_definitions/todo_user.steps.ts:21
   Message:
     NoSuchElementError: No element found using locator: By(css selector, *[id="new-todo"])
         at elementArrayFinder.getWebElements.then (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:851:17)
         at ManagedPromise.invokeCallback_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:1366:14)
         at TaskQueue.execute_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2970:14)
         at TaskQueue.executeNext_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2953:27)
         at asyncRun (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2813:27)
         at /Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:676:7
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)Error
         at ElementArrayFinder.applyAction_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:482:23)
         at ElementArrayFinder.(anonymous function).args [as sendKeys] (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:96:21)
         at ElementFinder.(anonymous function).args [as sendKeys] (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:873:14)
         at EnterValue.performAs (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/interactions/enter.ts:41:59)
         at /Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/@serenity-js/core/src/screenplay/actor.ts:112:43
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
0m01.500s

Not sure what is causing this issue. Element is present there.

Please help.

**Comment by jan-molak** [comment]
Hi @anuradhadande! Serenity/JS v2 is available now and comes with [template projects](https://github.com/serenity-js) and a [new tutorial](https://serenity-js.org/handbook/thinking-in-serenity-js/index.html).

Please check them out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:

**Comment by rakeshnambiar** [comment]
@jan-molak I have ended up with an issue when I get the `element not found` that breaks the further test execution. I have an exception handling at the method level but it seems this particular error is throwing at the framework level. Unfortunately, I didn't manage to upgrade to the latest version and the version details I am using is mentioned below.

```
    "cucumber": "1.3.2",
    "npm-failsafe": "^0.4.1",
    "protractor": "^5.4.2",
    "protractor-cucumber-framework": "0.6.0",
    "serenity-cli": "^0.11.1",
    "serenity-js": "^1.10.13",
    "webdriver-manager": "^12.1.7",
```

```
E/launcher - No element found using locator
```

**Comment by jan-molak** [comment]
Hey @rakeshnambiar! I'm afraid I don't have the capacity to support version 1.x. Have you considered migrating the one test that's failing to V2 to see if the issue has been addressed?

**Comment by rakeshnambiar** [comment]
@jan-molak  thanks for your reply. I can understand your limitation. I tried to migrate the script to the V2 but due to the screenshot issue I couldn't make the progress https://github.com/serenity-js/serenity-js/issues/362 When I wrote the scripts, I have used the PageObject model approach and not using the Actor. It's not practical to convert everything into the new format.

**Comment by jan-molak** [comment]
Got it, have you considered [my comment](https://github.com/serenity-js/serenity-js/issues/362#issuecomment-604759617)?

**Comment by rakeshnambiar** [comment]
I missed the alert when you commented but I noticed it today when I picked the ticket number. Let me give a try - Thanks a lot.

**Comment by rakeshnambiar** [comment]
Btw do you have the latest V2 template? I will use that and move all the scripts.

**Comment by rakeshnambiar** [comment]
I am also having difficulties to generates the report and it's working only on Java 8. Hopeing this also resolved in the V2.

**Comment by jan-molak** [comment]
> Btw do you have the latest V2 template? I will use that and move all the scripts.

Sure - check out https://github.com/serenity-js/serenity-js-cucumber-protractor-template and let me know how it went.
Also, we have a [community chat](https://gitter.im/serenity-js/Lobby) now if you fancy joining?

**Comment by rakeshnambiar** [comment]
@jan-molak thanks a lot. I am already there on the Gitter chat.  I just cloned the tempated and successfully run the sample test. However the report is not properly generated for me in Win10. Am I missing something? 

![image](https://user-images.githubusercontent.com/20258636/99880030-c7e58380-2c08-11eb-9072-ca07bc9dce6e.png)

**Comment by jan-molak** [comment]
There are two stages to the reporting process - first, Serenity/JS generates json files with intermediary reports (under targer/site/serenity, then Serenity BDD CLI generates HTML based on that. If you get an empty HTML report it could be that the json files did not get generated correctly.

See if your protractor.conf.js correctly configures the Artifact Archive and SerenityBDDReporter services (see the template project). If it does, the next step will be to inspect json reports under target/site/serenity

**Comment by rakeshnambiar** [comment]
I can see `ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),` in the protractor config file. However, the json file is not available on this path. I am using the project template without any modification to make-sure the settings are correct.
