### ISSUE TITLE
My automation it freezes

### ISSUE THREAD

**Issue by Jimmy-RF** [serenity-js/serenity-js#1458]
Hello I'm working with serenity js with cucumber and webdriverio, I was working normally but now I don't not what happen with my framework or PC because I have a very strange issue, I can identify that when I put Wait.for(Duration.ofSeconds(2)), > 2 my automation it freezes.

as you can see in the video when I change the timeout from 2 to 3, never finish my test :( I don't know what happen :( heplllme please.

MAC OS

https://user-images.githubusercontent.com/100356221/195854162-2ee5ad83-b4d5-4290-b9a3-835e3f8a415c.mp4

**Comment by jan-molak** [comment]
Hey @Jimmy-RF - I'd suggest switching to Node 16 LTS first; Note that Node 15 is not supported either by Serenity/JS or WebdriverIO

**Comment by Jimmy-RF** [comment]
Hello @jan-molak sorry but I was in holidays I hope that you has a excellent new year..

I upgrade my node js to 16.16.0 but I have the same problem... when I run my test in Chrome 105 or less my project work correctly as you can see in the next video, but when I execute my project in Chrome 106, 107 or 108 my project doesn't work as you can see in the video.

Also I downloaded the cucumber and wio template in serenity js 3 and not work either.

In the link you can see and example executing the project in chromeversion 105 and 108 and also the project

https://drive.google.com/drive/folders/1HeSyQ2PTQ4tduaiL6xc1SeIQk_C8aTHh?usp=sharing

Thank you so much!!

**Comment by jan-molak** [comment]
No worries, hope you had a good time off. I had a quick look at the videos and admit this is rather strange.

I'd suggest a couple of things you might want to try:
- Can you reproduce the same "hanging" behaviour in a pure WebdriverIO test? I.e. just using the regular WDIO APIs to get through the login screen?
- If not, then I'd check if the behaviour of the system under test is any different in Chrome 105 vs 106? [Chrome 106](https://developer.chrome.com/blog/new-in-chrome-106/) introduced several new features along with a bunch of deprecations and removals, does the UI of your app depend on any of those?
- When the test is in the hanging state, is there anything of interest being logged to the developer tools console? Are there any JavaScript errors? Are there any hanging network connections in the network tab?

**Comment by Jimmy-RF** [comment]
Hello Hello @jan-molak good news :) I installed webio and I saw that I was a problem wiith an element that doesn't work in serenity I idn't know why serenity don't show the problen in the log but now is working correctly.  

Sorry fo the problem

**Comment by jan-molak** [comment]
No worries, glad you managed to sort it out!
