### ISSUE TITLE
Getting a fail scenario when using Ensure that to validate an element visibility

### ISSUE THREAD

**Issue by julian-mesa** [serenity-js/serenity-js#1484]
Hi everyone, 
I'm using the following template in order to run the tests with serenity+playwright:https://github.com/serenity-js/serenity-js-cucumber-playwright-template/

I would like to use the Ensure.that in order to validate the visiblity of the elements, 

This is the element

```
export const LoginForm= {
    username: () =>
        PageElement.located(By.id('username')])).describedAs('test element'),
}
```

This is my validation

```
import { Ensure, equals } from '@serenity-js/assertions';
import { Navigate, Click, Enter, Select, isVisible } from '@serenity-js/web';
import { Answerable, Check, d, Task, Wait } from '@serenity-js/core';

export const Login= {
    using: () =>
        Task.where(`#actor`,
            Ensure.that(LoginForm.username(), isVisible())),
}
```

After the execution I got this in the report

AssertionError: Expected test element to become present but got undefined

The element is visible in the html document. I tried with isPresent but I got the same error. Any ideas about this?

Thanks in advanced.

**Comment by viper3400** [comment]
Hi @julian-mesa, are you sure, this is your code? Looks like there is some confusion with the closing brackets:`.located(By.id('username')]'))`

**Comment by julian-mesa** [comment]
Hi @viper3400 , yes sorry for typo, I changed a little bit the code in order to don't expose information related for the company I'm working on and I messed up, but the code works, the issue is in the Ensure.that line, I'm able to run the code but the test fails in that line. The thing is that if I interact with the element that in this case is a textbox I'm can write  a text using the Enter interaction.

Regards,

**Comment by viper3400** [comment]
Hi @julian-mesa, thought it was a typo ;) 

But still, it's hard to tell without seeing the code. So you say, this will work:

```Enter.theValue('username').into(LoginForm.username())```

Are you sure the page resp. the part of the page was completely loaded, when you access the field? Can you try to put a short ```Wait.for(Duration.ofSeconds(5))``` before you call the `isVisible()` task?

Can you try an `isClickable()` instead of the `isVisible()`?

**Comment by julian-mesa** [comment]
Hi @viper3400,
I tried putting a Wait.for before the Ensure.that and it worked, but I don't want to wait for a static period of time, is there another way to wait until the element is visible in dynamic way?

**Comment by viper3400** [comment]
@julian-mesa , sure: You can either use [Wait.until](https://github.com/serenity-js/serenity-js/blob/dc008deea3df025eff0230546100d89156564a8e/integration/web-specs/spec/screenplay/interactions/Wait.spec.ts#L50) or [Wait.upTo](https://github.com/serenity-js/serenity-js/blob/dc008deea3df025eff0230546100d89156564a8e/integration/web-specs/spec/screenplay/interactions/Wait.spec.ts#L62).

`Wait.until` will wait until the default timeout of your test setup, with `Wait.upTo` you can specify the desired `Duration` for the call. Both  `Interaction`s are polling until the element under question, in you case, `isVisible()`. It would fail, if the element does not become visible within the `Duration`.

**Comment by julian-mesa** [comment]
cool! thanks @viper3400 using the Wait.until works as expected but just one more question, the Ensure.that shouldn't expect implicitly for the condition to be meet?

**Comment by viper3400** [comment]
Hi @julian-mesa, not sure if I get your point. Do you mean you've expected `Ensure.that` to have an implicit _wait_? Well,  `Wait.until` is the implicit _wait_ in Serenity/JS, I guess. If you like to `Ensure.that(anElement(), isVisible)` then it should _already be visible_. 

Normally, I use `Wait.until` for page elements loaded dynamically. If I assume, that all elements are then loaded (for example fields in a form) I go on with `Ensure.that`. 

You can expect the condition to be met in both cases.

**Comment by viper3400** [comment]
Actually, @jan-molak, I wonder where to configure the default timeout for a playwright project. For webdriverio I would do this in the [wdio.conf.ts](https://github.com/serenity-js/serenity-js/blob/dc008deea3df025eff0230546100d89156564a8e/examples/webdriverio-mocha-todomvc/wdio.conf.ts#L88). 

Would it be the `expect.timeout` in [playwright.conf.ts](https://github.com/serenity-js/serenity-js/blob/dc008deea3df025eff0230546100d89156564a8e/examples/playwright-test-todomvc/playwright.config.ts#L22).

(Comments in both of the configuration files are a bit misleading then, I guess)

**Comment by jan-molak** [comment]
@viper3400 so the comment in `playwright.conf.ts` is auto-generated by Playwright Test and related to Playwright's `expect` function:
https://github.com/serenity-js/serenity-js/blob/dc008deea3df025eff0230546100d89156564a8e/examples/playwright-test-todomvc/playwright.config.ts#L17-L23

I wonder if it's best to remove that comment from the template. Config option and comment are valid, but you're right, they might be confusing.

**Comment by jan-molak** [comment]
@julian-mesa 

> just one more question, the Ensure.that shouldn't expect implicitly for the condition to be meet?

In Serenity/JS 3.0.0-RC.44 I introduced a new assertion to `Ensure.eventually(question, expectation)`. 
It evaluates the condition, and if no errors are thrown but the condition is not met, it will evaluate it again with an exponential backoff until the timeout is reached.

The timeout can be configured on a per-assertion basis, e.g.:
```typescript
await actor.attemptsTo(
  Ensure.eventually(element, isPresent()).timeoutAfter(Duration.ofSeconds(3))
)
```
or globally via Serenity/JS configuration (#1083):

```typescript
import { configure } from '@serenity-js/core'

configure({
  interactionTimeout: Duration.ofSeconds(5), // timeout for Wait.until and Ensure.eventually
})
```

Let me know if this addresses your use case and if we can close this ticket?

**Comment by julian-mesa** [comment]
@jan-molak thanks. Sure, we can close the issue.
