### ISSUE TITLE
Report is blank when not using "describe"

### ISSUE THREAD

**Issue by pogodins** [serenity-js/serenity-js#1495]
I recently started exploring Serenity/JS and Playwright integration by referencing https://github.com/serenity-js/serenity-js-playwright-test-template.
What I observed is that when I remove `describe` section from the tests and directly use `it` Serenity report is not generated properly (0 scenarios executed).

After comparing 2 options I found our that when not using `describe` test name and title are blank in `scenario-*.json` file generated by Serenity.

Please take a look at my observations in json file (with describe on left side and without on right side):
<img width="1058" alt="Screenshot 2023-02-08 at 13 37 31" src="https://user-images.githubusercontent.com/15627778/217532546-058bcf9c-ec40-4fd1-967b-e6ef281c9deb.png">

**Comment by jan-molak** [comment]
So it looks like the bug you found, @pogodins, can manifest itself with other runners too. Nice catch!

The fix will involve the following:
- [ ] Cater for missing describe blocks in `@serenity-js/playwright-test` integration
- [ ] Cater for missing describe blocks in `@serenity-js/mocha` integration
- [ ] Cater for missing describe blocks in `@serenity-js/jasmine` integration
- [ ] Guard against missing scenario name in `@serenity-js/serenity-bdd`
- [ ] Report on guards violated in Serenity BDD Reporter in `@serenity-js/console-reporter`
