### ISSUE TITLE
Unable to convert Note.of('someNote') to a string

### ISSUE THREAD

**Issue by harivsudhang** [serenity-js/serenity-js#1496]
I tried the below code but i didnt get what is expected.

Code snippet:
q`https://mywebsite.com/${ Note.of('ID').map(replace(/.*\//, '')) }`

Expected
Expected is that it should display as https://mywebsite.com/12345

Actual
But the output is https://mywebsite.com/{}

Please help

**Comment by harivsudhang** [comment]
@jan-molak Kindly help :(

**Comment by jan-molak** [comment]
Hi @harivsudhang, could you please share the context in which you're using this function call?

In particular, note that `q` produces a `Question` which means that you can use it as an argument with any Serenity/JS Interaction. For example:

```typescript
await actor.attemptsTo(
  Navigate.to(q`https://mywebsite.com/${ Note.of('ID').map(replace(/.*\//, '')) }`)
)
```

However, as questions are dynamic (which means they need to be resolved by an actor), using the construct above in methods that only accept `string` will result in JavaScript will [coerce them](https://developer.mozilla.org/en-US/docs/Glossary/Type_coercion) to a string by calling `question.toString()`. 

For example:
```typescript
console.log(q`https://mywebsite.com/${ Note.of('ID').map(replace(/.*\//, '')) }`)
// outputs 'https://mywebsite.com/{}'
```

```typescript
const result = q`https://mywebsite.com/${ Note.of('ID').map(replace(/.*\//, '')) }` + 'test'
// result will be 'https://mywebsite.com/{}test'
```

Does this answer your question?

**Comment by harivsudhang** [comment]
@jan-molak Hi Jan- thanks for the immediate response, now ì understand that it can be used only in serenity interactions. I was thinking to use it as a plain string where i can pass it to non serenity interactions. 
do you suggest with any snippet where we can extract in a variable as a plain string and pass it to non serenity interactions please.

**Comment by jan-molak** [comment]
Sure, to extract a value from a question, you need to make an actor answer it:

```typescript
const question = q`https://mywebsite.com/${ Note.of('ID').map(replace(/.*\//, '')) }`;
const answer = await actor.answer(question);

console.log(answer);
```

Does this help?

**Comment by harivsudhang** [comment]
@jan-molak Yes it did the trick :) I am really thankful to you for the awesome and seamless framework created by you for us. I am using your SerenityJs for almost 3 years now.
I am looking forward to working with you in 3.0 version too. Thanks again for clarifying.

**Comment by jan-molak** [comment]
Brilliant, thanks for confirming :-) I'm glad Serenity/JS is useful! Would you like to add a few words about your experience with the framework under #898, to be included on the new website?
