### ISSUE TITLE
Serenity Html report always points to target/site/serenity

### ISSUE THREAD

**Issue by harivsudhang** [serenity-js/serenity-js#1518]
@jan-molak 
Hi Jan- Good Morning ! The serenity html reports are always stored only in target/site/serenity. Only the json file is stored in the configured path and not the entire folders and files.
Below is the configuration in my protractor.conf.js file. Please suggest how to override the default path and store the reports in my configured path.

 crew: [
            ArtifactArchiver.storingArtifactsAt(folderPath + 'htmlReports'),
            ConsoleReporter.forDarkTerminals(),
            screenshotsFrequency(),
            new SerenityBDDReporter(),
        ]

**Comment by viper3400** [comment]
Hi @harivsudhang 

You can pass a bunch of command line arguments to the `serenity-bdd run`.
You can customise the`—source` and `—destination` folders according to your needs.

```
$ npx serenity-bdd run --help
serenity-bdd run
 
Invokes the Serenity BDD CLI jar to produce a Serenity BDD HTML report from the
Serenity/JS JSON reports
 
Options:
      --version          Show version number                           [boolean]
      --cacheDir         A relative path to where the Serenity BDD CLI jar file
                         is stored
                       [default: "node_modules/@serenity-js/serenity-bdd/cache"]
      --destination      A relative path to the directory where the Serenity BDD
                         report should be produced
                                               [default: "target/site/serenity"]
      --features         A relative path to the directory containing the
                         Cucumber.js feature files         [default: "features"]
      --artifact         The GAV identifier of the Serenity BDD CLI artifact to
                         use; You're best off with the default option unless you
                         want to experiment.
                            [default: "net.serenity-bdd:serenity-cli:jar:3.1.0"]
      --source           A relative path to the directory containing the
                         Serenity/JS JSON reports
                                               [default: "target/site/serenity"]
      --issueTrackerUrl  Base URL for issue trackers other than JIRA
      --jiraProject      JIRA project identifier
      --jiraUrl          Base URL of your JIRA server
      --project          Project name to appear in the Serenity reports
                                                     [default: "e2e-serenityjs"]
      --shortFilenames   Use unique hashes instead of human-readable names for
                         the HTML files                [boolean] [default: true]
      --log              A Logback log level to pass to the Serenity BDD CLI jar
                            [choices: "warn", "info", "debug"] [default: "warn"]
  -h, --help             Show help                                     [boolean]
```

Don‘t wonder, if an empty `target/site/serenity` folder is created anyway, despite you configured different source and destination. See https://github.com/serenity-bdd/serenity-core/issues/2454

Does this help?

**Comment by harivsudhang** [comment]
> 

Hello @viper3400  - Thanks for a quick response :) It would be great if it does not create a folder with target/site/serenity, otherwise your suggestion works great !

**Comment by viper3400** [comment]
Hi @harivsudhang 

The `serenity-cli` is part of the `serenity-core` project. This project is part of [Serenity BDD](https://serenity-bdd.github.io/). Serenity BDD is for Java. Serentiy/JS re-use the `sernity-cli` for the purpose of creating the Serenity BDD style reports.

For me, the created folder is not a big issue. If it's a blocking issue for you, I'd suggest to comment and / or upvote https://github.com/serenity-bdd/serenity-core/issues/2454. 

As a fix has to be applied there, I'd also suggest to close this issue, as you are now able to configure your Serenity/JS project report.

**Comment by harivsudhan** [comment]
@wakaleo Thanks John for your response, Since there is another issue opened long back on this. We can close this now.
