### ISSUE TITLE
Serenity 3.0 migration from Serenity 2.0

### ISSUE THREAD

**Issue by harivsudhang** [serenity-js/serenity-js#1519]
@jan-molak 
Hi Jan- Good Morning ! I am bit worried that I might need to do too many changes when we start migrating to the SerenityJS version 3.0. Currently i am using SerenityJs protractor with cucumber in Typescript with Version - "^2.33.10".

I am using the below Code snippet 
 upButton: () => Target.the('Go to Top Button').located(by.id('btnUpwardsId')),

 await actorCalled('User').attemptsTo(
            Wait.upTo(Duration.ofSeconds(10)).until(upButton, isClickable()),
            Scroll.to(upButton),
            Click.on(upButton));

This is just a snippet, I have huge scenarios with such syntax. Kindly suggest me how can i handle this with 3.0. The reliability with SerenityJS may impact with my Clients. :( Thanks in advance !

**Comment by jan-molak** [comment]
Hey @harivsudhang!

You're right: `Target` to `PageElement` change does require a code change, as per the [migration guide](https://github.com/serenity-js/serenity-js/blob/main/documentation/serenity-js.org/blog/2022-08-12-upgrading-to-serenity-js-3.md).

It should be a reasonably straight-forward regex replacement, though:
```
Target.the\((?<description>.*?)\).located\(by\.(?<selectorType>.*?)\((?<selector>.*?)\)\)
```

Using a JetBrains IDE you could do something like this:
<img width="775" alt="Screenshot 2023-02-27 at 10 18 13" src="https://user-images.githubusercontent.com/1089173/221537086-2b51e717-8bc8-4489-846a-25e2de957ab6.png">

Having said that, if people find migrating code from v2 to v3 challenging, please upvote this ticket and I'd be happy to look into writing an automated codemod.

**Comment by harivsudhang** [comment]
@jan-molak 
I understand, but is it possible to continue with the same 2.0 version even after 3.0 is released? Also is it possible to use protractor along with this? Please suggest

**Comment by jan-molak** [comment]
Hey @harivsudhang - no, version 3.0 introduces several backwards-incompatible changes. In particular, class `Target` is replaced by `PageElement` and `PageElements` classes.
This change requires consuming code to be updated, hence the major version bump in the framework itself.

Does this help?

**Comment by harivsudhang** [comment]
Thanks Jan for the response 👍

**Comment by jan-molak** [comment]
You're welcome! There's also a v2->v3 migration guide that will be published with the new website - https://github.com/serenity-js/serenity-js/blob/main/documentation/serenity-js.org/docs/about/serenity-js-v3.mdx
