### ISSUE TITLE
Ability to use Serenity-js for screen scraping

### ISSUE THREAD

**Issue by nbarrett** [serenity-js/serenity-js#153]
Hi @jan-molak - another curveball question from me - sorry! 

I've got a requirement on an app that I have built to use serenity-js as in a production 'screen-scraping', rather than testing capacity.  I need to query and push data into a third-party application that does not have an API, so I am trying to work out how I might call the working mocha specs that I have written in serenity-js from my production code and acheive this integration via the app's web-ui. Architecturally, my application has a node-js backend (fortunately at the same release level as serenity-js) with an angular-js front end. The flow would be something like this:

-  A user invokes some http request within the angular application (containing some parameters) 
- The http request gets forwarded to a node express endpoint on the server.
- The node express endpoint would somehow invoke the ** serenity-js spec, and pass the parameters to it. 
- Serenity-js would run the spec to completion which would perform the necessary screen-scraping,  culminating in some data parsing of the page returning a `PromiseLike<MyData[]>`. 
- The data would then be passed back up to the stack to the angular client. Or it could persist the data to the database if a 'synchronous' end to end flow was too time-consuming.

Okay, most of that I can achieve already, but the bit I am having trouble visualising is how I can bootstrap the serenity-js (and protractor) process, within the endpoint that is already running in its own node server process?

** Protractor would be configured with a headless chrome browser, given that the whole thing is running on my server (actually hosted in heroku)

**Comment by nbarrett** [comment]
Hi @jan-molak - I've done some experimentation and made some progress with an out of process integration between my express app and the serenity specs by using `require('child_process').exec;` as outlined in this pretty good [article](http://krasimirtsonev.com/blog/article/Nodejs-managing-child-processes-starting-stopping-exec-spawn). I guess my question here was whether you could visualise an in-process solution. For instance on Java projects in the past I've written production applications that call upon selenium features to perform screen scraping and I want(ed) to use Serenity-js for exactly the same thing (but potentially without a test framework layer). I'd welcome any thoughts in this area! 👍

**Comment by jan-molak** [comment]
Have a look at how I'm running the [integration tests](https://github.com/jan-molak/serenity-js/blob/48a6e6fb504a60490c0f35efdd83545b10bc599d/packages/cucumber/spec/recognises_scenario_results.spec.ts), and the [ChildProcessReporter](https://github.com/jan-molak/serenity-js/blob/48a6e6fb504a60490c0f35efdd83545b10bc599d/packages/integration-testing/src/child_process_reporter.ts) in particular.

It shows how you can report progress between two processes. Does that help?

**Comment by nbarrett** [comment]
Ah great thanks for that @jan-molak - you are using `child_process` as well (fork rather than exec - is there a benefit?). Good to see that I'm on the right track in using an out-of-process solution....

**Comment by jan-molak** [comment]
Hey @nbarrett - based on our conversations since this ticket was opened I believe that you managed to get this setup working? Would you care to write a blog post about it so I could link it in [the community section](https://serenity-js.org/community/events-and-articles.html#articles) of the new website?

**Comment by nbarrett** [comment]
Yes, I'm sure I could do something along those lines 👍
