### ISSUE TITLE
Pause to debug

### ISSUE THREAD

**Issue by AG0819** [serenity-js/serenity-js#154]
Is there any sort of 'break' like in Java for serenity-js? I have a step that selects an option from a dialog, the dialog automatically closes after selection. The step successfully clicks on the option I want then it times out without going to the next step (the next step is the one that is ensuring the dialog closed).
Thanks!

**Comment by jan-molak** [comment]
Hi there! Would my suggestion from #83 help?

**Comment by AG0819** [comment]
Having trouble implementing the debugger:



import { Interaction, PerformsTasks, Task, UsesAbilities, AnswersQuestions
} from '@serenity-js/core/lib/screenplay';



export class Debug implements Interaction {
    performAs(actor: UsesAbilities & AnswersQuestions): PromiseLike<void> {
        throw new Error('Method not implemented.');

        const Debug = () => Interaction.where('#actor pauses to debug',
actor => {
            debugger;
            return Promise.resolve();
            });
    }
}

**Comment by AG0819** [comment]
I used console.debug() instead and I'm getting unhandled promise rejection
(id: 19) CAnnot read property 'toString' of undefined then the timeout
happens

**Comment by jan-molak** [comment]
Hey @AG0819! In Serenity/JS 2.0 you should be able to implement an interaction to `Debug` as follows:

```typescript
const Debug = () =>
    Interaction.where(`#actor pauses to debug`, actor => {
        debugger;
    });
```
then
```typescript
actor.attemptsTo(
    Debug(),
);
```

Let me know if this helps!
Jan

**Comment by jan-molak** [comment]
Hi @AG0819 I haven't heard from you in a while, so will assume that my last suggestion has helped. Please feel free to open another ticket or join [Serenity/JS Community Chat](https://gitter.im/serenity-js/Lobby) if you have further questions.
