### ISSUE TITLE
Loop in serenityjs 3.0

### ISSUE THREAD

**Issue by harivsudhan** [serenity-js/serenity-js#1600]
@jan-molak 
Hi Jan- Below is the snippet of Loop I am using currently as per serenityjs 2.0 version. For the latest serenityjs 3.0 how to do i convert the below. Please suggest

```typescript
await actorCalled('tester').attemptsTo(
    Loop.over(elementLocators).to(
    Wait.upTo(ReusableMethods.durationInSecs())
        .until(Loop.item<ElementFinder>(), isPresent()),
    Scroll.to(Loop.item<ElementFinder>()),
    Ensure.that(Value.of(Loop.item<ElementFinder>()), equals(actualValue))
));
```

**Comment by jan-molak** [comment]
Hi @harivsudhan! Sure, what's `elementLocators` in your code sample, please?

**Comment by jan-molak** [comment]
[`PageElements`](https://serenity-js.org/api/web/class/PageElements) extends [`List`](https://serenity-js.org/api/core/class/List), which means you can use [`PageElements.forEach`](https://serenity-js.org/api/web/class/PageElements#forEach).

So you'd have:

```typescript
const percentageFields = () =>
  PageElements.located(By.css('input[inputmode = "text"]'))
    .describedAs('Percentage Fields')

await actorCalled('tester').attemptsTo(
    percentageFields().forEach(({ item, actor }) => 
        actor.attemptsTo(
            Wait.upTo(ReusableMethods.durationInSecs())
                .until(item, isPresent()),
            Scroll.to(item),
            Ensure.that(Value.of(item), equals(actualValue))
        )
    )
));
```

Also, note that in Serenity/JS 3 you can configure the default [interaction timeout](https://serenity-js.org/api/core/class/SerenityConfig#interactionTimeout), so you might be able to remove `.upTo(ReusableMethods.durationInSecs())` and simplify the code further.

Let me know if this helps?

**Comment by harivsudhan** [comment]
You are simple awesome 👏 🤩
