### ISSUE TITLE
Failure in Press.spec.ts when running protractor-web tests

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1614]
Hi Jan, when I try to `make verify report` Serenity/JS on the `main` branch on my local machine I still run into issues with the `./integration/protractor-web` tests with the `Press.spec.ts`.

[report-protractor.zip](https://github.com/serenity-js/serenity-js/files/11179444/report-protractor.zip)

My current setup:

MacBook Pro with
- Apple M2 Pro
- 16 GB
- MacOS Ventura 13.3
- NodeJS 16.19.1

I run into the same error as described [here](https://matrix.to/#/!JsJujYDGNOlDhPFgDS:gitter.im/$EQbcJUsXcXAxOdUfosdi3nVjukmSE1bA01S1QBPUkrg?via=gitter.im&via=matrix.org), but this time I'm not on Windows but on MacOS.

I think, you are on MacOS as well? Are you able to run the tests, locally?

If I would add some `TakeScreenshot` tasks in their, I can get it work. So I still assume this is a timing issue with the Copy/Paste tasks. Have the impression, the string gets not selected in time and therefore gets not copied at all. The test pastes then an empty string.

Edit: It works on a Mac Mini, with a 3.2 GHz 6-Core Intel Core i7 processor (16 GB / Ventura 13.3). So it really looks like a timing issue with the `Press` operations and Protractor. 🤔 

Well, the easiest solution for now would be to ignore this the `protractor-web` tests, locally ...

**Comment by jan-molak** [comment]
Hey @viper3400, my M2 has only just arrived, but you're right I'm also seeing occasional failures in this test. What's interesting is that on my Intel-based 2018 MacBook Pro and on Ubuntu Linux, the test passes every time.

I agree it looks like a timing issue, but I need to investigate this further to understand if that's an issue in Serenity/JS, Protractor on M2, Chromedriver on M2, or Chrome on M2...

**Comment by jan-molak** [comment]
Fixed in 3.1.3, thanks for reporting the issue!
