### ISSUE TITLE
Testing a cookie value on serenity-js

### ISSUE THREAD

**Issue by marktigno** [serenity-js/serenity-js#180]
Hello! I just want your comments on this. I'm trying to expand the capability of my tests to verify a cookie value of the web browser. Here's a sample code I have made:

    export const Cookie = {
        verify: (key: string, expectedValue: string) => Interaction.where(`#actor gets cookie ${key}`, actor => {
            const browse = BrowseTheWeb.as(actor);
            return browse.manage().getCookie(key).then(function(cookie) {
                expect(cookie.value).eventually.equal(expectedValue);
            });
        }),
    };

Any comments to improve further this or am I doing the right way? Thanks! ^_^V

**Comment by jan-molak** [comment]
Hey @marktigno!

Serenity/JS 2.0 ships with dedicated questions about [`Cookie`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/Cookie.ts~Cookie.html), as well as the new [assertions library](https://serenity-js.org/modules/assertions/) to address this use case:

```typescript
import { Ensure, equals } from '@serenity-js/assertions';
import { Cookie } from '@serenity-js/protractor'; 

actor.attemptsTo(
    Ensure.that(Cookie.valueOf('myCookie'), equals('expectedValue')),
);
```

Hope this helps!
Jan
