### ISSUE TITLE
Customize the photographer/reporter

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#183]
Hi,

I wondered if/how we could customize the photographer. Here some ideas:
- Editing the screenshot 'take' policy [as described here for SerenityBDD](https://johnfergusonsmart.com/serenity-bdd-tip-fine-tuning-screenshots-living-documentation/) - Do the same options work? Shall it be also put in a serenity.properties file? protractor.conf.js ?
- Can we ask the photograph to -for ex.- trigger F12 before any capture?
- Can we ask one of the two reporter to retrieve some browser logs (ex. the F12/console logs)?

I would be really interested in understanding how this works & how this can be achieved, by using, extending or enhacing serenityJs.

**Comment by jan-molak** [comment]
Hi there!

Configuration options of the built-in [`Photographer`](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/src/serenity-protractor/stage/photographer.ts#L77) are not as advanced as the Serenity BDD version. You can configure it to [take screenshots of failures](https://github.com/serenity-js/tutorial-journey-planner/blob/master/protractor.conf.js#L30) or all the tasks and interactions encountered (which is the default behaviour).

The `Photographer` is not capable of triggering keys, so you'll either need an `Actor` to do that for you or create an alternative `Photographer` that performs the additional action. As you can [see here](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/src/serenity-protractor/stage/photographer.ts#L114), a reporter can access the current Actor, so technically you could use that to perform an additional interaction.

Does that help?

**Comment by san-ouadghiri** [comment]
Ok I'll have a look and try to come back with what I found.

I'm also considering a [Chrome DevTool](https://chromedevtools.github.io/devtools-protocol/) integration. I feel like it could be awesome. I'm not sure how it could turn out or be displayed but, I'll have a look and see what I can make out of it.

**Comment by jan-molak** [comment]
Sorry @san-ouadghiri, I must've missed your last comment. Chrome DevTool integration sounds like a brilliant idea! What exactly do you have in mind?

**Comment by jan-molak** [comment]
Hey @san-ouadghiri! Serenity/JS 2.0  ships with a completely re-written [`Photographer`](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html), which you can configure as per the [API docs](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html):

```javascript
// protractor.conf.js
const { ArtifactArchiver } = require('@serenity-js/core');
const { 
  Photographer, 
  TakePhotosOfFailures,
  TakePhotosOfInteractions,
  TakePhotosBeforeAndAfterInteractions,
} = require('@serenity-js/protractor');

exports.config = {

    serenity: {
        crew: [
            ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),

            // to take photos when an interaction fails (fastest):
            Photographer.whoWill(TakePhotosOfFailures),

            // to take photos when after every interaction, no matter the outcome
            // (useful when generating living documentation):
            // Photographer.whoWill(TakePhotosOfInteractions), 

            // to take photos before and after every interaction, no matter the outcome
            // (slowest, but good for debugging):
            // Photographer.whoWill(TakePhotosBeforeAndAfterInteractions)
        ]
    },

    // ... rest of the config omitted for brevity
};
```

Hope this helps!
Jan
