### ISSUE TITLE
Serenity/JS should allow sharding tests for better scalability in large CI systems

### ISSUE THREAD

**Issue by muhqu** [serenity-js/serenity-js#1950]
### What's the problem you're trying to solve?

We have over 100 tests and like to run them across multiple test executors in our CI environment. A single machine can only run a few browsers in parallel due to memory consumption. Being able to run the tests across multiple machines allows for better scaling.

### How would you like to solve it?

The [playwright](https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines) and [vitest](https://vitest.dev/guide/cli.html#shard) test runners support a `--shard` parameter, that evenly splits the number of tests to run. 
e.g. if you have 100 tests `--shard=1/4` would execute test 1-25, `--shard=2/4` would execute test 26-50, etc… 

### Are there any alternatives?

Using the playwright test runner… but it would be great to have this ability with WebdriverIO as well.

### How can we make it happen?

- [ ] [work on this myself](https://serenity-js.org/contributing/#propose-an-enhancement) (with Serenity/JS team guidance)
- [ ] [hire the Serenity/JS team](https://github.com/sponsors/serenity-js) to build it for me
- [ ] add it to the Serenity/JS backlog and wait for a volunteer

**Comment by muhqu** [comment]
Also created a [feature request](https://github.com/webdriverio/webdriverio/issues/11243) for the webdriverio test runner to add native support for a test sharding.

**Comment by jan-molak** [comment]
This feature was added to WebdriverIO and released https://github.com/webdriverio/webdriverio/issues/11243 

Thanks!
