### ISSUE TITLE
REST API (axios) + SerenityJS, and SerenityJS reporting

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#208]
Hi @jan-molak,

It's me again :)!
I just manage my first serenity/axios usecase on a basic get. An when I looked at the report I saw an white screen capture as per UI tests. I was naively hoping for 
![image](https://user-images.githubusercontent.com/28731357/39297672-6707ed9a-4944-11e8-9b6d-4687df2a39c5.png).

So here are my questions:
- How would you advise to deactivate the Photgraph when we do an API call ? (For ex. could we deactivate it when a given ability, here CallAnAPI, is executed ?)
- Do you plan on an axios/serenityJS integration (in the same style that serenityBDD+rest-assured) including fancy reporting ? If someone else where to do it, how would you advise to proceed?

I hope you can lead me on the right path, as you usually do. Thanks again for your work,
San.

**Comment by jan-molak** [comment]
Hi @san-ouadghiri! Yes, I'm planning to improve that soon.

**Comment by san-ouadghiri** [comment]
I'll wait patiently for it. I'll look forward to trying it ! Thanks for your investment 🙇.

**Comment by jan-molak** [comment]
Hi @san-ouadghiri and thanks for your patience! The great thing about the [modular design](https://serenity-js.org/handbook/integration/architecture.html) of the recently released Serenity/JS 2.0 is that that you can use it to write REST tests using pure Jasmine or Cucumber, without Protractor. This means that you don't have to use the browser if you don't need it. Check out the [examples](https://github.com/serenity-js/serenity-js/tree/master/examples/cucumber-rest-api-level-testing).

The new version also ships with a completely re-written implementation of the [`@serenity-js/rest module](https://serenity-js.org/modules/rest/).

Please check it out and let me know what you think!

Jan
