### ISSUE TITLE
Serenity/JS should allow to hide sensitive information in report

### ISSUE THREAD

**Issue by eyesopen** [serenity-js/serenity-js#2165]
### What's the problem you're trying to solve?

Most if not all cases when testing e2e will require to perform login and having password exposed in the report is not an option. So i believe most of us end up with custom question that returns *** instead of the actual value. 

### How would you like to solve it?

Could we have an inbuilt question, that will allow to hide the value from the report? Or any other solution of course :)

### How can we make it happen?

- [ ] [work on this myself](https://serenity-js.org/contributing/#propose-an-enhancement) (with Serenity/JS team guidance)
- [ ] [hire the Serenity/JS team](https://github.com/sponsors/serenity-js) to build it for me
- [X] add it to the Serenity/JS backlog and wait for a volunteer

**Comment by viper3400** [comment]
Hi, I think this is about `Enter.theValue('password').into(passwordfield)`. 

So it's not just about passwords in general, but about all sensitive data. This should not be that much effort, I pushed my attempt to implement a `Enter.theSensitiveValue('password').into the passwordfield)`.

The corresponding line in the report would read:

`#actor enters '[masked sensitive value]' into the name field`.

What do you think @eyesopen and @jan-molak ?

**Comment by eyesopen** [comment]
Both solutions looks great, I will take any :-). Thank you

**Comment by 1MateuszKruk** [comment]
I see there is a solution, but thanks for an implementation of that 😄 I had a simillar problem, but opted into doing my own Interaction for that. Just wanted to add that it may be better to put it like this
```js
Enter.theValue(...).into(...).discretely()```

**Comment by jan-molak** [comment]
Cool, thanks for the feedback! We'll be shipping `Masked.valueOf(..)` by Mr. @viper3400  shortly!

**Comment by jan-molak** [comment]
Shipped in Serenity/JS 3.16.0 🚀
