### ISSUE TITLE
Improve Serenity-Js documentation and examples

### ISSUE THREAD

**Issue by sergiomcunha** [serenity-js/serenity-js#217]
Improve documentation of Serenity-JS with: 
- Having all the code used on documentation available on a repository on GitHub;
- Have full examples of them, for instance on screenplay pattern (Using a bunch of actors that have Abilities and give interaction to the ability, after that how to use interactions and abilities after this);
- A full example of a project with Authentication, after that do something on application.
- Narrow the approaches used on the documentation, use mostly the same example, and don't jump too much over different projects, so it became easy to understand the differences between approaches.

**Comment by scaddenp** [comment]
I am finding it a right struggle finding out what builtin questions, tasks, interactions etc are pre-defined (is there any way other than trawling source code?). It is not like they come up with any form of code completion. Situation is not much better with java Serenity but take approach that if it in that project, something like it might be here. Even a simple list of available classes and what the import path is would be helpful. This "issues" section of github is so far an invaluable resource however.

**Comment by jan-molak** [comment]
Hey @sergiomcunha - you're right, improving the docs is one of my goals with Serenity/JS 2.0. Stay tuned!

**Comment by rajeshwarp** [comment]
Hi Jan,

When can we expect Serenity/JS 2.0 and Its Tutorial(Paid/Free).

**Comment by jan-molak** [comment]
Hi @sergiomcunha, @scaddenp and @rajeshwarp - it turned out that Serenity/JS 2.0 required far more work than I originally anticipated... but it's live now with a new website and new API docs available at [serenity-js.org](https://serenity-js.org). I'd love to hear what you think!

With the release out of the way, I'm planning to focus on a Serenity/JS online course. Is this something you'd be interested in?

**Comment by rajeshwarp** [comment]
Hi @jan-molak 

Congratulations ! Yes I would like to take up the online course.

Thanks!

**Comment by jan-molak** [comment]
I'm planning to start working on a Serenity/JS course in the near future. If you'd like to stay up to date with developments in this space, please follow me on [Twitter](http://twitter.com/@JanMolak) or [LinkedIn](https://www.linkedin.com/in/janmolak/) 😃
