### ISSUE TITLE
When using Examples, if Feature description is the same, then only last test is shown in generated report

### ISSUE THREAD

**Issue by emosGambler** [serenity-js/serenity-js#220]
Hi, I think I've found some issue.

**Steps to reproduce:**
1) Create a feature with Examples table. Feature description should not be parametrized:
![https://i.imgur.com/wrQs9kn.png](https://i.imgur.com/wrQs9kn.png)

2) Implement steps and run these tests. Tests are executed in loop and the console confirms it:
![https://i.imgur.com/ss8Myzo.png](https://i.imgur.com/ss8Myzo.png)

3) Generated report does only show last test loop:
![https://i.imgur.com/zBl2KpR.png](https://i.imgur.com/zBl2KpR.png)
![https://i.imgur.com/Oqw5s1I.png](https://i.imgur.com/Oqw5s1I.png)

**Additional comment:**
When I have parametrized Feature description using provided variable _product_ (Feature: Add _product_ to the todo list), then report shows correct number of tests executed. **Can you please review if this is a valid issue?**

Repository with this issue: 
https://github.com/emosGambler/protractor-typescript-cucumber-serenity-example/tree/feature/its-a-bug

**Comment by jan-molak** [comment]
Hi there and thanks for taking the time to prepare such a detailed report, much appreciated!
You're right, this is an issue with the current implementation of the cucumber js integration.

It has been reported in #168, where I also mention a way to work around the problem while the root cause is being addressed (#162).

Stay tuned!
Jan

**Comment by emosGambler** [comment]
Hi Jan,

Yup, I have figured out the same workaround. Thank you for the reply and I am looking forward to see this fixed.

Best regards,
Jacek
