### ISSUE TITLE
Serenity/JS Github main README.md - Deadlink to playwright-test in handbook

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#2239]
### What happened?

In the main README.md of the [Serenity/JS Github page](https://github.com/serenity-js) the link to playwright-test in handbook is broken. There is a tick before the question mark for the piwik campain:

https://serenity-js.org/handbook/test-runners/playwright-test/`?pk_campaign=readme&pk_source=github

Should most likely be:
https://serenity-js.org/handbook/test-runners/playwright-test/?pk_campaign=readme&pk_source=github

<img width="1483" alt="Bildschirmfoto 2024-02-17 um 10 22 03" src="https://github.com/serenity-js/serenity-js/assets/11006334/de0a5698-233e-4c92-90b4-37ec54c61782">

### What did you expect to happen?

The  page should open in browser.

### Node.js version

-

### How to reproduce the bug.

Click on the link.

### Serenity/JS version

```shell
-
```

**Comment by jan-molak** [comment]
Thank you, nice catch!
