### ISSUE TITLE
Screenplay option to    browser.switchTo().frame(element(by.tagName('iframe')));

### ISSUE THREAD

**Issue by tfarrar** [serenity-js/serenity-js#227]
I need the ability to switch to a frame similar to way it is done in protractor below.  Is there a way I can access the lower level browser in serenity screenplay to switch to frame?

  it('should switch to iframe', function () {
            browser.switchTo().frame(element(by.tagName('iframe')));
        });

// Screenplay option I found.
   Switch.toWindowNumber(1),
    BrowseTheWeb.as(actor).switchToParentWindow(0),
    BrowseTheWeb.as(actor).switchToWindow(),

**Comment by AbhineetSharmax** [comment]
Hi Tfarrar,

For a workaround you may manage, serenity iframe switches using below line of code,

browser.driver.switchTo().frame(0);

**Comment by marktigno** [comment]
Try checking my solution on that here https://github.com/jan-molak/serenity-js/issues/233
