### ISSUE TITLE
serenity-bdd: The id generated doesn't include the path to the feature, so the context of the feature is lost.

### ISSUE THREAD

**Issue by jfstephe** [serenity-js/serenity-js#2299]
### What happened?

My rough project structure is:

src/components/componentA/features/coolFeatureA.feature
src/components/componentA/features/**commonBehaviour**.feature
src/components/componentB/features/coolFeatureB.feature
src/components/componentB/features/**commonBehaviour**.feature

but because the 'id' generated by the serenity-bdd only takes into account the name and not the directory structure, the commonBehaviour.feature of componentA has the same id as commonBehaviour.feature of componentB so effectively I lose the results belonging to one of the features.

I don't think this is an issue with serenity-cli.

I did see the [docs](https://serenity-js.org/handbook/reporting/serenity-bdd-reporter/#serenity-bdd-best-practices), which say to name the feature file the same as the feature, but:
a) it doesn't explain clearly what happens if you don't do that
b) it doesn't mention anything about uniqueness of filenames etc

### What did you expect to happen?

The full path to be included in the 'id' property of the generated json.

### Node.js version

18.18.2

### Execution environment

windows (bash shell)

### How to reproduce the bug.

I can't do that unfortunately due to a locked down dev environment, but hopefully you can see the issue.

### Serenity/JS version

```shell
This is very difficult in my environment (quite restricted :-( ).

I'm using 3.14.2 for each of:

@serenity-js/console-reporter
@serenity-js/core
@serenity-js/cucumber
@serenity-js/serenity-bdd

and unfortunately can't go higher as later versions of serenity-cli seen to need java version above 8.
```

**Comment by jfstephe** [comment]
Hi,
Thanks for getting back to me and sorry my description could have been clearer.

The issue seems to be that for each of the different component feature scenarios, they are generating a html file with the same name.

From this image you can see that hovering over the Scenario link for the first scenario ('ComponentA') shows "http://localhost:8080/5e72e68f6e6fad16b416ae304454bfc7396b8b75642807c09a65f10f62962643.html"
![image](https://github.com/serenity-js/serenity-js/assets/3627080/e43f08a6-969d-491f-95b9-6fea3eb4aabe)

If I hover over the Scenario link for the first scenario ('ComponentA') or the second scenario ('ComponentB') it shows the link to the same URL :-(.

The bad news for me is that I created a sandbox to reproduce this outside of work and this was not reproducable in v3.21.2 of serenity-js, but was in 3.14.2 :-(.

In desperation, I was looking around and I then came across the serenity-bdd run option "shortFilenames"

npx serenity-bdd run --shortFilenames false

In 3.14.2, unsurprisingly this gives both feature scenarios a file of:

http://localhost:8080/component_operation_should_work_test.html

I tried this in 3.21.2 confident that this too would be broken but it's not. 2 unique files are generated:
http://localhost:8080/e660bf90e893052ddae193567b91a6ac__sl_features_sl_operationworks.html and 
http://localhost:8080/ac51b47f2908bcf6b929ff76b17eb1fe__sl_features_sl_operationworks.html

(This isn't a problem for me, I'm just sharing that to reassure you that this is ok in 3.21.2, although the 'shortname' output is not quite as short or readable any more).

----------
**Aside:**
As a minor hack, for my 3.14.2 case (if you recall we don't have java 11 available on my project), I did manipulate the json output from cucumber-js - appending random numbers after the ids: 
{"id":"component-operation-should-work;test"....
became
{"id":"component-operation-should-work;test123"....
etc
and that seemed to fix it. So I may run some thing after cucumber-js and before serenity-bdd to insert the json filename at the end of the ids within the file.

------------

**In summary:**
* If you have any better suggestions to my above hack (e.g. hooking in to the @serenity-js/cucumber formatter) please let me know
* As you can see from my screen shot, there is still no 'context'. The directory structure is missing which I think is because I don't have a single 'features' root directory like you do.

src/**components/componentA**/features/coolFeatureA.feature
src/**components/componentA**/features/commonBehaviour.feature
src/**components/componentB**/features/coolFeatureB.feature
src/**components/componentB**/features/commonBehaviour.feature

What I'd hope to see is that "components/<componentName>" is part of the hierarchy much like you have with "Another" and "Api" in your screenshot.

Hopefully that sheds some light on the issue. If it's not clear let me know. Thanks for a great tool!

**Comment by jan-molak** [comment]
I see, thanks for the detailed explanation and for confirming that the behaviour is correct in 3.21.2.

Serenity BDD 4 changed how it identifies test results, so apart from the `id` field in the `json` report, it uses the new [`path` and `pathElements`](https://github.com/serenity-js/serenity-js/blob/45c5ed7d410a632f43e74b6da8818b6cd00908d9/packages/serenity-bdd/src/stage/crew/serenity-bdd-reporter/processors/transformations/scenarioDetailsOf.ts#L10) fields as well. Those fields are also used to generate the file name you saw when you disabled `shortFilenames`.

In your case, this behaviour is what helps to differentiate feature files that share the same name.

> if you recall we don't have java 11 available on my project

I'd strongly recommend upgrading to Java 11 or newer, either by installing it on your machine, or by running Serenity BDD in a Docker container that offers a newer Java version (e.g. [`amazoncorretto`](https://hub.docker.com/_/amazoncorretto))

Once you update your runtime environment, you'll have access to newer versions of both Serenity/JS and Serenity BDD and associated frameworks like Playwright or WebdriverIO.

> Thanks for a great tool!

You're welcome, I'm glad it helps

**Comment by jfstephe** [comment]
Yup I'll try and upgrade.

FYI I think there's a minor issue on the "Test results" because you don't see path information you get on the summary page

Summary:

![image](https://github.com/serenity-js/serenity-js/assets/3627080/71858e2f-3cb6-4586-984f-68f6126071fd)

Test Results:
![image](https://github.com/serenity-js/serenity-js/assets/3627080/34e3884a-fb26-49f7-87f7-739df1dcd574)

Perhaps not the original issue I stated so happy to create a new one, if you can confirm the issue?

**Comment by jan-molak** [comment]
> Perhaps not the original issue I stated so happy to create a new one, if you can confirm the issue?

Yeah, I think it would be nicer to display the full path. I don't think Serenity/JS has much control over how the manual test results are rendered, though. Would you mind proposing this using the [Serenity BDD issue tracker](https://github.com/serenity-bdd/serenity-core/issues)?

**Comment by jfstephe** [comment]
https://github.com/serenity-bdd/serenity-core/issues/3437 - Done :-)

I'll close this ticket. Can I ask that you look at https://github.com/serenity-js/serenity-js/issues/2306? It may be that I've raised it in the wrong place and it should be over in the other issue tracker.
