### ISSUE TITLE
Serenity/JS could show where the changes between releases have been made in SCM tool (git) and highlight areas that have not been retested

### ISSUE THREAD

**Issue by jfstephe** [serenity-js/serenity-js#2306]
### What's the problem you're trying to solve?

Manual (bear with me) regression test suites can become large and slow to execute. Ideally we'd only regression test the areas of the code that have been affected by modifications since the last release.

I don't think any tool out there ATM has this capability as most test case management tools are so far removed from the code bases they test.

### How would you like to solve it?

Using JFS's approach from [here](https://johnfergusonsmart.com/reporting-manual-test-results-in-serenity-bdd/) for integrating manual testing with feature files through serenity, it's possible to know when a feature was last tested.

Using that information, combined with the information from SCM tools like git it would be possible to create a heat map view ([like this](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-main-win.png)) that could be added to [Serenity BDD Reporter](https://serenity-js.org/handbook/reporting/serenity-bdd-reporter/).

This could be used to guide people as to which areas of the application are more important to focus on for their testing activities.

### Are there any alternatives?

This is an enhancement.

If you think this is valuable, I'd love to discuss this further.

I think there's possible future enhancements to this to possibly use static code analysis to further improve the heatmap to include dependency information e.g. if you change common function X and that is used in component A, B and D then you should consider regression testing them.

### How can we make it happen?

- [X] [work on this myself](https://serenity-js.org/contributing/#propose-an-enhancement) (with Serenity/JS team guidance)
- [ ] [hire the Serenity/JS team](https://github.com/sponsors/serenity-js) to build it for me
- [ ] add it to the Serenity/JS backlog and wait for a volunteer

**Comment by jan-molak** [comment]
@jfstephe - I think it would be best to raise this with [Serenity BDD](https://github.com/serenity-bdd/serenity-core) - a long time ago it had similar functionality available

**Comment by jfstephe** [comment]
Done - thanks :-)
https://github.com/serenity-bdd/serenity-core/issues/3441
