### ISSUE TITLE
Report not generating when a test fails for SerenityJS with Mocha and Supertest.

### ISSUE THREAD

**Issue by kpkiran** [serenity-js/serenity-js#232]
Hi,

I am using serenityJS with mocha and supertest to test the REST based services. The configuration is fine and the tests run fine. The only issue I am facing is, the report doesn't get generated if any one of the test fails. My protractor.conf.js file is as below. Please let me know if you need any further information from my side. I need help on this. 

I am using Mac with node version v9.11.1. 

`exports.config = {
    
    // Framework definition - tells Protractor to use Serenity/JS
    framework: 'mocha',
    frameworkPath: require.resolve('serenity-js'),
    specs: ['features/**/*.feature'],
    cucumberOpts: {
        require: [
            'features/**/*.js'
        ],
        format: 'pretty',
        compiler: 'ts:ts-node/register' // interpret step definitions as TypeScript
    },
    specs: [ 
        'spec/**/*.spec.js'
     ],

    mochaOpts: {
        ui:       'bdd',                  // use the describe/it syntax (default: 'bdd').
        compiler: 'ts:ts-node/register'   // interpret step definitions as TypeScript
    },

    serenity: {
        dialect: 'mocha'
    },

    capabilities: {
        browserName: 'chrome',
      
        chromeOptions: {
           args: [ "--headless", "--disable-gpu", "--window-size=800,600" ]
         }
      }
};`

One of the test looks something like below.

```const expect = require('chai').expect;
const request = require('supertest');
const config = require('../../protractor.conf');
const urlConfig = require('../../config.js')
const configuration = require('../../configuration');
const getEnv = require('../../environment');

const environment = getEnv();

beforeEach(function(){
    this.timeout(10000);
});

describe('Passing the country and locale for departures', () => {
    var country = 'AU'
    it('should not be null', (done)=>{
        request(environment)
        .get(`/v2/departures?country=${country}&locale=en`)
        .end((err, res) => {
            if(err) {
                done (err);
            }
            expect(res.body).to.not.equal(null);
            done();
        });
    });
});```

**Comment by jan-molak** [comment]
Thanks for reporting this issue, @kpkiran! Would you be able to set up a standalone github repo that demonstrates the problem? You could use https://reqres.in/ to represent the API under test.

Thanks!
Jan

**Comment by jan-molak** [comment]
Sure, [here it is](https://github.com/jan-molak/serenity-js/blob/master/package.json#L5).
