### ISSUE TITLE
Not able to find element present in iframe using Serenity JS

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#233]
How can i find element present in iframe.. using chrome browser. Thats somewhere down in tree.. @jan-molak

<Iframe id='broker'>
  <>
     <> 
        <>
        <a id='raise an issue'>

Please, help me find 'raise an issue' which is present in iframe.

**Comment by marktigno** [comment]
Hello! You need to change focus of your test to the iframe element and then find the target object there. Try to use this wrap-up code and use it on your tests:
    
    import { protractor } from 'protractor';
    import { Interaction } from 'serenity-js/protractor';
    export const Window = {
        switchToFrame: (index: number) => Interaction.where(`#actor switches to a frame`, actor => {`
            return protractor.browser.driver.switchTo().frame(index);
        }),
    };

**Comment by marktigno** [comment]
Oh I almost forgot. You need also this code to return to the parent window:

    switchToDefaultContent: () => Interaction.where(`#actor switch back to default`, actor => {
        return protractor.browser.driver.switchTo().defaultContent();
    }),

**Comment by AbhineetSharmax** [comment]
Hello everyone,

I have Figured it using,

browser.driver.switchTo().frame(0);

Hence, it worked like charm.

**Comment by jan-molak** [comment]
@AbhineetSharmax - glad you managed to solve the issue, thanks for letting us know!
@nbarrett - yeah, I think we need a nice built-in way of doing that.
