### ISSUE TITLE
can i get an equivalant to browser.refresh();

### ISSUE THREAD

**Issue by kdp88** [serenity-js/serenity-js#236]
as the title states is there a way to get browser.refresh(); to work or is there a serenity framework way to do it

**Comment by jan-molak** [comment]
Hey @kdp88!

Serenity/JS doesn't support that out of the box yet, but it definitely should :-)
The feature would require exposing one of either of [those two methods](https://github.com/angular/protractor/issues/1143) on the `BrowseTheWeb` ability and creating an `Interaction` utilising that.

In the meantime, you could use something along those lines:

```typescript
import { protractor } from 'protractor';
import { Interaction } from '@serenity-js/core';

const Refresh = () => Interaction.where(`#actor reloads the website`, actor => {
  return protractor.browser.refresh();
});
```

Does that help?
Jan

**Comment by kdp88** [comment]
@jan-molak can you give me your brain 😁🙃🙃 thanks dude appreciate ya

**Comment by jan-molak** [comment]
`interactions/refresh.ts` sounds like a sensible place to host it, yes :-)

**Comment by kdp88** [comment]
@jan-molak any idea why protractor.browser.refresh(); does not work inside --headless mode (protractor.conf.js) but works flawlessly when --headless is commented out?

**Comment by kdp88** [comment]
@jan-molak also when i attempt to utilize the import statement 
`import { Interaction } from '@serenity-js/core';`

i get the followin error (screenshot) any ideas
![image](https://user-images.githubusercontent.com/12736081/41678094-21922be8-7498-11e8-9d9b-8d9e5b78dc1b.png)

**Comment by jan-molak** [comment]
Can you try with `import { Interaction } from '@serenity-js/core/lib/screenplay';`?

**Comment by kdp88** [comment]
Yes sir that worked  like a charm also had to put export const, but for some reason it will not do the refresh in headless mode works perfectly without headless

**Comment by marktigno** [comment]
try to include the `--no-sandbox` with the `--headless` mode. It might work on that way. :)

**Comment by kdp88** [comment]
@marktigno thanks for the suggestion I got that one in my conf.js as well still no dice

**Comment by marktigno** [comment]
another method would be opening again the same page and it will act as a refresh on the browser:

    protected open(url: string, user = 'User') {
        return this.stage.theActorCalled(user).attemptsTo(
            Start.openPage(url),
        );
    }

**Comment by kdp88** [comment]
@marktigno is there a way to store the url to use it as a variable, basically browser.getCurrentUrl().

I guess that would be another interaction? I cant recall if serenity has a native getCurrentUrl

**Comment by jan-molak** [comment]
There's [a question](https://github.com/jan-molak/serenity-js/blob/f7cbfcd39bff526cd4078dd7d67b5577a91c6585/packages/serenity-js/src/serenity-protractor/screenplay/questions/website.ts#L22) that retrieves the value of the current URL so that you can assert on it. You could use the exact same mechanism in the interaction.

Does that help?
Jan

**Comment by marktigno** [comment]
I didn't know about this until I found that now. Thank's @jan-molak! I need to do code change on my other tests here. 😄

**Comment by marktigno** [comment]
Just another question, do you know any implementations to execute back navigation on the browser?

**Comment by jan-molak** [comment]
I'll make a mental note to add those interactions when I extract the `@serenity-js/protractor` module :-)

In the meantime:

```typescript
import { protractor } from 'protractor';
import { Interaction } from '@serenity-js/core/lib/screenplay';

const Navigate = ({
  back: () => Interaction.where(`#actor navigates back`, actor => {
    return protractor.browser.navigate().back();
  }),
});
```

**Comment by marktigno** [comment]
Nice! Thanks for that @jan-molak, I'm doing the same thing here on our end by adding those helper codes on our tests. In the future I'll send PR to have them included on the `@serenity-js/protractor` module. ^_^V
