### ISSUE TITLE
Serenity/JS own integration test reports for web specs are not complete

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#2370]
### What happened?

When running the web-spec tests from integration folder in Serenity/JS main repo, the produced reports are not complete for the web-specs folder.

The links to the features on the overall result page just redirect to index.html. The feature tag at the bottom of the page redirect to pages, that are not existing.

This issue is most likely related to the BDD Report > 4.x and the necessary [requirements hierarchy](https://serenity-js.org/handbook/reporting/serenity-bdd-reporter/#serenity-bdd-best-practices).

### What did you expect to happen?

Links in report direct me to the page presenting the result of the web-spec.

### Node.js version

20.13.1

### Execution environment

macOs Sonoma 14.4.1

### How to reproduce the bug.

Clone Serenity/JS repository, run make, then run `npm run integration-test:webdriverio-web` and inspect the report for this run.

### Serenity/JS version

```shell
Serenity/JS 3.22.4
```

**Comment by jan-molak** [comment]
Thanks, I'll take a look!

**Comment by viper3400** [comment]
I just filed it. It's not urgent nor blocking but points out some limitations introduced with BDD reporter V4.

**Comment by jan-molak** [comment]
Thanks for reporting, @viper3400, I have investigated this further.

Serenity BDD assumes that a test suite has only one root directory, such as `features` or `spec`. In the case of Serenity/JS integration test suite for WebdriverIO, some test scenarios come from the [`integration/web-specs`](https://github.com/serenity-js/serenity-js/tree/aebcb7b47540576437d79f6190c867a455ea695b/integration/web-specs) module, symlinked as `./node_modules/@integration/web-specs`, and some test scenarios are WebdriverIO-specific, and so are located under `./spec`. This means that the common root for both is `.`, which Serenity BDD doesn't seem to support.
