### ISSUE TITLE
Serenity/JS should provide arithmetic functions

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#2420]
### What's the problem you're trying to solve?

Certain test scenarios require performing simple arithmetic operations like subtraction, addition, rounding, and so on. While such functions are reasonably easy to write to support Serenity/JS answerable, it would offer a better developer experience to have them provided out of the box.

An example of such a custom function might look like this:
```ts
const sum = (first: Answerable<number>, second: Answerable<number>) => 
  Question.about('sum', async actor => {
    const firstAnswer  = await actor.answer(first);
    const secondAnswer = await actor.answer(second);
    
    return firstAnswer + secondAnswer;
  })
```

### How would you like to solve it?

Introduce a `Numeric` class in `@serenity-js/core`, offering methods like:

```ts

Numeric.sum(values: ...Array<Answerable<Array<number> | number>>): QuestionAdapter<number>

// This would support:
//   Ensure.that(Numeric.sum(1, 2, 3), equals(6))
//   Ensure.that(Numeric.sum([ 1, 2, 3 ]), equals(6))
//   Ensure.that(Numeric.sum(List.of([ 1, 2, 3 ])), equals(6))
//   Ensure.that(Numeric.sum(
//     Text.of(pageElement1).as(Number), 
//     Text.of(pageElement2).as(Number)
//   ), equals(/* */))
//   Ensure.that(Numeric.sum(
//     Text.ofAll(pageElements).eachMappedTo(Numeric.intValue()), 
//   ), equals(/* */))

```

We'll also need some meta-questions:
```
Numeric.intValue(radix: Answerable<number>).of(text: Answerable<string>): QuestionAdapter<number>
// delegating to Number.parseInt(text, radix)

Numeric.floatValue().of(text: Answerable<string>): QuestionAdapter<number>
// delegating to Number.parseFloat(text)
```

### Are there any alternatives?

Developers could continue to write arithmetic functions themselves

### How can we make it happen?

- [X] [work on this myself](https://serenity-js.org/contributing/#propose-an-enhancement) (with Serenity/JS team guidance)
- [ ] [hire the Serenity/JS team](https://github.com/sponsors/serenity-js) to build it for me
- [X] add it to the Serenity/JS backlog and wait for a volunteer

**Comment by karthikcamarakanti-eaton** [comment]
@jan-molak currently there is no possible way/workaround  of doing this ?

**Comment by jan-molak** [comment]
> @jan-molak currently there is no possible way/workaround of doing this?

@karthikcamarakanti-eaton - there is, a developer can write the desired arithmetic function themselves, for example:

```ts
const sum = (first: Answerable<number>, second: Answerable<number>) => 
  Question.about('sum', async actor => {
    const firstAnswer  = await actor.answer(first);
    const secondAnswer = await actor.answer(second);
    
    return firstAnswer + secondAnswer;
  })
```
