### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by andreasgebauer** [serenity-js/serenity-js#246]
When an AssertionError is raised in a beforeEach method using mocha the SceneFinished event isn't triggered. This leeds to errors like:

[ERROR] (node:5718) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
[ERROR]     at /some-project-path/node_modules/@serenity-js/core/src/reporting/serenity_bdd_reporter.ts:152:95
[ERROR]     at <anonymous>
[ERROR] (node:5718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 359)
[ERROR] (node:5718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jan-molak** [comment]
Nice catch, thanks for letting me know!

**Comment by jan-molak** [comment]
Hi @andreasgebauer! This was a synchronisation issue in the Serenity/JS 1.x implementation of the `SerenityBDDReporter`. [Serenity/JS 2.0](https://serenity-js.org) ships with a completely re-written reporter that doesn't have this problem.

While Serenity/JS 2.0 doesn't support Mocha (yet!), you can use it with Jasmine - check out the [template repository](https://github.com/serenity-js/serenity-js-jasmine-protractor-template)
