### ISSUE TITLE
How to compare an Attribute value to the Website URL

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#249]
Hi,

I'm trying to compare a DOM element's attribute value to a part of my URL. To give some context, basically I click on an element randomly within a menu, then check that the element got highlighted, and then want to check that the URL contains a parameters relevant to the highlighted element (the element got an id in its data-id attribute, this value should also be in the url).

So if I choose precisely element 2, this assertion works
See.if(Attribute.of(Menu.active()).called("data-id"), (value) => expect(value).to.eventually.equals("2"),

Also this works
See.if(Website.url(), (value) => expect(value).to.eventually.contains('2')),

But I want a random pick. So I don't know if it will be 2 or another value, but I want cohesion.
Sadly this (or several variations of it) doesn't work.
See.if(Website.url(), (value) => expect(value).to.eventually.contains(Attribute.of(Menu.active()).called("data-id")),

So I tried a different approch where I would compare the Attribute to the URL substring I would beforehand calculate. Something including some url.substring(). But because Website.url() is not a string (and Website.url().toString does not quite give what i expected :D !) I find myself stuck.

@jan-molak , @everyone, how would you solve that ?

**Comment by jan-molak** [comment]
Hi @san-ouadghiri - this use case is not supported in Serenity/JS 1.x, but it will be supported in 2.0 (due to be released within the next couple of weeks).

In [2.0](https://github.com/jan-molak/serenity-js/tree/2.0) you will be able to:

```typescript
import { Ensure, includes } from '@serenity-js/assertions';
import { Attribute, Website } from '@serenity-js/protractor';

actor.attemptsTo(
  Ensure.that(Website.url(), includes(Attribute.of(Menu.active()).called('data-id')))
);
```

Stay tuned!
Jan

**Comment by jan-molak** [comment]
Hey @san-ouadghiri! Serenity/JS 2.0 is live and ships with a [`@serenity-js/assertions`](https://serenity-js.org/modules/assertions/) module that enables the syntax I suggested in the above post.

Please check it out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
