### ISSUE TITLE
How to get an nth element from list

### ISSUE THREAD

**Issue by emosGambler** [serenity-js/serenity-js#251]
Given I have a `Target` element:

`static Element = Target.the('Element').located(by.css('li'))`

And more than one element is found, then how can I get element number 0, 1, 2, etc from this list?

I'm looking of something like:

`Element.get(2);`

as in protractor.

I cannot figure out this one.

**Comment by san-ouadghiri** [comment]
@emosGambler have you tried just solving that using a xpath expression (which btw works in a protractor or a none-protractor context) ?

Ex. Target.the('"Blabla" input').located(by.xpath('//li[@data-qa = "myelement"][2]'));
or just Target.the('"Blabla" input').located(by.xpath('//li[2]'));
(you can also use css selector, I'm just used to xpath)

If you're unsure of your selector, google can interpret those. So in you dev tools (F12) you look at the DOM (Elements tab) and hit Ctrl-F. In this filed you can search for litteral strings, but you can also enter selectors. Google will interpret them. So searching for //li (and hitting several time Enter) will highlight them one-by-one, when hitting //li[2] will only highlight one even though you hit enter several time.

Last but not least : i actually do not advise you to do that. Today your test search for the "blabla" string which is li n°2. Tomorrow a dev may add a line, and it will be li[3]. Your test will break, or worse, will raise a false positive (the false green is the worse). As much as possible you should prevent relative positions (div/li), ordinated position (li[3]) and text based selectors (text() = "plop"). If you lack an id or an attribute (<button>plop</button>) ask your dev for one ! Else you may have trouble as your product evolve.

Help it help (i hope it reply to your question) & good coding :)
San.

**Comment by emosGambler** [comment]
Hi @san-ouadghiri,

Searching by `li` was just an example. In our project, there are most likely ids assigned to the elements. Using xpath is a solution for small lists, but what if I have list of 100 elements and I want to do with them something. I am not happy to declare a list of 100 different elements using your way: `//li[1], //li[2], ...//li[100]` etc. I wanted to have a solution which will, for example, allow me to iterate through list of elements in code itself. Something like `ListOfTargets.each(target => { // do something });`

Thanks for answer.

**Comment by san-ouadghiri** [comment]
Oh. I did not get your objective the first time.

So if for example yoy want to click on button 1, 2, ..., 100 (so repeat the same action on several elements) you can try what is described in ticket 250. Not to rewrite a selector, i would advise to write a generic target, and to put each element id in the array. You would end up with a table of 100 ids, a selector calling array[n], and the repeater action calling the selector each time with the right id. It should do the trick.

**Comment by emosGambler** [comment]
Hmmm. That should do the trick, but this is quite complicated in my opinion. I will try it soon and I will post back just so we have a solution here.

Thanks!

**Comment by emosGambler** [comment]
Ok, sorry for not responding for so long.

To be honest, this code looks complicated as for something this easy as taking nth element from array of elements. @jan-molak, can you comment on this matter?

**Comment by emosGambler** [comment]
@jan-molak, any help? =(

**Comment by jan-molak** [comment]
@emosGambler - what you're after will be addressed in Serenity/JS 2.0 - [here's an early preview](https://github.com/jan-molak/serenity-js/blob/5a44b914da08318937c3c3df13e19f7161889c0f/packages/protractor/spec/screenplay/questions/Pick.spec.ts#L83) of what this will look like. Thoughts and feedback welcome!

**Comment by nbarrett** [comment]
Nice @jan-molak - phew I'm glad James has now been fired and replaced by [Peter](https://github.com/jan-molak/serenity-js/blob/5a44b914da08318937c3c3df13e19f7161889c0f/packages/protractor/spec/screenplay/questions/Pick.spec.ts#L11), who has now moved onto more extravagant drinks such as [coconut milk](https://github.com/jan-molak/serenity-js/blob/5a44b914da08318937c3c3df13e19f7161889c0f/packages/protractor/spec/screenplay/questions/Pick.spec.ts#L83)! 🤣

**Comment by jan-molak** [comment]
`James` was overworked, he's been doing todo lists for 2.5 years now, we needed a new `Actor` ;-)

**Comment by jan-molak** [comment]
Hi @emosGambler - Serenity/JS 2.0 is live now so you can use the [`Pick`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/Pick.ts~Pick.html) question to pick an n-th element, as well as an element with matching text, and more.

There's a nice example [here](https://github.com/serenity-js/todomvc-demo/blob/904ebf979199989ca686808b3f9992c095883d3d/src/todomvc/ui/TodoList.ts#L15-L17), and plenty of examples in [unit tests](https://github.com/serenity-js/serenity-js/blob/master/packages/protractor/spec/screenplay/questions/Pick.spec.ts).

Please check it out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
