### ISSUE TITLE
when installing this package in current node LTS 22.8.0

### ISSUE THREAD

**Issue by BillyG83** [serenity-js/serenity-js#2518]
### What happened?

My app is node version 22.8.0 as per the node docs, when i run `yarn install` i get this error
```
error @serenity-js/assertions@3.11.0: The engine "node" is incompatible with this module. Expected version "^16.13 || ^18.12 || ^20". Got "22.8.0"
```

when will node version 22.8.0 have support please?

### What did you expect to happen?

a response will get the PM off my back 😅 

### Node.js version

22.8.0

### Execution environment

mac OS, this is before any stack requirement, its on yarn install

### How to reproduce the bug.

- make any app with current node LTS 22.8.0
- yarn install this lib
- see error
```error @serenity-js/assertions@3.11.0: The engine "node" is incompatible with this module. Expected version "^16.13 || ^18.12 || ^20". Got "22.8.0"```

### Serenity/JS version

```shell
3.26.1
```

**Comment by jan-molak** [comment]
Hi @BillyG83, and welcome to the Serenity/JS Community!

> a response will get the PM off my back 😅

Haha, I hope you and your PM have a great day thanks to #2520 😄

**Comment by BillyG83** [comment]
hi @jan-molak thanks for the update this is great! TY
