### ISSUE TITLE
Serenity-JS, screenplay and Test Data Driven?

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#256]
Hi @Jan-Molak, greetings!!

Just wondering is it ok to use test data driven approach for serenity JS screenplay pattern! If Yes, then how can we integrate it with our Scenarios. (Do we have an option to use YML too?). Need your suggestions. Thank you.

**Comment by AbhineetSharmax** [comment]
Hi @jan-molak , for an example..

In Ruby( Watir ).. we read the value from .yml files.

________________________#test data file

<Data.yml>

Links:
  Next: nxt_btn
  Proceed: proceed_btn
_______________________

<StepDefinition/steps.rb>

When(/^Users clicks next$/) do
 on(Click).clickOn("Next")
end
_________________________
<click_on.rb>

class Click

     data = DataMagic.load("Data.yml")
      
#click method to use YML to fetch Links name and click on it
     define clickOn(element)
           link(:id, res["Links"]["#{element}"] ).click
     end

end

___________________________
What's happening, the next button is read from YML and utilizes in clickOn method.

Something like above, wanted to read the value from (.JSON, YML) in Serenity JS.

Thanks.

**Comment by viper3400** [comment]
@AbhineetSharmax, this is quite an old issue. Have you found a solution for it?

There is still no native support for reading YAML files in Serenity/JS.

I do kind of data-driven tests using the new `List.of().forEach` feature in Serenity/JS 3.0.0 RC. I use this to iterate over my custom test data objects and execute `Task`s for each of the object in the list. See #823.

**Comment by viper3400** [comment]
Let's close this issue, you can request to reopen this issue at any time, if it's still an issue to you. You can create a new issue to discuss a feature request for your use case, as well.
