### ISSUE TITLE
Handling Cookie box

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#264]
Greetings jan-molak,

I really love your creation, its a quick way of doing tedious stuffs :)
I have a scenario related to a cookie box, when i hit the website, a cookie box sometimes appears and sometimes it doesnt. 

Is there any implementation in Serenity which will help me check both the conditions?

if (cookiebox.isVisible())
do this..
else
 do this.. 

Please help me.. Thanks.

**Comment by san-ouadghiri** [comment]
I actually have the same issue. I'm in the process but fail to found the right condition.

```
export const HandleCookies = {
    accept: () => Task.where(`#actor accept the cookies`,
        Wait.until(CookieFooter.accept(), Is.clickable()),
        Click.on(CookieFooter.accept()), Wait.until(CookieFooter.accept(), Is.invisible())
    ),
    refuse: () => Task.where(`#actor refuse the cookies`,
        Wait.until(CookieFooter.deny(), Is.clickable()),
        Click.on(CookieFooter.deny()), Wait.until(CookieFooter.deny(), Is.invisible())
    ),
    cleverRefuse: () => Task.where(`#actor refuse the cookies (only if it appears)`, //ONLY USE when your goal is NOT to test the cookie notice, but just to get rid of it
        Check.whether( //Condition I fail to write so that it's true when there, and false when not there
        ).andIfSo(
            Click.on(CookieFooter.deny()), Wait.until(CookieFooter.deny(), Is.invisible())
        )
    )
};
```

Hopefully we can help each other.

**Comment by AbhineetSharmax** [comment]
@san-ouadghiri, Greetings!

A small piece of code that may bring happiness. It worked for me hope it does it for you too :)

browser.isElementPresent(element(by.css('.my_button').then(function(result){

if(result) { return actor.attemptsTo();}
else{});

**Comment by san-ouadghiri** [comment]
Hi @AbhineetSharmax 
Thanks ! How do you make that work as a task? I tried 
```

export class CleverRefuse implements Task {

    performAs(actor: PerformsTasks): PromiseLike<void> {
        browser.isElementPresent(element(by.path(CookieFooter.denyLocator)))
            .then(
            function(result) {
                if (result) {
                return actor.attemptsTo(//myAction...);
            }
    })};
}
```

But my IDE complains it's not a PromiseLike<void>. Id I put any, it's happy, but then I got an error at the execution -> (result: ERROR, error:TypeError: protractor_1.by.path is not a function)

So I wondered how you added it to your code overall.

**Comment by AbhineetSharmax** [comment]
Hi @san-ouadghiri,

by.path is not a function, true!
check for available functions, you may use
className, css, id, linkText, js, name, partialLinkText, tagName, xpath.

also, return an empty task to resolve your another issue.

export class CleverRefuse implements Task {

    performAs(actor: PerformsTasks): PromiseLike<void> {
        browser.isElementPresent(element(by.path(CookieFooter.denyLocator)))
            .then(
            function(result) {
                if (result) {
                return actor.attemptsTo(//myAction...);
            }
return actor.attemptsTo(); //you may add this to resolve your issue.
    })};
}
hope it helps :)

**Comment by jan-molak** [comment]
Hey guys, Serenity/JS 2.0 is live and ships if a completely re-written interaction to [`Check`](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html).

```typescript
import { Check } from '@serenity-js/assertions';
import { Task } from '@serenity-js/core';
import { isDiplayed, Target } from '@serenity-js/protractor';

class CookieBox {
  static modal = Target.the(`cookie box`).located(by.css(...));
  static closeButton = Target.the(`close button`).of(CookieBox.modal).located(by.css(...));
}

const AcceptCookies = () => 
    Task.where(`#actor accepts cookies`,
        Click.on(CookieBox.closeButton),
    );

 actor.attemptsTo(
     Check.whether(CookieBox.modal, isDisplayed())
         .andIfSo(
             AcceptCookies(),
         )
 );
```

Hope this helps!
Jan
