### ISSUE TITLE
Webdriver not exiting

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#267]
Hi Jan-molak,
 greetings!!

a very small query when i run the test, after run, when i check task manager i see many chromedrivers open, how can i close those!! please help.

**Comment by AbhineetSharmax** [comment]
Hi Jan, Any updates, please help :)

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax! I'd love to help, but it's difficult to tell without being able to see what you're seeing.. Would you be able to provide a minimal test case demonstrating the issue?

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax - this used to be an intermittent issue with Serenity/JS version 1 when Protractor was configured to restart the browser between tests.

Serenity/JS version 2 addresses this problem, so could you please give it a try and let me know what you think? Thanks! 

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
