### ISSUE TITLE
OR AND conditions in See.if

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#269]
Hi Jan-molak, 

Was performing See.if yesterday and was wondering about how can we have AND OR in include method!

See.if(Elements.element, text => expect(text).to.eventually.include( '£125' || '£67'))

any help would be appreciating.

**Comment by AbhineetSharmax** [comment]
Hi jan-molak, Thank you for your response. 
I am still not sure how to check for those two either values in See.if . 

as per the Scenario, it display an amount £85 when the switch is ON in environment and it displays £125 when switch is OFF in environment. so either of the values get displayed. How can i handle this situation not sure? please help.

**Comment by jan-molak** [comment]
Interesting! What do you mean when you talk about the switch being ON? Is it an `env` variable or something similar you're relying on?

**Comment by AbhineetSharmax** [comment]
Its something like when some discount scheme is going on so the price would change, but it will remain either of it 129 or 85. But only these two values needs to be checked in a single See.if. :)

**Comment by jan-molak** [comment]
Right, have you tried `expect(text).to.eventually.include.oneOf(['£125', '£67'])` ?

**Comment by AbhineetSharmax** [comment]
Hi Jan, 

very good evening !!! 

Yes i have tried with it.
it says Property oneOf does not exist on type 'PromiseInclude' 

any help please?

**Comment by jan-molak** [comment]
This use case will be addressed by the new `@serenity-js/assertions` module coming with Serenity/JS 2.0 soon.

```typescript
import { Text } from '@serenity-js/protractor';
import { Ensure, equals, or } from '@serenity-js/assertions';

const Widgets= {
  Price: Target.the('price widget').located(by.id('...')),
};

actor.attemptsTo(
    Ensure.that(Text.of(Widgets.Price), or(equals('£125'), equals('£67'))),
);
```

Stay tuned!
Jan

**Comment by AbhineetSharmax** [comment]
Hi jan-molak,

Its really great ! :D

For a workaround i am currently using it as,

expect(txt.includes('£125') || txt.includes('£80')).equals(true);

Happy to get a module as wished 🍹 Thanks again!

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax! Serenity/JS 2.0 is live and ships with a [`@serenity-js/assertions`](https://serenity-js.org/modules/assertions/) module that provides both the [`or`](https://serenity-js.org/modules/assertions/function/index.html#static-function-or) and [`and`](https://serenity-js.org/modules/assertions/function/index.html#static-function-and) functions.

Please check it out and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
