### ISSUE TITLE
Check if an element is focused

### ISSUE THREAD

**Issue by charleshimmer** [serenity-js/serenity-js#272]
I'm trying to write a test that checks if an element is currently focused.  Reading through protractor and selenium docs it seems the way people have solved this is to check if your element matches the element returned by the browser as the currently `active` or `focused` element. (Something like `browser.driver.switchTo().activeElement()`. I can't seem to get this to work with the serenity-js framework.  Anyone done this before or have any tips on how I might do this?

**Comment by charleshimmer** [comment]
I have found I can get the outerHTML of the element I'm trying to test like this `Attribute.of(c).called('outerHTML')` but I get an error of `Ignoring uncaught error RangeError: Maximum call stack size exceeded` when I try and access the browser's currently active element. 

This `browser.driver.switchTo().activeElement()` seems to return a `WebElementPromise`. I think the issue I'm running into is figuring out how to use the WebElementPromise.

**Comment by jan-molak** [comment]
Hi @charleshimmer - apologies for not getting around to responding to your ticket for so long; I was busy with Serenity/JS 2.0 - which is now available and ships with an [`isActive()` expectation](https://serenity-js.org/modules/protractor/function/index.html#static-function-isActive).

Hope this addresses the issue!
Jan
