### ISSUE TITLE
A "/n" portion in Website.url() is interpreted in the assertion error message

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#273]
**Assertion**
See.if(Website.url(), (value) => expect(value).not.to.eventually.contains('#')),

**The website url**
https://mysecretdomain/fr/noworries/#

**The assertion message when the url lacks it's #**
Assertion error: expected 'https://mysecretdomain/froworries' to include '#'

So the /n part disappeared. Maybe it's interpreted and then put in one line anyway? Whatever the cause is, it should not be. This led one of my colleague to wonder if our url was broken here too (not only missing the # part) when it was not. So not a big deal, but it can bring unnecessry confusion.

**Comment by san-ouadghiri** [comment]
(In case it was not at the serenity level, or just in cas you wonder, I use the chai / chai as promised / chai smoothie "expect")

**Comment by jan-molak** [comment]
Thanks @san-ouadghiri, would you be able to paste in the (anonymised) content of the corresponding json report? Thanks!

**Comment by jan-molak** [comment]
Hey @san-ouadghiri - I don't seem to be able to reproduce the issue with Serenity/JS 2.0 alpha.
If you could paste the anonymised content of the corresponding json report then we could confirm if the issue is/was with Serenity/JS or with Serenity BDD CLI.

Thanks!
