### ISSUE TITLE
Couple of questions on serenity interactions, tasks.

### ISSUE THREAD

**Issue by emosGambler** [serenity-js/serenity-js#275]
Hi everyone,

My issues:
1) So I have a feeling like serenity js is missing some of the most basic interactions. Not only I mean the obvious gaps like `Hover.over(target: Target)`, but some more complicated ones like: 

`Click.on(target: Target).if(condition: boolean)`,
`Expect.target(target: Target).Class.toContain(expectedClass: string)`,
`Expect.targets(targets: TargetArray).Text.toEqual(expectedTextForEveryTarget: string)`, etc.

So I do have to create all the interactions myself, which makes me write protractor code anyway and I'm just starting to miss all the screenplay pattern concept, as it is looking more and more like good old page object pattern.

2) In the issue above I've presented the type TargetArray (equivalent of ElementArrayFinder in protractor), but I don't see such invention in serenity js. It would be super useful when you have a grid or something and you need to validate values from this grid. 

3) I completely stopped using tasks, as complexity of the project was increasing, because it was much more nicer to create API-like interactions, such as:

`ValidateGrid.Rows.ToHaveValues.BiggerThan(value: number)`

And creating tasks just not allow me to do such a thing.

***

What are your thoughts? Am I just missing something?

Regards,
Jacek

**Comment by jan-molak** [comment]
Hi @emosGambler!

The recently released Serenity/JS 2.0 ships with additional interactions, such as [`Hover`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Hover.ts~Hover.html).

Other examples from your original post can be addressed as follows:

### Conditional logic
The following logic:
```typescript
Click.on(target: Target).if(condition: boolean),
```
can be expressed as:
```typescript
import { Check, equals } from '@serenity-js/assertions';
// other imports

actor.attemptsTo(
  Check.whether(something, equals(true))
    .andIfSo(Click.on(target) /* , ... other tasks */)
    /* optionally */ .otherwise(/*... tasks if condition not meet */)
);
```
using:
- an interaction to [`Check`](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html)
- [expectations](https://serenity-js.org/modules/assertions/identifiers.html#expectations) from the [`@serenity-js/assertions` module](https://serenity-js.org/modules/assertions/)

### Asserting on CSS classes
The following logic:
```typescript
Expect.target(target: Target).Class.toContain(expectedClass: string)
```

can be expressed as:
```typescript
import { CSSClasses } from '@serenity-js/protractor';
import { Ensure, contain } from '@serenity-js/assertions';

actor.attemptsTo(
  Ensure.that(CSSClasses.of(target), contain(expectedClass)),
);
```

using:
- question about the [`CSSClasses`](https://serenity-js.org/modules/protractor/file/src/screenplay/questions/CSSClasses.ts.html)
- [expectations](https://serenity-js.org/modules/assertions/identifiers.html#expectations) from the [`@serenity-js/assertions` module](https://serenity-js.org/modules/assertions/)

### Asserting on text of multiple elements
The following logic:
```typescript
Expect.targets(targets: TargetArray).Text.toEqual(expectedTextForEveryTarget: string)
```

can be expressed as:
```typescript
import { Ensure, equals } from '@serenity-js/assertions';
import { Text } from '@serenity-js/protractor';

actor.attemptsTo(
  Ensure.that(Text.ofAll(targets), equals([ 'text of element 1', 'text of element 2' ]))
)
```

using:
- question about the [`Text.ofAll`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/text/Text.ts~Text.html#static-method-ofAll) elements
- [expectations](https://serenity-js.org/modules/assertions/identifiers.html#expectations) from the [`@serenity-js/assertions` module](https://serenity-js.org/modules/assertions/)

Hope this helps!
Jan
