### ISSUE TITLE
The Given under Background: is not working 

### ISSUE THREAD

**Issue by malindapw** [serenity-js/serenity-js#282]
Hi my feature file is similar to this , 

```gherkin
Feature: Borrower Signup
  Background:
   Given John able to load the page
```

When I run the test then it does not execute the step

DevTools listening on ws://127.0.0.1:58006/devtools/browser/6fca610b-9d5d-448d-aba1-b8460f7fa676
[protractor] 0 scenarios
[protractor] 0 steps
[protractor] 0m00.000s

But if I change the feature file like this then its working

```gherkin
Feature: Borrower Signup
  Background:

  Scenario:  John can signup as a new borrower
    Given John able to load the page
```

**Comment by jan-molak** [comment]
Hi @malindapw, it would be easier for me to suggest a solution if I had a bit more context.
Could you please tell me a bit more about _how_ you execute the scenario? By name? By tag? From the command line? From you IDE?

Thanks!
Jan

**Comment by malindapw** [comment]
Hi @jan-molak , I execute tests from command line. It does not matter how I execute its same results it's not giving any errors but not execute the given statement when it's under the Background: 
e.g. 

$npm test

**Comment by jan-molak** [comment]
Hey @malindapw! Serenity/JS 2.0 is live and ships with a completely re-written [Cucumber.js adapter](https://serenity-js.org/modules/cucumber/), which should address this issue.

Please check out the [template project](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) and let me know what you think!

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
