### ISSUE TITLE
Cleaning browser storage

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#291]
Hi everyone,

How would you purge the storage (localStorage, sessionStorage) using serenity?

I tried several task variations but always struggle with browser.executeScript('window.localStorage.clear();') not being an Activity basically. What would be your advise?

In general I feel like usecases such as cleaning cookeis or storage are important parts of a scenario, and as thus, if we find a solution for that, it would be worth getting it's own documentation page :).

**Comment by paolocarrasco** [comment]
What worked for me was this:
```typescript
export class Authenticate implements Task {
  private static cleanTheBrowser() {
    return browser.driver.manage().deleteAllCookies();
  }

  @step('{0} authenticates himself in the platform')
  performAs(actor: PerformsTasks): PromiseLike<void> {
    const credentials = this.searchCredentialsFor(this.name);

    return new Promise<void>((resolve) => {
      Authenticate.cleanTheBrowser()
        .then(resolve);
      })
      .then(() => actor.attemptsTo(
        // Other commands to interact with the login form
      ));
  }

  // Other commands to interact with the login form
}
```
The key there was to treat the deletion of cookies as a promise. I don't have errors from web driver so far.

**Comment by jan-molak** [comment]
Hey @san-ouadghiri - you're on the right track! Check out the new [TodoMVC demo project](https://github.com/serenity-js/todomvc-demo/blob/master/src/todomvc/ClearLocalStorage.ts):

```typescript
import { Task } from '@serenity-js/core';
import { ExecuteScript } from '@serenity-js/protractor';

export const ClearLocalStorage = () =>
    Task.where(`#actor clears local storage`,
        ExecuteScript.sync('window.localStorage.clear()'),
    );
```

To delete cookies use the [`DeleteCookies`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/DeleteCookies.ts~DeleteCookies.html) interaction.

Hope this helps!
Jan
