### ISSUE TITLE
click on element present at bottom of page works fine on chrome not on IE

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#292]
Hi Jan,

Have got into situation where an element os present at bottom of the page and serenity scrolls and click on it as expected.
However, similar scenario doesn't work properly on IE browser, it doesnt click and exits with error other element would recieve the click at point()

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax! Are you still experiencing this issue? If so, could you please create a minimal reproducible example using one of the [template projects](https://github.com/serenity-js)? Thanks!

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax - I haven't heard from you in a while so I'm going to close this ticket. Please feel free to re-open it if you're still experiencing the issue and can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Thanks!
