### ISSUE TITLE
Provision a screencapture on Javascript

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#293]
Hi Jan-molak,

Now, Its really long time since i started using Serenity and its really awesome. Thanks to You!! :)

Have few things up in my wishlist that i would request you to implement .

when run,
Execute.script('argument[0].click();').on(Login.username);

Can we capture the screenshot for these steps too..?

Thank you,
Abhineet Sharma

**Comment by jan-molak** [comment]
Thanks for your kind words, @AbhineetSharmax, they mean a lot :-)

I'll look into this when I start working on the new `Photographer` class for Serenity/JS 2.0.

Thanks!

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax - Serenity/JS v2 has been released yesterday and offers a new implementation of [`ExecuteScript`](https://github.com/serenity-js/serenity-js/blob/ff4f51b54bd22159c56f9255ee0d79a7e089b535/packages/protractor/src/screenplay/interactions/execute-script/ExecuteScript.ts) that should trigger a screenshot shout the interaction fail.
