### ISSUE TITLE
Reporting summary file contains pending twice

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#294]
Hi @jan-molak,

Greetings!!

In Targets > site > serenity > in summary.txt have seen two entries for pending.

Summary report generated 23-01-2019 16:22195 test scenarios

Passed: 114
Pending 0
Failed: 4
Failed with errors: 77
Compromised: 0
Pending: 0
Ignored: 0
Skipped: 0

Just an observation. :)

**Comment by AbhineetSharmax** [comment]
Hi @jan-molak , Greetings!!

Firstly, Thank you for 2.0. Its has brought us many things to explore and making things possible with your solutions for our asked questions. 😃

I am commenting here again, because even in 2.0 when i navigate to target> site> serenity> summary.txt still contains, " Pending " twice.

Thanks,
Abhineet Sharma

**Comment by jan-molak** [comment]
Cool, thanks for re-testing. I'll add it to [the backlog](https://github.com/orgs/serenity-js/projects/1).

**Comment by jan-molak** [comment]
This issue seems to be specific to Serenity BDD CLI - @AbhineetSharmax would you mind reporting it at https://github.com/serenity-bdd/serenity-cli/issues

Thanks!
Jan

**Comment by AbhineetSharmax** [comment]
@jan-molak Thank you, i will raise it to serenity-cli.
