### ISSUE TITLE
broken links in the https://serenity-js.org

### ISSUE THREAD

**Issue by scaddenp** [serenity-js/serenity-js#306]
There are broken links in the cucumber prequisites documentation  eg
https://serenity-js.org/cucumber/prerequisites.md and https://serenity-js.org/cucumber/installation.md
 Pretty minor since tutorial covers them.

**Comment by jan-molak** [comment]
Thanks for spotting the issues, @scaddenp! I've recently published a new website for Serenity/JS 2.0, so I guess we could close this ticket. Please feel free to open another ticket should you spot any issues with 2.0.
