### ISSUE TITLE
should the webdriver monkey-patches be applied to defineStep too?

### ISSUE THREAD

**Issue by ntdaley** [serenity-js/serenity-js#308]
I notice that webdriver_synchroniser.ts applies its monkey-patching to `Given`, `When`, and `Then`.
But not to [`defineStep`](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#definesteppattern-options-fn).

Is there a reason for this?

Since `Given`, `When`, `Then` are all aliases of `defineStep`... I would think people might use `defineStep` not expecting it to behave differently.

**Comment by jan-molak** [comment]
Well spotted! I'll keep this in mind for when I start implementing the new Cucumber/Protractor adapter and synchroniser for [Serenity/JS 2.0](https://github.com/jan-molak/serenity-js/tree/2.0)

**Comment by jan-molak** [comment]
Hi @ntdaley! Serenity/JS v2 has been released yesterday with a completely re-implemented [Cucumber adapter](https://github.com/serenity-js/serenity-js/tree/master/packages/cucumber) that doesn't have the issue you observed in v1 as it no longer uses monkey patching.

Thanks for helping me make Serenity/JS better!
