### ISSUE TITLE
unable to identify the elements from the drop down list as they are designed in reactJS .

### ISSUE THREAD

**Issue by praveen0314** [serenity-js/serenity-js#315]
Hi Jan,

I am failing to identify the elements from the drop down list. As the list is dynamic and designed in reactJS, dev team is not used the regular Select class functionality hence, we are unable to see the list details in backend. It is just a 'div'. I can read only the text field.

Even i have tried using 'Arrow down key entry'  but for that as well i need to enter some text which the application is not allow me to do so. Hence failing. 

Can you suggest any workaround on how to identify dropdown list element which are hidden using screenplay serenity BDD with JUNIT

**Comment by jan-molak** [comment]
Hey @praveen0314 - It's difficult to advise you without seeing the code I'm afraid. Would you be able to come up with an example repo demonstrating the list? This way it will be easier for either myself or someone from the Serenity/JS community to propose some ideas.

**Comment by jan-molak** [comment]
Hi @praveen0314, I'll close this ticket since I haven't heard from you in a while. Please feel free to open a new ticket should you come across any issues with Serenity/JS in the future.
