### ISSUE TITLE
Automating using Firefox getting Connection is not secured

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#319]
Hi Jan,

Firstly thank you for giving us this platform for discussing things and for the quick replies with perfect solutions. Not sure this question belongs to this platform! however you have answers for many questions.. need you help with situations where we see messages like "your connection is not secure" when hitting https, so Everytime i need to add exception or add certificate to firefox browser. 

I know that there is Firefoxprofile available in selenium, do we have anything similar to it, where i just need to pass a profile name and it will initiate particular profile? I really need to automate this situation, Please help Thank you!

**Comment by marktigno** [comment]
Have you tried to add this on your protractor.conf.js file:

    capabilities: {
        browserName: 'firefox',
        acceptInsecureCerts: true, // <- this will accept insecure websites without the prompt.

        'moz:firefoxOptions': {
            'args': [
                '--safe-mode',
                '--private',
            ]
        },
    }

**Comment by AbhineetSharmax** [comment]
@marktigno , Thank you for a quick suggestion. really appreciate. :) 

I have set acceptInsecureCerts  equals true yet, no luck. Recently have created a profile with firefox browser.

browserName: 'firefox',
marionette: true,
"moz:firefoxOptions": {
"binary": "path",
"args": ["-profile", "pathtoprofiledirectory"]}
}

now, able to open my created particular profile with certificate added to it.

Now when i am running it.

Browser gets open, with my created profile.
however, it doesnt proceed further with any automation steps.

says Driver info: driver.version: unknown

with direct connect, it says connection refused.

@jan-molak, @marktigno .. Any help with it. Thanks.

Best Regards,
Abhineet Sharma

**Comment by marktigno** [comment]
I suggest to you to update to the compatible version of the gecko driver for the version of your Firefox. :)

**Comment by AbhineetSharmax** [comment]
@marktigno, Yup have tried webdriver-manager update .. and now have seen this is an issue with firefox 0.24 driver and the fixes will be available on 0.25 yet to be released. There is also a workaround but i am still wondering how to apply that. Thanks for the suggestion

**Comment by jan-molak** [comment]
Hey @AbhineetSharmax  - did @marktigno's suggestion help you to resolve the issue, or is there any further guidance you'd like?

Thanks,
Jan

**Comment by AbhineetSharmax** [comment]
Yes, Thank for the help @jan-molak @marktigno 😃
