### ISSUE TITLE
No distinction of browser with 'mobileEmulation' in report

### ISSUE THREAD

**Issue by sylvainleduby** [serenity-js/serenity-js#323]
Hi, 

When using `mutliCapabilities` of 2 browsers with same `browserName`, one with `mobileEmulation` mode and one without it, there is only 1 entry in report's Browsers list (Chrome for example). It would be great if the report shows each capability as distinct browser.

```
  'multiCapabilities': [{
    'browserName': 'chrome'
  },{
    'browserName': 'chrome',
    'mobileEmulation': {
      'deviceName': 'iPhone 6'
    }
  }],
```

**Comment by jan-molak** [comment]
That's a good idea, thanks @sylvainleduby! Let's look into this once Serenity/JS version 2 is out.

**Comment by jan-molak** [comment]
Hey @sylvainleduby - please check out Serenity/JS version 2.1.2 and let me know what you think!

![image](https://user-images.githubusercontent.com/1089173/74092760-66f91e80-4ac0-11ea-9934-a13281edced1.png)

---
_If Serenity/JS makes your life easier you can [buy me a coffee](https://github.com/sponsors/jan-molak) on Github_ :octocat:
