### ISSUE TITLE
Support for Cypress

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#326]
Hi @jan-molak ,
Working on serenity-js, gives us power to customise our test scenarios and make it flexible and readable. So far best Framework. :)

Is it a better idea to use serenityJS- protractor in some other framework or
shall i integrate it with some other framework?

There is a framework available for us to work, where,
browser selection option on UI is available.
screenshots comes while run is going on and can see results.

Is there any way where we can see in between run result of any particular scenario in serenity js, if ran as a test suite(having more than 300 ) together.

Regards,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax and thanks for your kind words :-) I'm very happy to hear that Serenity/JS is helping you out!

It's difficult for me to advise without seeing the other framework you're referring to. If you could point me to its documentation or demos then I could try to suggest something.

Best,
Jan

**Comment by asnov** [comment]
Hi @jan-molak 
Do you have any plans to integrate with cypress so we could use the best from both worlds?

**Comment by jan-molak** [comment]
@asnov - I think that the way Serenity/JS v2 is designed should make it possible to create an adapter for Cypress. I'm not sure how much time I will have to investigate that, but am open to ideas.

**Comment by jan-molak** [comment]
I've had quite a few people ask about Cypress recently, so if anyone would like to work with me on a PR to support it I'd be happy to help out.

**Comment by jan-molak** [comment]
Let's move this conversation to #493

**Comment by jan-molak** [comment]
Conversation moved to #846
