### ISSUE TITLE
Support for ag-grid

### ISSUE THREAD

**Issue by puneethsaladi** [serenity-js/serenity-js#328]
Hi @jan-molak,

Serenity-js presently doesn't seem to support actions on ag-grid. Is there a plan to add it in future releases?

**Comment by jan-molak** [comment]
Interesting! Is there anything specific about the actions performed on the ag-grid? Would you be able to produce a mini-project on github demonstrating the issue?

**Comment by jan-molak** [comment]
Hi @puneethsaladi, I haven't heard back from you in a while, so am closing the ticket.
Please feel free to open a new one should you wish to discuss your idea further.
