### ISSUE TITLE
Cannot read property 'set' of undefined with serenity and cucumber

### ISSUE THREAD

**Issue by maddymathavan** [serenity-js/serenity-js#331]
Hi I am using protractor with cucumber and serneity when i am running e2e i m getting below error.
webpack: Compiled with warnings.
[19:00:02] E/downloader - undefined
[19:00:02] I/update - chromedriver: file exists C:\Users\kmathav\OCP_UI\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.46.zip
[19:00:02] I/update - chromedriver: unzipping chromedriver_2.46.zip
[19:00:02] I/update - chromedriver: chromedriver_2.46.exe up to date
[19:00:02] I/launcher - Running 1 instances of WebDriver
[19:00:02] I/direct - Using ChromeDriver directly...
[19:00:02] E/downloader - undefined

DevTools listening on ws://127.0.0.1:55085/devtools/browser/1b0ad00b-6f04-4590-88b3-3a58fe520ba6
start
Cannot read property 'set' of undefined
[19:00:36] I/launcher - 0 instance(s) of WebDriver still running
[19:00:36] I/launcher - chrome #1 failed 1 test(s)
[19:00:36] I/launcher - overall: 1 failed spec(s)
[19:00:36] E/launcher - Process exited with error code 1

--------------------------------------

Package.json --

{
  "name": "oda_odic",
  "version": "0.9.1-SNAPSHOT",
  "author": "Someone",
  "description": "ODA ODIC angular2 application",
  "angular-cli": {},
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://stash.transunion.com/scm/pa/oda.git"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "npm run clean && npm rebuild node-sass --force && ng build",
    "clean": "npm run clean:dist && npm run clean:coverage",
    "clean:dist": "rimraf dist/",
    "clean:coverage": "rimraf coverage/",
    "build:prod": "npm run clean && ng build --prod",
    "test": "ng test --browsers PhantomJS --log-level debug --code-coverage true --single-run true --progress true --watch false",
    "test:watch": "ng test --browsers Chrome --log-level debug --code-coverage true --single-run true --progress true",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "pretest": "serenity update",
    "report":  "serenity run"
  },
  "keywords": [],
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngrx/core": "^1.0.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.0.0",
    "@ngrx/store-devtools": "^3.1.0",
    "@ngui/overlay": "^0.8.0",
    "ag-grid": "^9.0.2",
    "ag-grid-angular": "^9.0.2",
    "angular2-moment": "^1.0.0-beta.4",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "jquery": "^3.1.1",
    "moment": "^2.15.2",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-cookies": "^1.0.2",
    "reselect": "^2.5.4",
    "rxjs": "^5.3.0",
    "@uicoetoolbox/component-library": "~0.8.1",
    "@uicoetoolbox/core": "~0.8.1",
    "zone.js": "^0.8.5",
    "webdriver-manager": "^12.1.5",
    "protractor-cucumber-framework": "^4.1.1"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^4.0.2",
    "@types/core-js": "^0.9.43",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "@types/bluebird": "3.5.1",
    "angular-in-memory-web-api": "^0.2.4",
    "codelyzer": "~2.0.0-beta.4",
    "cxsd": "~0.1.0",
    "jasmine-core": "~2.5.2",
    "serenity-cli": "^0.11.1",
    "serenity-js": "^1.10.13",
    "chai": "^3.0.0",
    "chai-as-promised": "^7.1.1",
    "chai-smoothie": "^0.3.2",
    "cucumber": "^1.3.3",
    "ts-node": "^7.0.1",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-spec-reporter": "0.0.30",
    "node-sass": "^4.5.0",
    "phantomjs-prebuilt": "^2.1.14",
    "protractor": "~5.1.0",
    "tslint": "~4.4.2",
    "typescript": "2.3.4"
  }
}

----------

Protractor.config.js

// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

/*global jasmine */
// const { SpecReporter } = require('jasmine-spec-reporter');
const crew = require('serenity-js/lib/stage_crew'),
    glob         = require('glob'),
    protractor   = require.resolve('protractor'),
    node_modules = protractor.substring(0, protractor.lastIndexOf('node_modules') + 'node_modules'.length),
    seleniumJar  = glob.sync(`${node_modules}/protractor/**/selenium-server-standalone-*.jar`).pop();

exports.config = {
  seleniumServerJar: seleniumJar,
  allScriptsTimeout: 11000,
  // specs: [
  //   './e2e/**/*.e2e-spec.ts'
  // ],
  specs: [
    'e2e/features/**/*.feature'  
  ],
  serenity: {
    dialect: 'cucumber',
    crew:    [
      crew.serenityBDDReporter(),
      crew.photographer()
  ]
  },
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['--disable-web-security', '--user-data-dir=~/.e2e-chrome-profile']
    }
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  // seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  framework: 'custom',
  frameworkPath: require.resolve('serenity-js'),
  // frameworkPath: require.resolve('protractor-cucumber-framework'),
  cucumberOpts: {
    require: 'e2e/features/step_definitions/newInvestigation_steps.ts',
    tags: false,
    format: 'pretty',
    compiler: 'ts:ts-node/register',
    profile: false,
    'no-source': true
  },
  // beforeLaunch: function() {
  //   require('ts-node').register({
  //     project: 'e2e'
  //   });
  // },
  onPrepare() {
    browser.ignoreSynchronization = true;
  }
};

**Comment by maddymathavan** [comment]
Waiting for answers pls...

**Comment by jan-molak** [comment]
Apologies for not getting back to you sooner, @maddymathavan. Would you mind giving Serenity/JS 2.0 a try and checking if the issue you observed is still present, and if it is - raising a ticket? Serenity/JS ships with a completely re-written Cucumber and Protractor adapter.
