### ISSUE TITLE
unable to skip tests using mocha: ending up with UnhandledPromiseRejectionWarning, TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by mmetan** [serenity-js/serenity-js#333]
Hi @jan-molak 
first of all thanks for this great tool! 

I've a case where I want to skip certain or rest of the tests, if some previous steps failed.
I'm using mocha and chai-as-promised.

I'm holding a boolean flag for this case and if certain tests are failing, i am setting this flag to false to determine if the new test needs to be skipped hence executing this.skip(). However,  skipping the test is ending up with below error:  
```
(node:11796) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at C:\.......\node_modules\@serenity-js\core\src\reporting\serenity_bdd_reporter.ts:152:95
(node:11796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
(node:11796) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[18:01:50] E/launcher - Error: TypeError: Cannot read property 'error' of undefined
    at C:\.......\node_modules\@serenity-js\core\src\reporting\serenity_bdd_reporter.ts:152:95
[18:01:50] E/launcher - Process exited with error code 100
```

And here is a sample code for my mocha test:
I even tried surrounding it with try catch even to suppress the warning but seems like its not working. 

```javascript
            it("test 1 will pass", async function(){
                expect(1).to.equal(1);
            });
            it("test 2 will FAIL", async function(){
                flag=false;
                expect(1,"this test is failing. setting flag to false").to.equal(5);
            });
            it("test 3 will pass", async function(){
                expect(1).to.equal(1);
            });
            it("test 4 should be skipped", async function(){
                    if(flag==true){
                        //continue testing stuff
                    }
                    else{
                        console.log("this is being skipped.");
                        try {
                            this.test.skip();
                        } catch (error) {
                            console.log("trying to handle the error here but failing...")                            
                        }
                    }
            });
```
Although this is a sample code, it needs to be stressed that my original tests require async functions since rest of the methods using await keywords for any kind of element interaction. This is due to testing an hybrid application(some pages are php some are angular).

Additional note: I wanted to try a workaround to compromise the tests instead of skipping them but I wasn't able to find any documentation about it.  Also not sure if this issue is same as #246 but seems like that one is happening in before methods. I am highly suspecting that the promise is not being handled in skip for serenity in this case. 

Any helps are highly appreciated. 
Thank you again.

**Comment by jan-molak** [comment]
Hi @mmetan and apologies for taking so long to respond.

It seems like you might have observed this either with Serenity/JS v1 or with an early alpha of v2.
I've just checked the scenario you describe with Serenity/JS `2.24.0` and Mocha `8.3.0`, and calling `this.test.skip()` correctly skips the test, so I'm going to close this ticket.

Please feel free to re-open it if you notice this issue again.
