### ISSUE TITLE
How can I add new tag on SerenityJS HTML reporter?

### ISSUE THREAD

**Issue by gurcuesra** [serenity-js/serenity-js#337]
I am using TypeScript and Serenity JS with Protractor. Also, I am using log4js for logging. But, SerenityJS HTML reporter tags are not enough for my companies requirements. I want to add extra tag as "Defects" and I want to add failures description on it. I research lot's of thing. But, I couldn't find any documentation or explanation about the customize the Serenity JS HTML reporter. 

HTML report tag should be like this:

Defects
#DefectNumber1  % 10     -------------1
#DefectNumber2  % 10	 -------------1
#NewDefect      % 5      -------------1

I found the how to get the failure of the Scenario or Step. But, I don't know how should I add on the reporter.

This is the my Hook.ts file:

``
import { configure, getLogger } from 'log4js';
configure('./log4js.json');
const logger = getLogger();

import { EventListener } from 'cucumber';
var event = EventListener;

module.exports = function Hook(){
   this.registerHandler('ScenarioResult', function(event){
        var scenario = event.getPayloadItem('scenario');
        logger.warn(`Scenario result is: ${scenario.getStatus().toUpperCase()}`);

        var durationMS = Math.round(scenario.getDuration()/10000000);
        var duration = durationMS/100;
        logger.warn(`Scenario duration is: ${duration} sec`);

        if(scenario.getFailureException() == null) {
            logger.error(`SCENARIO FAILURE IS: NO FAILURE`);    
        } else {
            logger.error(`SCENARIO FAILURE IS: ${scenario.getFailureException()}`);
        }
    })
}
``

This is the conf.js file:

``
const crew = require('serenity-js/lib/stage_crew');

exports.config = {
    
    directConnect: true,
    // seleniumAddress: 'http://localhost:4444/wd/hub',

    framework: 'custom',
    frameworkPath: require.resolve('serenity-js'),

    serenity: {
        crew:    [
            crew.serenityBDDReporter(),
            crew.consoleReporter(),
            crew.photographer()
        ],

        requirementsDirectory: `${process.cwd()}/./Project/Features/features`,
        outputDirectory: `${process.cwd()}/target/site/serenity/`,

        dialect: 'cucumber',  // or 'mocha'
    },

    specs: [ './Project/Features/*.feature' ],
    onPrepare: function() {
        browser.waitForAngularEnabled(false);
        browser.manage().window().maximize();
        browser.manage().timeouts().implicitlyWait(100000);
    },

    cucumberOpts: {
        require:    [ './Project/StepDefinitions/*.ts', './Project/Utilities/Hook.ts' ], // loads step definitions
        format:     'pretty',                      // enable console output
        compiler:   'ts:ts-node/register',         // interpret step definitions as TypeScript
        //tags: ['@TC7579',]                         // npm run tag @smoketest        // which ones you're not, by negating them with ~   => ~@performance
    }
}
``

How can I customize or add new tag on HTML reporter?

**Comment by abhinaba1080** [comment]
just to be clear, you want yo tag the scenario with existing defect id or create a new defect if something got failed?

**Comment by gurcuesra** [comment]
![Screenshot (338)_LI](https://user-images.githubusercontent.com/42274690/70158742-97f64680-166c-11ea-86fd-835c62166ee8.jpg)

Report should be like screenshot.

**Comment by jan-molak** [comment]
Hey @gurcuesra - we've [just been talking about a similar use case](https://gitter.im/serenity-js/Lobby?at=5e73f377671a621fe09efb65) on the [Serenity/JS Gitter channel](https://gitter.im/serenity-js/Lobby)

With Serenity/JS 2.0 you can tag your Cucumber feature files with any arbitrary tags you wish and you can also link from your test reports to [Jira and other issue trackers ](https://serenity-js.org/handbook/integration/jira-and-other-issue-trackers.html).

All you need to do is to decide on tags that make sense for your product and your test suite, i.e. `@defect`, `@sev1`, `@sev2`, etc. and use them to tag your `Features` and `Scenarios`:

```gherkin
Feature: A feature with two many defects

  @defect
  @sev1
  @issue:JIRA-123
  Scenario: A scenario where the customer encountered a problem

    Given ...
     When ...
     Then ...
```

Does this help?

Jan

**Comment by jan-molak** [comment]
Hey @gurcuesra, I haven't heard from you for a while, so will assume that my last suggestion has answered your question and am closing this ticket. Please feel free to re-open it if you have further questions.
