### ISSUE TITLE
Unable to run the tests on multiple browser instances in parallel

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-js/serenity-js#338]
I am trying to execute 2 BDD scenarios (single feature file) in parallel just on chrome browser and the configuration looks like below. But the tests are running in the sequentially.

In case the the scenarios are in more than one feature file the parallel run is working as expected. Is this a limitation of Protractor tool?

```
capabilities: {
        'browserName': 'chrome',
        'shardTestFiles': true,
        'maxInstances': 2
    },
```

**Comment by abhinaba1080** [comment]
@rakeshnambiar 
maxInstances do not run scenarios parallely, it run feature files in parallel.

**Comment by jan-molak** [comment]
Hi @rakeshnambiar, it feels like @abhinaba1080's suggestion has helped you to resolve the issue, so I'll close the ticket. Please feel free to open a new one should you require further assistance.

**Comment by rakeshnambiar** [comment]
@jan-molak - the parallel execution is working at the features level and not at the scenario level. Wehereas in Serenity-BDD Java setup this can be easily achievable. I hope at some point the protractor may accomodate this feature too.

**Comment by jan-molak** [comment]
@rakeshnambiar - it would be lovely if they did. Please feel free to raise a ticket with Protractor and link it from here so people could upvote it.
