### ISSUE TITLE
Mobile Emulation with serenityjs

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#361]
Hi Jan-Molak, @jan-molak Greetings!

Firstly, thank you for giving quick responses for each of our queries and giving us the opportunity to work on Serenity JS. Its is really easy to use.

The question is on mobile emulation with serenity,
while working with mobile browser emulation, found screen flickers alot on any of the Action performed on UI ex. clicks, input text. Request you to please help me with it. Thanks :)

Regards,
Abhineet Sharma

**Comment by AbhineetSharmax** [comment]
@jan-molak, is it because of the reporter trying to capture the image for each action? Thank you 😊

**Comment by jan-molak** [comment]
Hey @AbhineetSharmax - thanks for your kind words, I'm glad that you find Serenity/JS useful :-)

RE: flickering - It's difficult for me to tell without seeing the code. Would you be able to create a minimal test case (maybe by forking the [template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template)) that demonstrates the issue?

**Comment by AbhineetSharmax** [comment]
ya, below is my configuration for chrome.
capabilities:
{
browserName: 'chrome',
'chromeOptions': { 'mobileEmulation':{'deviceName': 'iPhone 5/SE'}}
}

}

after every action(click,input text) it zooms in the page and when i checked the reports the resolution of the image for mobile seems bigger than the original(because on emulation the webpage gets emulated and remain pages left is white).

Thanks,
Abhineet Sharma

**Comment by jan-molak** [comment]
Interesting, I don't see the zooming in / out behaviour you have observed on Protractor `5.4.2`, Chrome `77.0.3865.120` with the `Photographer` configured to `TakePhotosOfInteractions` 😕 

What version of Protractor/Chrome are you on? Also, do you see this behaviour when you run the template project with `mobileEmulation` switched on?

**Comment by jan-molak** [comment]
Now that Serenity/JS 2.0 is out, let's look at any mobile emulation related issues under #323
