### ISSUE TITLE
Is there a way to use the new serenity bdd report in serenity JS?

### ISSUE THREAD

**Issue by ralves20** [serenity-js/serenity-js#376]
Hello,

I'm using serenity JS 1.10.13 to run my tests, and when I generate the html report, the report generated is the oldest serenity report, which is this one:
![image](https://user-images.githubusercontent.com/40844089/70179224-6b6a1b00-16bc-11ea-836d-6f4f13687c14.png)

However, I would like to use the new serenity bdd html reporter, which is this one:
![image](https://user-images.githubusercontent.com/40844089/70179189-5ee5c280-16bc-11ea-9221-4a6a0c85a23c.png)

Is there a way that I can use the new html reporter on serenity 1.10.13?

**Comment by jan-molak** [comment]
Hi @ralves20 - the new Serenity BDD reporter expects a different `JSON` structure than the old one used to. The best way to use the latest reporter is to switch from Serenity/JS 1.x to 2.0.

If that's something you'd like to do I'd be happy to guide you through the process?

Jan

**Comment by ralves20** [comment]
Hi @jan-molak thank you very much!
But at the moment, the project that I'm working, the customer does not want to change, so I have to keep Serenity 1.x.

But thank you very much for your quick feedback.

btw, I'm using serenity js in other projects and it is great!

**Comment by heiho1** [comment]
Hi @jan-molak ,

I am currently integrating Serenity into a BDD testing project and I would like to know the steps to upgrade from 1.x Serenity to 2.x.  Do you feel it is stable enough to use?

**Comment by jan-molak** [comment]
@heiho1 - a number of teams have been using the new version successfully over the past 6 months and I think I've managed to address any major issues already. The reason why I'm still keeping Serenity/JS in "alpha" is that I'd like to release it with comprehensive documentation. It feels like documenting the framework takes more time than it took to write it, though! 😄 

@nbarrett has been working on a 1.x to 2.x [migration guide](https://github.com/jan-molak/serenity-js/pull/377/files?short_path=2b9023d#diff-2b9023d15428d67137ee6656533b59c6), which will be incorporated into the new Serenity/JS Handbook.
If you'd like to go through the migration guide and give us your feedback under #377 that would be greatly appreciated!

**Comment by jan-molak** [comment]
Closing as Serenity/JS has been out of alpha since February 2020 and the latest Serenity BDD reporting CLI jar is already available.
