### ISSUE TITLE
TypeError: Cannot read property '0' of undefined - what is wrong?

### ISSUE THREAD

**Issue by ralves20** [serenity-js/serenity-js#402]
Hi

I'm trying to generate reports in my local machine and I'm getting this error:
TypeError: Cannot read property '0' of undefined
However, when I generate the reports throught docker environment it is possible.

Does anyone know what can I do to be able to generate those reports on my local machine?

This is my package.json

`  "devDependencies": {
    "@serenity-js/core": "^1.6.0",
    "@serenity-js/cucumber": "^1.0.0",
    "@serenity-js/rest": "^1.1.1",
    "@types/chai": "^4.1.7",
    "@types/chai-arrays": "^1.0.2",
    "@types/chai-as-promised": "^7.1.0",
    "@types/chai-fs": "2.0.0",
    "@types/cucumber": "1.3.3",
    "@types/js-yaml": "^3.11.2",
    "@types/neat-csv": "^4.0.0",
    "@types/node": "7.0.31",
    "axios": "^0.18.0",
    "axios-debug-log": "^0.4.0",
    "chai": "3.5.0",
    "chai-arrays": "^2.0.0",
    "chai-as-promised": "^7.1.1",
    "chai-fs": "^2.0.0",
    "chai-smoothie": "^0.3.2",
    "chance": "1.1.3",
    "cross-env": "^5.2.0",
    "cucumber": "1.3.3",
    "dotenv": "8.1.0",
    "etherscan-api": "^10.0.0",
    "failsafe": "^1.0.0",
    "faker": "^4.1.0",
    "faker-man": "^4.2.1",
    "fs": "0.0.1-security",
    "glob": "7.1.2",
    "gulp": "4.0.2",
    "js-base64": "^2.4.9",
    "js-yaml": "^3.12.0",
    "leite": "0.2.0",
    "moment": "^2.24.0",
    "neat-csv": "^4.0.0",
    "node-pop3": "^0.1.0",
    "npm-failsafe": "^0.4.1",
    "npm-run-all": "^4.1.5",
    "protractor": "5.4.2",
    "protractor-cucumber-framework": "6.2.0",
    "serenity-cli": "^0.11.1",
    "serenity-js": "^1.10.13",
    "sinon": "7.5.0",
    "sonarqube-scanner": "^2.5.0",
    "ts-node": "3.0.6",
    "tslint": "^5.20.1",
    "tslint-sonarts": "^1.9.0",
    "typescript": "^2.4.0",
    "webdriver-manager": "12.1.7"
  }
}
`

node version: v12.11.1
npm version: 6.11.3
yarn version: 1.19.1
Java JDK 11

error on console:

`(py27-16) rodrigo@rodrigo:~/webapp-ecommerce-frontend-testes$ npm run report

> webapp-testing@1.0.0 report ~/webapp-ecommerce-frontend-testes
> serenity run

TypeError: Cannot read property '0' of undefined
    at ../webapp-ecommerce-frontend-testes/node_modules/java-home/lib/java-home.js:92:27
info: Using Java at: [ '/usr/lib/jvm/java-11-oracle/bin/java' ]
error: [ 'WARNING: An illegal reflective access operation has occurred' ]
serenity run

Aggregates the JSON reports generated by Serenity BDD and produces one in HTML

Opções:
  --version          Exibe a versão                                   [booleano]
  --log              log level
                           [opções: "info", "verbose", "debug"] [padrão: "info"]
  --cacheDir         An absolute or relative path to where the Serenity BDD CLI
                     jar file should be stored                          [padrão:
  "../webapp-ecommerce-frontend-testes/node_m
                                                    odules/serenity-cli/.cache"]
  --destination      Directory to contain the generated Serenity BDD report
                                                                        [padrão:
  "../webapp-ecommerce-frontend-testes/target
                                                                /site/serenity"]
  --features         Source directory containing the Cucumber.js feature files
                                                                        [padrão:
  "../webapp-ecommerce-frontend-testes/features"]
  --artifact         Serenity BDD CLI artifact to use; You're best off with the
                     default option unless you want to experiment.
                        [padrão: "net.serenity-bdd:serenity-cli:jar:all:1.11.0"]
  --source           Source directory containing the Serenity BDD JSON output
                     files                                              [padrão:
  "/home/rodrigo/Projetos/FastShop/HTTPS/webapp-ecommerce-frontend-testes/target
                                                                /site/serenity"]
  --issueTrackerUrl  Base URL for issue trackers other than JIRA
  --jiraProject      JIRA project identifier
  --jiraUrl          Base URL of your JIRA server
  --project          Project name to appear in the Serenity reports (defaults to
                     the project directory name)
  -h, --help         Exibe ajuda                                      [booleano]

Error: WARNING: An illegal reflective access operation has occurred
    at /home/rodrigo/Projetos/FastShop/HTTPS/webapp-ecommerce-frontend-testes/node_modules/serenity-cli/lib/actions/logging.js:9:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp-testing@1.0.0 report: `serenity run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webapp-testing@1.0.0 report script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2020-01-15T17_25_46_391Z-debug.log`

**Comment by abhinaba1080** [comment]
Can you try degrading your JDK version to 8?

**Comment by jan-molak** [comment]
Hey @ralves20 - we haven't heard from you regarding this ticket in a while so I'm going to close it. Please feel free to re-open it if you believe the issue still requires our attention.
