### ISSUE TITLE
Serenity-BDD Report generation with requirements

### ISSUE THREAD

**Issue by ttretau** [serenity-js/serenity-js#41]
During report generation I get a warning that the requirements coverage reports could not be generated:

`warn: net.thucydides.core.requirements.PackageRequirementsTagProvider - To generate correct requirements coverage reports you need to set the 'serenity.test.root' property to the package representing the top of your requirements hierarchy.`

I see in the reports that the requirements are not mapped to the tests..

Could this be fixed by passing the `requirements directory` to Serenity-BDD CLI? This is not done right now?
Does it makes sense to upgrade to the latest Serentiy-BDD CLI? Or is there a reason to not do that?
I tested with the latest version and got a hanging java process..

**Comment by ttretau** [comment]
Ah, I just saw that Serenity-BDD is trying to do an automatic mapping from the Feature-file to the feature-name. So if they are different it does not work.. Perhaps something for the documentation?
Perhaps I can help to document that. Is the tutorial or the book the right place?

**Comment by jan-molak** [comment]
Sure, please go ahead. Thanks!
