### ISSUE TITLE
The methods from CallAnApi should catch instead of using callbacks

### ISSUE THREAD

**Issue by AlexRex** [serenity-js/serenity-js#411]
The methods in the following class: https://github.com/jan-molak/serenity-js/blob/master/packages/rest/src/screenplay/abilities/call_an_api.ts#L74

Are using callback style for the promises, when using this style of error handling if a returned error happens it won't be properly propagated and mapped to the resolved case. In order to illustrate:

```javascript
new Promise((resolve, reject) => {
  reject('hack')
}).then(
  (ok) => {
    console.log('ok', ok);
    return ok;
  },
  (error) => {
    console.log('error', error); // error hack
    return error;
  }
)
.then(
  (ok) => {
    console.log('ok', ok); // ok hack
    return ok;
  },
  (error) => {
    console.log('error', error);
    return error;
  }
)
```

If you take a look at the code snippet you can see that if reject the promise at the first iteration of the `then` we get it properly handled but in the following iteration is not happening. 

I had an issue with a SSL certificate which Axios treats as an error and throws an exception, as this is not properly handled by the `CallAnApi` class the error is not properly handled and the test execution does not stops. 

I am open to work on a Pull Request to fix it if needed 😄

**Comment by jan-molak** [comment]
Hey @AlexRex, thanks, well spotted! The upcoming 2.0 release will change the original implementation. Would you like to review [the new version](https://github.com/jan-molak/serenity-js/blob/2.0/packages/rest/src/screenplay/abilities/CallAnApi.ts)?

**Comment by AlexRex** [comment]
Hi @jan-molak I reviewed the code of the version 2.0 and in this method: https://github.com/jan-molak/serenity-js/blob/2.0/packages/rest/src/screenplay/abilities/CallAnApi.ts#L156-L182

Looks like it will have the same issue. Unless you want to handle there all the errors and create a new promise to the clients I wouldn't use the callback style for promises, I would rather go with the `catch` approach as this will properly propagate the error.

**Comment by jan-molak** [comment]
Thanks for taking the time to look into this. Would you be willing to [propose a test](https://github.com/jan-molak/serenity-js/blob/2.0/packages/rest/spec/screenplay/abilities/CallAnApi.spec.ts) that demonstrates the issue you mention?

**Comment by AlexRex** [comment]
Hi @jan-molak I've been doing some tests with the version2 and looks like now the problem is solved! 

Sorry for taking that long to answer, busy days. :)

**Comment by jan-molak** [comment]
Amazing, thanks for letting me know!
