### ISSUE TITLE
Actors cannot be instantiated from protractor.conf.js

### ISSUE THREAD

**Issue by testifyqa** [serenity-js/serenity-js#416]
Hi Jan, so I am successfully able to instantiate Actors from a config block in my setup.ts file like so...
```
import { setDefaultTimeout } from 'cucumber';
import { Actors } from '../../spec/screenplay/Actors';
import { configure } from '@serenity-js/core';

setDefaultTimeout(10000);

configure({
    actors: new Actors()
});
```

I instead tried adding `actors: new Actors()` [with appropriate require() / import] in the serenity block in my protractor.conf.js file but it complained about not being able to find the module.

I also tried taking it out the serenity block and just putting it in the main exports.config block in protractor.conf.js but got the same error.

Error:
```[16:45:19] E/configParser - Error code: 105
[16:45:19] E/configParser - Error message: failed loading configuration file protractor.conf.js
[16:45:19] E/configParser - Error: Cannot find module './spec/screenplay/Actors'
Require stack:
- /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/protractor.conf.js
- /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/protractor/built/configParser.js
- /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/protractor/built/launcher.js
- /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/protractor/built/cli.js
- /Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/node_modules/protractor/bin/protractor
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/t.knee/Documents/DevProjects/JavascriptProjects/TestifyQA/serenity-js-framework/protractor.conf.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
npm ERR! Test failed.  See above for more details.
➜  serenity-js-framework git:(master) ✗ 
```

protractor.conf.js:
```
const
    { Photographer, TakePhotosOfFailures } = require('@serenity-js/protractor'),
    { SerenityBDDReporter } = require('@serenity-js/serenity-bdd'),
    { ConsoleReporter } = require('@serenity-js/console-reporter'),
    { ArtifactArchiver } = require('@serenity-js/core'),
    { Actors } = require('./spec/screenplay/Actors');

exports.config = { 
    baseUrl: 'https://www.zagat.com', 
    directConnect: true, 
    allScriptsTimeout: 120000, 
    capabilities: {
        browserName: 'chrome'
    },
    specs: ['./features/*.feature'], 
    framework: 'custom',
    frameworkPath: require.resolve('@serenity-js/protractor/adapter'),
    onPrepare: () => {
        require('ts-node').register({ 
            project: './tsconfig.json'
        });
    },
    serenity: {
        actors: new Actors(),
        runner: 'cucumber',
        crew: [
            Photographer.whoWill(TakePhotosOfFailures),
            new SerenityBDDReporter(),
            ConsoleReporter.forDarkTerminals(),
            ArtifactArchiver.storingArtifactsAt('./target/site/serenity')
        ]
    },
    cucumberOpts: {
        require: ['./features/**/*.ts',
                  './support/**/*.ts'], 
        compiler: 'ts:ts-node/register'
    },
};
```

**Comment by jan-molak** [comment]
Hi @testifyqa this problem lies with Protractor, I'm afraid 😞 

Protractor doesn't support TypeScript in config files. If you have a look at the [TypeScript example](https://github.com/angular/protractor/tree/37bef24331c1012bfc2cc7d3fa259a00e69bd192/exampleTypescript) in the Protractor repo, you'll notice that the way it "supports" a TS config file is by first [transpiling it to JS](https://github.com/angular/protractor/blob/37bef24331c1012bfc2cc7d3fa259a00e69bd192/exampleTypescript/package.json#L9-L10), and then running the resulting JS file instead.

While you could do that too, I find this workaround rather inelegant since you can run the tests through ts-node, but the config file you'd have to transpile separately.

Given this limitation of Protractor, there are two ways you could go about solving this problem:
- implement the `Actors` file in JavaScript rather than TypeScript - this kinda works as long as `Actors` have no dependency on other TS files
- configure the `runner` and the `crew` in the `protractor.conf.js` file, but configure the `Actors` using `engage` before the test scenarios start.

For example:

```setup.ts
import { Before } from 'cucumber';
import { engage } from '@serenity-js/core';
import { Actors } from './Actors';

Before(() => engage(new Actors());
```

Does this help?

**Comment by testifyqa** [comment]
Thanks Jan, I did notice the engage() whilst browsing example repos.

Would that still work cleanly when using multiple step definition files for a test? Would I need to declare the before(engage()) block in each step def file?

Cheers.

**Comment by jan-molak** [comment]
If you have multiple step definition files I'd move the call to engage to your setup file.

There you have two options, depending on your circumstances:
- if your `Actors` class holds any state (like configuration properties) then it's better to instantiate  it in `Before` hook:

```typescript
// features/support/setup.ts
Before(() => engage(new Actors()));
```

- if your `Actors` class is stateless, then it's enough to call engage once before the test suite starts:
```typescript
// features/support/setup.ts
engage(new Actors());
```

**Comment by testifyqa** [comment]
Thanks, currently I just had the configure block in my setup.ts file configure actors, but as everything else like runner and stage crew is handled in protractor.conf.js, I think my best bet is probably just change the configure block to `engage(new Actors());` in that same setup.ts file 👍

**Comment by jan-molak** [comment]
Yup, agreed 👍
