### ISSUE TITLE
stage cue related issue

### ISSUE THREAD

**Issue by vaibhavgatne** [serenity-js/serenity-js#422]
Step Definition: node_modules\serenity-js\src\serenity-cucumber\stage_cue.ts:6

**Comment by jan-molak** [comment]
Could you please provide a bit more context?

In particular:
- what version of Serenity/JS are you using?
- the version of Node.js
- your operating system, web browser details, and anything that could be useful to reproduce the issue
- the details of the issue you're seeing and the context in which it occurs
- steps to reproduce the issue

Thanks!

**Comment by vaibhavgatne** [comment]
On Mon, Jan 27, 2020, 11:12 PM Jan Molak <notifications@github.com> wrote:

> Could you please provide a bit more context?
>
> In particular:
>
>    - what version of Serenity/JS are you using?-->2.0.0
>    - the version of Node.js-->8.11.2
>    - your operating system, web browser details, and anything that could
>    be useful to reproduce the issue-->windows,chrome 79 version,parallel
>    execution of feature file with four instance through Jenkins .
>    - the details of the issue you're seeing and the context in which it
>    occurs-->parallel execution of run.
>    - steps to reproduce the issue
>
> -->parallel runs of feature file and if particular element is not getting
on UI then it shows loading and after that it shows this message rather
than it ,it should be fail.

**Comment by jan-molak** [comment]
RIght, I'm guessing that you're running your tests in parallel via Protractor sharding?
Would you be able to create a minimalistic repo that shows how the issue can be reproduced?

You could use https://github.com/serenity-js/serenity-js-cucumber-protractor-template as base.

Looking forward to hearing from you!

**Comment by vaibhavgatne** [comment]
Thanks for your quick reply.i will update on you soon.

**Comment by jan-molak** [comment]
Hey @vaibhavgatne - I haven't heard from you regarding this ticket for a while so I'm going to close it. Please feel free to re-open it if you need any further guidance.
