### ISSUE TITLE
Make the output directory configurable

### ISSUE THREAD

**Issue by marktigno** [serenity-js/serenity-js#45]
Hello Jan,

Is there a way to modify the report folder that can be defined using config file or a command-line argument? As of now after I execute the tests the results are placed on the default folder mentioned. I'm planning to execute a parallel test on different URLs (example website A and B) and create different types of report per URL. By the way serenity-js is a great product. Thanks! ^_^V

**Comment by marktigno** [comment]
It seems I've found it where the default location for the report is being set, is there a way this line here could be set using a config property or from a command line argument? Right now I'll try to find a way how to play with it.

![image](https://cloud.githubusercontent.com/assets/13494822/26485759/cd3f840a-422a-11e7-8e87-643de775ce75.png)

**Comment by jan-molak** [comment]
Hey @marktigno! Yes, I wanted to make that configurable as soon as someone needs it :-)
By the way, are you running the exact same test against those two different URLs? If the test has the exact same title and steps, how do you know which website has a problem should that test fail?

**Comment by nbarrett** [comment]
Hey Jan - sounds like multicapabilities is what's needed here - but if this is specified in the protractor config, is the production of json files and then serenity reports sandboxed in a way that allows the output from each capability to be viewed separately ?

**Comment by jan-molak** [comment]
Hey Nick! The identity of a scenario is determined based on the [name of the feature, the title of the scenario and its position in the feature file](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/src/serenity-cucumber/cucumber_serenity_notifier.ts#L150). 

Cucumber, which [generates the `SceneStarts` event](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/src/serenity-cucumber/cucumber_serenity_notifier.ts#L36), has no knowledge of the Protractor browser nor its capabilities, so we'd need to find a better place to obtain and include that information.

**Comment by marktigno** [comment]
Hello Jan! There will be two answers for that:
1.) Yes running the same set of tests on different URLs like UAT environment then prelive environment.
2.) Same environment but different test scenarios by executing using the following commands:
     a.) npm run protractor -- --baseUrl="http://www.someurl.com/" --suite="smoketest"
     b.) npm run protractor -- --baseUrl="http://www.someurl.com/" --cucumberOpts.tags="@regressiontest"

In that way serenity will generate results/reports based on the arguments set on these arguments. As of now it seems serenity is pre-configured to store results on the "target/site/serenity" when the protractor is invoked during execution. It will be better if that will be configurable before protractor executes the tests and that would be very awesome especially running tests in parallel execution.

Reference: https://github.com/angular/protractor/blob/master/lib/config.ts

**Comment by jan-molak** [comment]
Gotcha, I guess two things would be useful:
- to configure the output directory
- to include the information about the execution context when generating the unique hash of a given scenario (so that the url is included, for instance)

**Comment by marktigno** [comment]
Addition feature also would be added if the report has archival like capabilities like report created on a specific time and date or some flexibility like:
    target_folder = "someDir/location/" + reportDate.madeOn();

**Comment by jan-molak** [comment]
Hey @marktigno - please update to the latest version and let me know if it's all working for you.

Best,
Jan

**Comment by marktigno** [comment]
Hello @jan-molak!

I've updated to this version of Serenity and it seems the screenshot are still generated to the default directory `target/site/serenity` though I've followed what is written on your [site](http://serenity-js.org/overview/configuration.html#output-directory) on the configs but the report generated is blank.
![image](https://user-images.githubusercontent.com/13494822/31068409-78916caa-a78a-11e7-857e-b8eb64cf972c.png)

Also I've find out on the `PhotographySchedule` class, the **outputDirectory** property does not exists as show on this screenshot:
![image](https://user-images.githubusercontent.com/13494822/31068506-e14415a4-a78a-11e7-92a4-43a82f237c3f.png)

Thanks,
Mark

**Comment by marktigno** [comment]
Disregard the second screenshot on the comment above, I just rebuild the forked copy and it recognized the property now. I'll try some test to find out what's missing on my end. Thanks!

**Comment by marktigno** [comment]
Hello @jan-molak,

It is confirmed on my end that the screenshots are still generated to the `target/site/serenity` directory including the generated .json result file.

Thanks!

**Comment by jan-molak** [comment]
Hey @marktigno - I'm slightly confused, so is that the behaviour you expected, or is there a defect and we should re-open this ticket?

**Comment by marktigno** [comment]
By the way, I'm using Typescript 2.5.3 on my machine.

**Comment by Thopthes** [comment]
Got the same problem here. After some analysis the reason is the following: 
Serenity class (serenity.ts) get config is called before configure is called in serenity_framework_config.ts
So the default value is used before the configured value overrides it.

**Comment by jan-molak** [comment]
Thanks for looking into that, @Thopthes! Let me know if you'd like to raise a PR for this - I'd be happy to help out.

**Comment by webit4me** [comment]
Hi @jan-molak, @Thopthes, is there any progress on this? 
Having this config available allow us to enable the reporting on our pipelines and I'm keen to contribute too,  but unfortunately I even don't know where to begin

**Comment by tibioneh** [comment]
This only works for the files generated during the test run in a SerenityJS-WebdriverIO project if setting the `outputDirectory` property in `wdio.conf.ts`. When running the aggregate `serenity-bdd run` command, a new `target` folder is generated in the root of the project with 0 tests. Can you please fix this?
