### ISSUE TITLE
Is there a way to set context tags for multi-browser testing?

### ISSUE THREAD

**Issue by robin-weller** [serenity-js/serenity-js#455]
Hi Jan,

With the Java Serenity version, you can provide a context for each browser so that the report shows which browser the test has run on. I have found an old example on John Smart's [blog](https://johnfergusonsmart.com/running-tests-different-environments-browsers-serenity-bdd/) and it still works with the latest version.

Is this something that can easily be done with Serenity/JS?

I am able to run the tests in multiple browsers but there is no distinction in the report to show which browser the test run on.

**Comment by abhinaba1080** [comment]
@robin-weller 
Actually serenity JS report does show the browser information the nicest way possible. I was working on serenity 1.x version and able to get below information in the report:

![image](https://user-images.githubusercontent.com/23141842/73942947-f0202200-4915-11ea-9d0b-282c130ba22d.png)

Not only that, for multi-browser tests, all the browsers will be listed down here. 

Most important thing is, before each test case, it shows the icon in which browser tests are executed. 

![image](https://user-images.githubusercontent.com/23141842/73943102-2f4e7300-4916-11ea-845a-0f1ca6e29676.png)

Can you share your protractor.conf and the report you are getting. It will ravel a broader picture.

**Comment by robin-weller** [comment]
That is what I see using the Java version. I am using v2 though.

protractor.conf.js:
```
const
    { ConsoleReporter } = require('@serenity-js/console-reporter'),
    { ArtifactArchiver } = require('@serenity-js/core'),
    { SerenityBDDReporter } = require('@serenity-js/serenity-bdd'),
    { Photographer, TakePhotosOfInteractions } = require('@serenity-js/protractor');

exports.config = {
    chromeDriver: require('chromedriver/lib/chromedriver').path,
    geckoDriver: require('geckodriver/lib/geckodriver').path,
    SELENIUM_PROMISE_MANAGER: false,

    directConnect: true,

    allScriptsTimeout: 11000,

    specs: [ './features/*.feature', ],

    framework: 'custom',
    frameworkPath: require.resolve('@serenity-js/protractor/adapter'),

    onPrepare: () => {
        require('ts-node').register({
            project: './tsconfig.json'
        });
        browser.waitForAngularEnabled(false);
    },

    serenity: {
        crew: [
            ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
            Photographer.whoWill(TakePhotosOfInteractions),
            new SerenityBDDReporter(),
            ConsoleReporter.forDarkTerminals(),
        ],
        runner: 'cucumber'
    },

    cucumberOpts: {
        require: [
            'features/steps/**/*.ts',
            'features/support/setup.ts',
        ],
        'require-module': ['ts-node/register'],
    },

    multiCapabilities: [
        {
            browserName: "chrome",
            chromeOptions: {
                args: [
                    '--disable-infobars',
                    '--no-sandbox',
                    '--disable-gpu',
                    '--window-size=1024x768',
                    // '--headless',
                ],
            },
        },
        {
            browserName: "firefox",
        },
    ],
};
```

Report:
![Screenshot 2020-02-06 at 13 57 46](https://user-images.githubusercontent.com/23662388/73943540-d6b4b100-48e8-11ea-8217-365219e3650f.png)

A Java version:
![Screenshot 2020-02-06 at 14 01 20](https://user-images.githubusercontent.com/23662388/73943755-3a3ede80-48e9-11ea-8c15-41fbaea747cc.png)

**Comment by abhinaba1080** [comment]
@jan-molak Is it related to old serenity CLI jar?

**Comment by jan-molak** [comment]
Hi @robin-weller, it's great to hear from you again!

@abhinaba1080 - your instincts are right, it is partially related to the old Serenity CLI jar. The upcoming 2.1.10 release of the jar will come with serenity-bdd/serenity-core#1860, which enables both browser and OS icons to be rendered for every test scenario.

I was waiting for that jar to be published to add both the browser/os tagging as well as the icons all in one go. But, having thought about it some more, I decided to implement the tagging first and the icons whenever the jar arrives.

Enjoy Serenity/JS v 2.1.0 with OS and browser tags

![image](https://user-images.githubusercontent.com/1089173/73991928-861f7100-4945-11ea-8a4b-a54feb537426.png)

Support for icons is coming soon ;-)

---
_You can now [sponsor my work on Serenity/JS](https://github.com/sponsors/jan-molak) on Github_ :octocat:

**Comment by robin-weller** [comment]
Thanks @jan-molak - good to hear from you too!

I am seeing the OS and browser tags in the report, however, there is an issue generating the report from firefox runs. so it is only showing chrome.

I see the following error when it is generating reports from firefox runs:
`[main] WARN  n.t.c.r.json.JSONTestOutcomeReporter - This file was not a valid JSON Serenity test report: scenario-user-can-log-in-ec36ba7706.json`

I am seeing the chrome icon though!

**Comment by jan-molak** [comment]
Cool, so we're making progress :-) Would you mind posting the offending `json` file?

**Comment by robin-weller** [comment]
Of course:

```
{ 
   "name":"User can log in",
   "title":"User can log in",
   "id":"demo-journeys;user-can-log-in",
   "manual":false,
   "testSteps":[ 
      { 
         "number":1,
         "description":"Given Arya is on the <Obfuscated Website> homepage",
         "startTime":1581086694376,
         "children":[ 
            { 
               "number":2,
               "description":"Arya navigates to '<Obfuscated Website>'",
               "startTime":1581086694379,
               "children":[ 

               ],
               "reportData":[ 

               ],
               "screenshots":[ 
                  { 
                     "screenshot":"photo-firefox-arya-navigates-to-<Obfuscated Website>-cf8036b9c1.png"
                  }
               ],
               "result":"SUCCESS",
               "duration":905
            },
            { 
               "number":3,
               "description":"Arya ensures that the title of the current page does start with '<Obfuscated Website>'",
               "startTime":1581086695287,
               "children":[ 

               ],
               "reportData":[ 

               ],
               "screenshots":[ 
                  { 
                     "screenshot":"photo-firefox-arya-ensures-that-the-title-of-the-current-page-does-start-with-<Obfuscated Website>-b2144a1f3b.png"
                  }
               ],
               "result":"SUCCESS",
               "duration":5
            }
         ],
         "reportData":[ 

         ],
         "screenshots":[ 

         ],
         "result":"SUCCESS",
         "duration":919
      },
      { 
         "number":4,
         "description":"When she logs in",
         "startTime":1581086695296,
         "children":[ 
            { 
               "number":5,
               "description":"Arya logs in to <Obfuscated Website>",
               "startTime":1581086695297,
               "children":[ 
                  { 
                     "number":6,
                     "description":"Arya clicks on the the user icon",
                     "startTime":1581086695297,
                     "children":[ 

                     ],
                     "reportData":[ 

                     ],
                     "screenshots":[ 
                        { 
                           "screenshot":"photo-firefox-arya-clicks-on-the-the-user-icon-dad1f72b8e.png"
                        }
                     ],
                     "result":"SUCCESS",
                     "duration":2581
                  },
                  { 
                     "number":7,
                     "description":"Arya enters '<Obfuscated Email>' into the the email address field",
                     "startTime":1581086697879,
                     "children":[ 

                     ],
                     "reportData":[ 

                     ],
                     "screenshots":[ 
                        { 
                           "screenshot":"photo-firefox-arya-enters-<Obfuscated Email>-into-the-the-email-address-field-1bd27fbedd.png"
                        }
                     ],
                     "result":"SUCCESS",
                     "duration":412
                  },
                  { 
                     "number":8,
                     "description":"Arya enters '<Obfuscated Password>' into the the password field",
                     "startTime":1581086698292,
                     "children":[ 

                     ],
                     "reportData":[ 

                     ],
                     "screenshots":[ 
                        { 
                           "screenshot":"photo-firefox-arya-enters-<Obfuscated Password>-into-the-the-password-field-3673e82b69.png"
                        }
                     ],
                     "result":"SUCCESS",
                     "duration":182
                  },
                  { 
                     "number":9,
                     "description":"Arya clicks on the the sign in button",
                     "startTime":1581086698476,
                     "children":[ 

                     ],
                     "reportData":[ 

                     ],
                     "screenshots":[ 
                        { 
                           "screenshot":"photo-firefox-arya-clicks-on-the-the-sign-in-button-68499d3cfd.png"
                        }
                     ],
                     "result":"SUCCESS",
                     "duration":513
                  }
               ],
               "reportData":[ 

               ],
               "screenshots":[ 

               ],
               "result":"SUCCESS",
               "duration":3693
            }
         ],
         "reportData":[ 

         ],
         "screenshots":[ 

         ],
         "result":"SUCCESS",
         "duration":3695
      },
      { 
         "number":10,
         "description":"Then she should see that she is logged in",
         "startTime":1581086698991,
         "children":[ 

         ],
         "reportData":[ 

         ],
         "screenshots":[ 

         ],
         "result":"PENDING",
         "duration":1
      }
   ],
   "userStory":{ 
      "id":"demo-journeys",
      "storyName":"Demo Journeys",
      "path":"features/demo.feature",
      "type":"feature"
   },
   "startTime":1581086694369,
   "testSource":"Cucumber",
   "tags":[ 
      { 
         "name":"Demo Journeys",
         "type":"feature"
      },
      { 
         "name":"firefox ",
         "type":"browser",
         "browserName":"firefox"
      },
      { 
         "type":"platform"
      }
   ],
   "featureTag":{ 
      "name":"Demo Journeys",
      "type":"feature"
   },
   "context":"firefox",
   "driver":"firefox",
   "duration":4811,
   "result":"PENDING"
}
```

**Comment by robin-weller** [comment]
The difference I am seeing between the Chome and Firefox JSON files is there is no recorded `browserVersion` for Firefox (which is probably fine?!) and there is no `name` defined with `"type": "platform"`?

**Comment by jan-molak** [comment]
Thanks, and what version of Firefox are you running?

Could you please also add the following section to your `protractor.conf.js` and let me know what it prints?

```javascript
    onPrepare: () => {
        return require('protractor').protractor.browser.getCapabilities()
            .then(capabilities => {
                console.log('platform',    capabilities.get('platform'));
                console.log('browserName', capabilities.get('browserName'));
                console.log('version',     capabilities.get('version'));
            });
    },
```

**Comment by jan-molak** [comment]
Hey @robin-weller, can you check out the latest build, please? It should be able to correctly detect details of all the major browsers and platforms.

Scenario view:
![image](https://user-images.githubusercontent.com/1089173/74074964-643af280-4a08-11ea-9e79-a028d70e30f5.png)

Summary view:
![image](https://user-images.githubusercontent.com/1089173/74075147-00fd9000-4a09-11ea-834a-79baf31e41cb.png)

As always, thoughts and feedback welcome!

**Comment by ctaepper** [comment]
seems like I created an issue about the same root cause in #456 I will test the latest version and see if the problem goes away

**Comment by jan-molak** [comment]
Thanks @ctaepper - yeah, my original solution was a tad bit optimistic. I then ran a test against 14 different browser/platform combinations and recorded my findings in [this unit test](https://github.com/serenity-js/serenity-js/commit/99659187b99bb2d97f8cc51910a4f12f2685875c).

If there's anything I missed, please feel free to extend it!

**Comment by robin-weller** [comment]
Thanks @jan-molak, `2.1.1` is looking good for browser tagging :)

Something I am seeing a difference in though is the platform tagging.

Chrome:
```
Browser: Chrome 80.0.3987.87
Platform: Mac OS X
```

Firefox:
```
Browser: Firefox 71.0
Platform: Mac 19.3.0 
```

Currently running Mac OS X 10.15.3 so it looks as though the Firefox run is picking up the Darwin version instead of the OS X version?

**Comment by jan-molak** [comment]
Hey @robin-weller - Different browsers describe the platform they run on differently, and to a different degree of fidelity. If I was to make the reporting consistent, I'd have to go either with the lowest common denominator or introduce another, higher-level tag (`PlatformType`?)

Not sure which one is better. Thoughts?

**Comment by robin-weller** [comment]
I guess it's not going to be perfect either way. If you run one instance of Chrome on Catalina and one on Mohave, you won't see any difference. However, running Firefox would give you a bit more to go on, albeit a Darwin version number.

Having both `Platform` and `Platform Type` would provide the most useful information but could end up cluttering the report when different browsers report different information!

**Comment by jan-molak** [comment]
This functionality has been introduced in `@serenity-js/serenity-bdd` `v2.3.0`, which generates both the `browser` and `platform` tags based on the information provided by the browsers (and some provide more precise information than others...):

![image](https://user-images.githubusercontent.com/1089173/76692864-94ebf880-6654-11ea-83ee-b8ed4943fdd3.png)

It also generates icons for the recognised browsers and platforms:

![image](https://user-images.githubusercontent.com/1089173/76692831-ba2c3700-6653-11ea-8e52-a006b34166df.png)

---
_If Serenity/JS has made your life easier, please consider becoming a sponsor and [buying us a coffee](https://github.com/sponsors/serenity-js) every once in a while :octocat:_
