### ISSUE TITLE
Correct way of storing values between calls

### ISSUE THREAD

**Issue by AlexRex** [serenity-js/serenity-js#463]
I am trying to test an API which requires a JWT token as the authorization mechanism. 

The flow is the following:
1. Call endpoint to login -> JWT from body 
2. Call endpoint to get user -> Get JWT from last request and place it in headers 

The current logic I am doing is the following one: 

1. Make first request and store it in the Notepad
```typescript
Given(/(.*) signs in/, (actorName: string) =>
  actorCalled(actorName).attemptsTo(
    Send.a(
      PostRequest
        .to('/url')
        .with({
          account: {
            email: 'whatever',
            password: 1234
          }
        })
    ),
    Ensure.that(LastResponse.status(), equals(201)),
    TakeNote.of(LastResponse.body())
  )
);
```

2. Extract JWT token from latest request and reuse it in the next request 
```typescript
Given(/(.*) post something in API/, async (actorName: string) => {
  const actor = actorCalled(actorName);
  const bearer = (await Note.of(LastResponse.body()).answeredBy(actor)).auth.access_token;

  return actor.attemptsTo(
    Send.a(
      PostRequest
        .to('/user')
        .with({
          test: 1234
        })
        .using({
          headers: {
            Authorization: `Bearer ${bearer}`
          }
        })
    ),
    Ensure.that(LastResponse.status(), equals(201))
  )
});
```

This is working just fine, but I am not sure if it is the proper way of doing so as here I am forcing the extraction of the bearer token from a previous request using ` const bearer = (await Note.of(LastResponse.body()).answeredBy(actor)).auth.access_token;`.

The problem here is that if in the step number 2 I also need to store something in the Notepad for usage in another API call, how should I retrieve again the bearer token if I override it with `LastResponse.body()`? Should it be stored in a variable or a class like an Ability to remember the JWT token?

Thanks!

**Comment by jan-molak** [comment]
Hey @AlexRex, check out [this example](https://github.com/serenity-js/todo-app/blob/7ea682263300385c9cf69df7212afe5e8d4a7484/projects/todo-app-api/spec/todos.spec.ts#L62-L71) and look at [`Question#map`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html#instance-method-map) to extract the access token from a response body.

Hope this helps!

Jan
