### ISSUE TITLE
serenity-js-cucumber-protractor only generating json but not HTML report

### ISSUE THREAD

**Issue by RaghuGouda** [serenity-js/serenity-js#464]
When the script is run generating the screenshots and the json reports, but not the html reports.
project is:  https://github.com/serenity-js/serenity-js-cucumber-protractor-template
below are the test result 
![Screenshot_225](https://user-images.githubusercontent.com/34091585/74828728-9cf69800-5335-11ea-8510-d5829bf87c73.png)
![Screenshot_226](https://user-images.githubusercontent.com/34091585/74828729-9ec05b80-5335-11ea-85c4-93aabbf5d2d2.png)
![Screenshot_227](https://user-images.githubusercontent.com/34091585/74828734-9ff18880-5335-11ea-9c10-1bc51782c964.png)
![Screenshot_228](https://user-images.githubusercontent.com/34091585/74828736-a08a1f00-5335-11ea-8c38-2a6b221df82d.png)
![Screenshot_229](https://user-images.githubusercontent.com/34091585/74828738-a122b580-5335-11ea-85ba-4c9b5224fd11.png)

**Comment by jan-molak** [comment]
Hi @RaghuGouda, 

Thanks for the screenshots, it really helps me to understand the issue better!

It looks like the `test:report` script is not entirely correct as it calls `serenity-bdd run ./target`

If you run `serenity-bdd` with a `--help` switch as follows:

```
npx serenity-bdd --help run
```

you'll see what arguments the command handles:

```
serenity-bdd run

Invokes the Serenity BDD CLI jar to produce a Serenity BDD HTML report from the
Serenity/JS JSON reports

Options:
  --version          Show version number                               [boolean]
  --cacheDir         A relative path to where the Serenity BDD CLI jar file is
                     stored         [default: "node_modules/@serenity-js/cache"]
  --destination      A relative path to the directory where the Serenity BDD
                     report should be produced [default: "target/site/serenity"]
  --features         A relative path to the directory containing the Cucumber.js
                     feature files                         [default: "features"]
  --artifact         The GAV identifier of the Serenity BDD CLI artifact to use;
                     You're best off with the default option unless you want to
                     experiment.
                        [default: "net.serenity-bdd:serenity-cli:jar:all:2.1.9"]
  --source           A relative path to the directory containing the Serenity/JS
                     JSON reports              [default: "target/site/serenity"]
  --issueTrackerUrl  Base URL for issue trackers other than JIRA
  --jiraProject      JIRA project identifier
  --jiraUrl          Base URL of your JIRA server
  --project          Project name to appear in the Serenity reports
                           [default: "serenity-js-cucumber-protractor-template"]
  --log              A Logback log level to pass to the Serenity BDD CLI jar
                            [choices: "warn", "info", "debug"] [default: "warn"]
  -h, --help         Show help                                      
```

Since your `ArtifactArchiver` in `protractor.conf.js` stores artifacts under `./target/site/serenity` and that's also the default location where `serenity-bdd run` command will look for artifacts, you could change your `test:report` script as follows:

```
"test:report": "serenity-bdd run"
```

Or, if you wanted to be super-explicit:

```
"test:report": "serenity-bdd run --source target/site/serenity --destination target/site/serenity"
```

Does this help?

Best,
Jan

**Comment by RaghuGouda** [comment]
Hi @jan-molak 
I tried both the ways but HTML Report is not generating please have a look 

![Screenshot_230](https://user-images.githubusercontent.com/34091585/74903349-b0a20d00-53ce-11ea-842f-98a866403297.png)
![Screenshot_231](https://user-images.githubusercontent.com/34091585/74903354-b1d33a00-53ce-11ea-83c5-ae35e2674aec.png)
![Screenshot_232](https://user-images.githubusercontent.com/34091585/74903355-b26bd080-53ce-11ea-8647-b9c8049e23e5.png)
![Screenshot_233](https://user-images.githubusercontent.com/34091585/74903356-b26bd080-53ce-11ea-9ad4-830d0db5c6c5.png)
![Screenshot_234](https://user-images.githubusercontent.com/34091585/74903358-b3046700-53ce-11ea-8c16-53b1bf405eac.png)

**Comment by jan-molak** [comment]
Hey @RaghuGouda - Would you be able to push your repository to Github so that I can try to debug the issue? Your config seems correct at first glance so I'd like to get to the bottom of this.

**Comment by RaghuGouda** [comment]
Hello @jan-molak -Please find the below link 
https://github.com/RaghuGouda/serenity

**Comment by jan-molak** [comment]
Thanks! So that's interesting, it seems to be working fine 
![image](https://user-images.githubusercontent.com/1089173/74991710-a881b600-543e-11ea-84d2-13b2f6e85841.png)

I wonder, do you have java installed? What do the following commands return on your machine:
```
java -version
```
and
```
echo %JAVA_HOME%
```
Thanks

**Comment by RaghuGouda** [comment]
ohhh! java haven't installed in my machine .

After installation, it worked. 

Thanks @jan-molak
