### ISSUE TITLE
Where to find serenity-js 2.0

### ISSUE THREAD

**Issue by NicoForce** [serenity-js/serenity-js#473]
I've been working on a huge automation project for two years now using only protractor, jasmine, and page objects as design pattern.

However, due to many mistakes my old self made, this project is not as maintainable as it should be, and so I want to change the stack to use serenity, cucumber, protractor and so on since I believe that the patterns being introduced by serenity will be of huge help in readability and maintenance on our project.

I just watched your youtube video showcasing serenity-js 2.0 and I'd like to use but can't seem to find it anywhere.

I hope you can help me, since I wouldn't like to migrate to serenity 1.0 and then migrate to serenity 2.0.

**Comment by jan-molak** [comment]
Hi @NicoForce - sure, the best place to start is the Serenity/JS website at https://serenity-js.org.

You'll find the [Serenity/JS Handbook](https://serenity-js.org/handbook/index.html) there, which will walk you through the main concepts and features of the framework. The handbook is a work in progress and is continuously evolving, but together with [the video](https://www.youtube.com/watch?v=djPMf-n93Rw) and [the examples](https://github.com/serenity-js/serenity-js/tree/master/examples) should give you a good idea of what Serenity/JS is all about.

If you'd like to start a new Serenity/JS project, the easiest way to do it is to use either the [Jasmine](https://github.com/serenity-js/serenity-js-jasmine-protractor-template) or [Cucumber](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) template projects.

The API docs are available at https://serenity-js.org/modules/ and the Serenity/JS node modules are [published to NPM](https://www.npmjs.com/search?q=%40serenity-js).

Does this answer your question?

**Comment by jan-molak** [comment]
I've realised that it's not immediately obvious that you'd need to click on "show more" to see the links to the website on YouTube.

Hopefully, this little note will address that. What do you think, @NicoForce?

![image](https://user-images.githubusercontent.com/1089173/75096912-58206a80-559c-11ea-87ac-ae6e64921af5.png)
