### ISSUE TITLE
Serenity Report with screenshot (Non-Screenplay) for Protractor/Mocha

### ISSUE THREAD

**Issue by DilipKumar1412** [serenity-js/serenity-js#480]
Not getting test screenshots in serenity report. I am using Protractor/Mocha and I am not finding example report or code in the GitHub

**Comment by jan-molak** [comment]
Hi @DilipKumar1412! Please note that Serenity/JS v2 doesn't support Mocha yet, but you can use it with Jasmine, which `describe/it` interfaces are almost identical. Please see the [template project](https://github.com/serenity-js/serenity-js-jasmine-protractor-template).

Does this help?

**Comment by DilipKumar1412** [comment]
Hi @jan-molak,

Thanks for the reply. Is support for Mocha framework in pipeline or WIP? if yes, when can we expect the release or version?

Thanks

**Comment by jan-molak** [comment]
Adding support for Mocha is definitely possible, but it's not a priority at the moment I'm afraid.
I'm open to PRs enabling this integration and there's always an option for your company to [support Serenity/JS](https://github.com/sponsors/serenity-js) and have the ticket prioritised over other things in the backlog. Is this something you'd consider?

**Comment by jan-molak** [comment]
Closing this ticket as Serenity/JS supports Mocha now, both with Protractor and standalone - https://serenity-js.org/modules/mocha/
