### ISSUE TITLE
Arbitrary screenshots in non-screenplay scenarios

### ISSUE THREAD

**Issue by DilipKumar1412** [serenity-js/serenity-js#490]
Hi @jan-molak ,

I want to display hyperlink in the Assertion message, but it is displaying anchor tag as string in the HTML report.

Expected result should be Screenshot : [2020-03-02T_12_45_58_612Z.png](url)

Is there any workaround to achieve this?

Thanks

**Comment by jan-molak** [comment]
Hey @DilipKumar1412! It looks like the screenshot did not get attached to the ticket, would you mind uploading it again? Thanks!

**Comment by DilipKumar1412** [comment]
I want to display hyperlink in the Assertion message on failure(Modal), all html tags are display as string

![image](https://user-images.githubusercontent.com/61414460/75955181-5c714f80-5edb-11ea-8b61-ffd4352fd8e3.png)

Expected result should be Screenshot : [2020-03-02T_12_45_58_612Z.png](/)

**Comment by jan-molak** [comment]
I'd like to better understand your use case.

- Would you be able to elaborate further on the problem you're trying to solve? Why do you need to display a html tag in a report while Serenity/JS could take a screenshot for you automatically upon the assertion failure?
- Could you provide a code sample you're using right now to accomplish the result from the screenshot above?

Thanks!

**Comment by DilipKumar1412** [comment]
![image](https://user-images.githubusercontent.com/61414460/75962706-46b75680-5eea-11ea-804c-06a34cc82936.png)

We are using serenity report for Protractor/Mocha framework (Non-screenplay), we don't have option to take screenshot on failure(as you mentioned in the below thread https://github.com/serenity-js/serenity-js/issues/480).

So, we are taking screenshot and storing in a folder using browser.takeScreenshot() method, if test fails, we are passing screenshot path in assertion (using Chai Assertion).

**Syntax :** expect(value, errormessage).to.be.true
**Example :** expect(false, 'Error: \nScreenshot: anchor tag like below').to.be.true

![image](https://user-images.githubusercontent.com/61414460/75961563-3f8f4900-5ee8-11ea-93b1-e7ed93fdfa75.png)

But, I am expecting something like clickable ---> Screenshot : [2020-03-02T_12_45_58_612Z.png](/)

**Comment by jan-molak** [comment]
Right, I see what you mean. I'm afraid it's not designed to work this way.
I'd suggest you consider migrating to Serenity/JS v2 and then either using Screenplay _or_ using the internal Serenity/JS communication mechanism to inform the framework of the screenshot you've taken so that it's included in the report.

Does this help?

**Comment by jan-molak** [comment]
@DilipKumar1412 I haven't heard from you in a while so I'm going to close this ticket as support for screenshots in non-screenplay scenarios is tracked under #362
