### ISSUE TITLE
screenshots for each interactions in non-screenplay style scenarios

### ISSUE THREAD

**Issue by RaghuGouda** [serenity-js/serenity-js#495]
Hi @jan-molak ,
Is there any way to take screen shots for each interactions in After hook ,
I have tried adding TakePhotosOfInteractions in after hook but its not working 

After(function (this: WithStage, scenario) {
    return this.stage.theActorCalled('Inspector').attemptsTo(
        TakePhotosOfInteractions.of(scenario.pickle.name)
    );
});

**Comment by jan-molak** [comment]
Hey @RaghuGouda - the above code sample above is not exactly correct as [`TakePhotosOfInteractions`](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/strategies/TakePhotosOfInteractions.ts~TakePhotosOfInteractions.html) is how you configure a [`Photographer`](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html) - a service that takes screenshots automatically. What you're after is an [`Interaction`](https://serenity-js.org/handbook/design/interactions.html) to [`TakeScreenshot`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/TakeScreenshot.ts~TakeScreenshot.html) you can instruct an actor to perform in `attemptsTo(...)`,

Please see [my comment](https://github.com/serenity-js/serenity-js/issues/362#issuecomment-587433248) on #362 for an example.

Does this help?

**Comment by RaghuGouda** [comment]
Actully i want take screen shot for each step.
 
In this case it will take screen shots when ever it fails 

After({tags:"@ass"},function (this: WithStage, scenario) {
    return this.stage.theActorCalled('Inspector').attemptsTo(
        Check.whether(scenario.result.status, equals('failed'))
            .andIfSo(TakeScreenshot.of(scenario.pickle.name))
    );
});

and in this case it will take screen shots after the scenario

 After(function (this: WithStage, scenario) {
    return this.stage.theActorCalled('Inspector').attemptsTo(         TakeScreenshot.of(scenario.pickle.name)     
);
 });

So is there any ways to take screen shots for each and every steps of the scenario
