### ISSUE TITLE
Not able to use isDisabled() or isNotEnabled() assertion

### ISSUE THREAD

**Issue by Manishrn** [serenity-js/serenity-js#496]
Hi
I am trying to check that perticular webelement is disabled or not .
I can see that Ensure.that(target, isVisible()) and Ensure.that(target, isEnabled()) is there, however
not able to find isDisabled()/isNotEnabled() .

Is there a way to achieve this ? @wakaleo @jan-molak 

I did not see any declaration of isNotEnabled/ isDisabled in below image
![image](https://user-images.githubusercontent.com/24430750/76332205-17538000-6316-11ea-99e8-cfec7e719355.png)

**Comment by jan-molak** [comment]
Hey @Manishrn - sure, you can combine the expectations from the [`@serenity-js/protractor` module](https://serenity-js.org/modules/protractor/identifiers.html#expectations) with the ones from [`@serenity-js/assertions`](https://serenity-js.org/modules/assertions/identifiers.html#expectations).

For example:
```
import { Ensure, not } from '@serenity-js/assertions';
import { isEnabled } from '@serenity-js/protractor';

actor.attemptsTo(
  Ensure.that(target, not(isEnabled())),
);
```

Hope this helps!
Jan

**Comment by Manishrn** [comment]
@jan-molak Thank you 👍  , I will check this.

**Comment by Manishrn** [comment]
@jan-molak  working fine, Thank you :)

**Comment by jan-molak** [comment]
@Manishrn - splendid! Thanks for letting me know 🎉
