### ISSUE TITLE
npm test:report not working in serenity-js 2.2.2 -says corrupt jar for 2.1.9

### ISSUE THREAD

**Issue by usvgmani** [serenity-js/serenity-js#502]
**I get below exception while trying to run "serenity-bdd run" to get a test report on the serenity js 2.2.2 on java 1.8 on macos, when I manually download 2.1.8-all.jar the same command works. Does 2.1.9 require a certain version of java?**

> [test:report] Spawning: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java -DLOG_LEVEL=warn -Dlogback.configurationFile=/Users/.../node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -jar node_modules/@serenity-js/cache/serenity-cli-2.1.9-all.jar --destination target/site/serenity --features features --source target/site/serenity --project sample-serenity-bdd
> [test:report] Error: Invalid or corrupt jarfile node_modules/@serenity-js/cache/serenity-cli-2.1.9-all.jar
> [test:report] I'm terribly sorry, but something didn't go according to plan.
> [test:report] The following process exited with 1: **/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java** -DLOG_LEVEL=warn -Dlogback.configurationFile=/Users/.../node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -jar node_modules/@serenity-js/cache/serenity-cli-2.1.9-all.jar --destination target/site/serenity --features features --source target/site/serenity --project sample-serenity-bdd

**Comment by usvgmani** [comment]
All fine, Issue with the local jar and download. Apologies.

**Comment by jan-molak** [comment]
No worries, glad you got it sorted out!
