### ISSUE TITLE
Contributing and compiling and testing the serenity-js repository 

### ISSUE THREAD

**Issue by andreasmarkussen** [serenity-js/serenity-js#503]
Node setup: Windows 10 with Node v13.9.0

I am unable to compile and run the tests. 

I wanted to contribute to the Serenity-JS project, with a test case and a fix, to detecting if Java is missing, but after a few hours, I had to give up. 

I tried to do the following 

    npm install compile test

But I keep getting dependency problems. 

```
@integration/testing-tools: > @integration/testing-tools@2.2.2 compile C:\Tech\forks\serenity-js\integration\testing-tools
@integration/testing-tools: > tsc --project tsconfig.json
@integration/testing-tools: C:\Tech\forks\serenity-js\integration\testing-tools>"node"  "C:\Tech\forks\serenity-js\integration\testing-tools\node_modules\.bin\\..\..\..\..\node_modules\typescript\bin\tsc" --project tsconfig.json
@integration/testing-tools: src/child-process-reporter/ChildProcessReporter.ts(1,29): error TS2307: Cannot find module '@serenity-js/core/lib/events'.
@integration/testing-tools: src/child-process-reporter/ChildProcessReporter.ts(2,40): error TS2307: Cannot find module '@serenity-js/core/lib/stage'.
@integration/testing-tools: src/EventRecorder.ts(1,29): error TS2307: Cannot find module '@serenity-js/core/lib/events'.
@integration/testing-tools: src/EventRecorder.ts(2,40): error TS2307: Cannot find module '@serenity-js/core/lib/stage'.
@integration/testing-tools: src/givenFollowingEvents.ts(1,29): error TS2307: Cannot find module '@serenity-js/core/lib/events'.
```

I have also tried using Ubuntu on my windows machine (WSL2)
Linux [MachineName] 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Same response

**Comment by jan-molak** [comment]
Hi @andreasmarkussen, and thanks again for offering your time and help!

As per our conversation on the [Serenity/JS Gitter channel](https://gitter.im/serenity-js/Lobby), please check out the [contributing guide](https://serenity-js.org/contributing.html#proposing-enhancements).

After cloning a fork of the Serenity/JS monorepo you'll need to run:
```
npm install 
make clean verify report
```

Hope this helps!
Jan
