### ISSUE TITLE
Log.the should pretty-print JSON objects

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#509]

**Comment by jan-molak** [comment]
Hey @abhinaba1080 could you please provide a sample of what you're getting and what you'd expect?

**Comment by abhinaba1080** [comment]
I mean currently Log.the(LastResponse.body()) prints stringified JSON response in the console. Is there a way to print the message like a JSON structure in the console?

**Comment by jan-molak** [comment]
Ah, I see what you mean. Yeah, at the moment it [prints it as string](https://github.com/serenity-js/serenity-js/blob/986ae29d8f6dd5570955ddc17404dae9fc2abcb3/packages/console-reporter/src/stage/crew/console-reporter/ConsoleReporter.ts#L256), while it should probably [inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options) it.

I think we should do it; I'll add it to the backlog, but if anyone wants to submit a PR I'd be happy to help out with it.

**Comment by abhinaba1080** [comment]
I will look into the backlogs from next week. Will connect to you.
