### ISSUE TITLE
Need help to understand Ensure assertions better for REST API testing

### ISSUE THREAD

**Issue by abhinaba1080** [serenity-js/serenity-js#512]
Hi @jan-molak ,

I am using the following assertion :

Question 1:

```ts
await actorInTheSpotlight().attemptsTo(Ensure.that(LastResponse.body(), not(contain('<summary>'))));
```
and also tried:

```ts
await actorInTheSpotlight().attemptsTo(Ensure.that(Transform.the(LastResponse.body(), body => body.value), not(contain('<summary>'))));
```

But getting the error like:

```
TypeError: actualValue.findIndex is not a function
      at DynamicallyGeneratedExpectation.predicate (C:\Dev Room\Projects\Demo\node_modules\@serenity-js\assertions\src\expectations\contain.ts:8:66)
      at C:\Dev Room\Projects\Demo\node_modules\@serenity-js\assertions\src\Expectation.ts:115:29
```

Question 2:

I am having a response body like:

```
{
   "@odata.context":"Err.Silder"
  Response",
   "@odata.type":"#Error.ValidationErrorResponse",
   "HttpStatus":400,
   "InternalMessage":"Validation Error Message",
   "Type":"Validation",
   "ValidationErrors":[
      {
         "Message":"Invalid request format.",
         "InternalMessage":null,
         "ErroredValue":null,
         "Description":"",
         "Reason":"Validation",
         "Severity":"Error"
      }
   ],
   "ObjectId":null
}
```

and my action is like:

```ts
 await actorInTheSpotlight().attemptsTo(Log.the(LastResponse.body()), Ensure.that(LastResponse.body(), property('Message', equals(message))));
```
I am getting error message like:

```

    ✗ adminensures that the body of the last response does have property 'Message' that does equal 'Invalid request format.' (4ms)

      Difference (+ expected, - actual):

      - undefined
      + 'Invalid request format.'
```
Currently, I am handing this very situation with Transform like:

```ts
await actorInTheSpotlight().attemptsTo(Ensure.that(Transform.the(LastResponse.body(), body => body.ValidationErrors[0].Message), equals(message)));
```

But we should have a deep equals logic. 

Can we have some real-time examples to check how to efficiently make use of Ensure assertion mechanism?

**Comment by jan-molak** [comment]
Hey @abhinaba1080!

[`contain`](https://serenity-js.org/modules/assertions/file/src/expectations/contain.ts.html) is used to check if a _list_ contains an item, for example:

```typescript
actorInTheSpotlight().attemptsTo(
    Ensure.that([1,2,3], contain(1)),
);
```

or with objects:
```typescript
actorInTheSpotlight().attemptsTo(
    Ensure.that([{ name: 'Abhinaba' }, { name: 'Jan' } ], contain({ name: 'Abhinaba' })),
);
```

Now, `LastResponse.body()` returns the body of the last response, so if your server returned JSON, axios will [turn it into a JSON object automatically](https://github.com/axios/axios/blob/6642ca9aa1efae47b1a9d3ce3adc98416318661c/lib/defaults.js#L57-L65).

So, given a HTTP API at `http://localhost:8080/developers` that returns:
```json
[
  { "name": "Abhinaba", "id": "@abhinaba1080" },
  { "name": "Jan", "id": "@jan-molak" },
]
```

you could write a flow as follows:
```typescript
actorInTheSpotlight().attemptsTo(
    Send.a(GetRequest.to('http://localhost:8080/developers')),
    Ensure.that(LastResponse.body(), contain({ "name": "Abhinaba", "id": "@abhinaba1080" })),
);
```

Does this answer your question?

**Comment by abhinaba1080** [comment]
Hey @jan-molak . Thanks for the clarification. But I was looking for some deep-equal/deep-contains mechanism. 

If I get the response from API endpoint like:

```
[
  { "name": "Abhinaba", "id": "@abhinaba1080" },
  { "name": "Jan", "id": "@jan-molak" },
]
```
is there a way to just check this reponse contains text as "Jan" or not querying the LastResponse?

**Comment by jan-molak** [comment]
Well, the response is not a string of text, though, it's a JSON object so it's best to treat it as such.

While it's technically possible to map the object back to string and then use a string predicate with it, so:

```typescript
Ensure.that(
    Transform.the(LastResponse.body(), body => JSON.stringify(body)),
    includes('Jan'),
)
```
I think that this is a _**really, really, really bad idea**_, since it would match things like `Jan`, `January`, `Jannice` and so on (did I mention we should not do it? 😄)

However, if the outcome that you're after is an assertion that verifies if the list [contains at least one item that](https://serenity-js.org/modules/assertions/function/index.html#static-function-containAtLeastOneItemThat) has a [property](https://serenity-js.org/modules/assertions/function/index.html#static-function-property) of `name` [equal to](https://serenity-js.org/modules/assertions/function/index.html#static-function-equals) `Jan`, there's a better way to do it:

```typescript
import { containAtLeastOneItemThat, property, equals } from '@serenity-js/assertions';

Ensure.that(
    LastResponse.body(),
    containAtLeastOneItemThat(property('name', equals('Jan')))
),
```

Does this solve the problem?

**Comment by abhinaba1080** [comment]
Thats It! Thanks.
