### ISSUE TITLE
Clarification about reporting in Non-Screenplay scenarios 

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#513]
Hi @jan-molak ,

It is really sad that we can't take the screenshot of each step in a Non-Screenplay pattern. Can we put that for enhancement?

1. Come back to the actual issue. Can I configure a custom message in Check.whether? "Inspector ensures that 'failed' does equal 'failed'" may not be an appropriate message to show. 

![image](https://user-images.githubusercontent.com/23141842/77143168-6f258000-6aa8-11ea-9224-cf79380fa973.png)

2. Not only that, if we set the stage as suggested in the description of this issue, we get a message like:

```
serenity.callToStageFor(...) has been deprecated. Please use `actorCalled(name)` and `actorInTheSpotlight()` functions from @serenity-js/core to access the actors instead.
```
3. Screenshots in each step are highly required.  It was working fine in Serenity 1.x in Non-Screenplay scenarios. Is there any workaround to get it solved? 

4. My terminal is not showing the passed tick marks on passed scenarios.

**Comment by jan-molak** [comment]
Hey @abhinaba1080 - it looks like 4 different issues in one ticket, could we tackle them separately and close this one, please?

**Comment by jan-molak** [comment]
Closing as we have separate tickets to track those requests:
- see #362 for reporting for non-screenplay scenarios
- see #524 for better support of Windows terminals
