### ISSUE TITLE
Not able to set protractor timeout for navigation

### ISSUE THREAD

**Issue by ctaepper** [serenity-js/serenity-js#517]
[Here](https://github.com/serenity-js/serenity-js/blob/master/packages/protractor/src/screenplay/abilities/BrowseTheWeb.ts#L82) is an option to set `timeoutInMillis` for protractors' `browser.get` method. However using the higher level [interaction](https://github.com/serenity-js/serenity-js/blob/master/packages/protractor/src/screenplay/interactions/Navigate.ts#L16) I cannot set this timeout unfortunately :(

I am hoping, you could fix that

**Comment by jan-molak** [comment]
Ha, well spotted! Thanks :-)

I'll add it to [the backlog](https://github.com/orgs/serenity-js/projects); in the meantime, if anyone would like to take a stab at a PR I'd be happy to review those as well.

I think the following API could do the trick.

```typescript
Navigate.to(url).waitingUpTo(duration: Duration)
```
