### ISSUE TITLE
passing stack traces to serenity-cli

### ISSUE THREAD

**Issue by nbarrett** [serenity-js/serenity-js#53]
In Serenity BDD it's possible to pass full stack traces into the html report by means of the [simplified.stack.traces](http://thucydides.info/docs/serenity-staging/#_running_serenity_tests_from_the_command_line) property. Is it possible to do the same in serenity-js? Currently when I pop up the show stack trace modal I just get the error message, which doesn't provide much to go on:

![image](https://cloud.githubusercontent.com/assets/626941/26630663/956a6ae4-45ff-11e7-9a94-546c7fe72735.png)

btw, I'm currently trying to determine the root cause of a flickering test in [tutorial-journey-planner](https://github.com/serenity-js/tutorial-journey-planner/blob/master/features/saving_time/journey_planner.feature) aarrgh!

**Comment by jan-molak** [comment]
The stack trace you see goes all the way down to Serenity/JS internals, which felt to me like not adding much to the report (?) This filtering is [done here](https://github.com/jan-molak/serenity-js/blob/7b4cce6f66e98ed19b681f8711c1becdf8570cc2/packages/serenity-js/src/serenity/reporting/serenity_bdd_reporter.ts#L192). Do you think it's useful to see the framework internal in the report?

**Comment by nbarrett** [comment]
As a developer reading the serenity report, to see the stack trace along with the failure has often been very useful - especially if one is trying to diagnose why something is not working within the automation framework. For a simple assertion failure, no that's not as important.

**Comment by nbarrett** [comment]
update: I'm seeing this now in [release 1.6.2](https://github.com/jan-molak/serenity-js/releases/tag/serenity-js%401.6.2) when an exception is thrown which is an improvement. Has something changed? 

![image](https://user-images.githubusercontent.com/626941/27054647-29b21c6e-4fb1-11e7-919f-2fcfddc81008.png)


Note that this is the exception that still reproduces issue #64.

**Comment by jan-molak** [comment]
Thanks Nick, would you mind creating a minimum runnable test case that would allow me to reproduce the problem? Ideally, something running against a public website :-)

**Comment by jan-molak** [comment]
Hey @nbarrett - I've completely re-written the error handling in Serenity/JS 2.0. Would you mind checking if your requirement is satisfied with the new release?

**Comment by nbarrett** [comment]
Sure thing @jan-molak - thanks again!
