### ISSUE TITLE
Generate empty report after error

### ISSUE THREAD

**Issue by DanteWitcher** [serenity-js/serenity-js#530]
It happens not constantly, when go through test, if I get error types like this (Linux): 

![image](https://user-images.githubusercontent.com/17080180/79113765-4ed8a080-7d8a-11ea-90f7-7996960236a8.png)

then will be generated empty report:

![image](https://user-images.githubusercontent.com/17080180/79113841-7465aa00-7d8a-11ea-8915-31ae0c9c5008.png)

mb you have some ideas why it happens?

    "@serenity-js/assertions": "^2.1.5",
    "@serenity-js/console-reporter": "^2.1.5",
    "@serenity-js/core": "^2.1.5",
    "@serenity-js/cucumber": "^2.1.5",
    "@serenity-js/protractor": "^2.1.5",
    "@serenity-js/rest": "^2.1.5",
    "@serenity-js/serenity-bdd": "^2.1.5",

**Comment by jan-molak** [comment]
Hey @DanteWitcher, the only issue I'm aware of that would be causing this is when you forget to return the result of actor.attemptsTo in a cucumber step. Since this method returns a promise, if said promise is not returned, Cucumber gets out of sync with Serenity.

Hope this helps!
Jan

**Comment by DanteWitcher** [comment]
@jan-molak ok, thanks for quick answer, I recheck all
