### ISSUE TITLE
Serenity session variable usage

### ISSUE THREAD

**Issue by camillomurcia** [serenity-js/serenity-js#547]
Hello team, I hope you are well, I want to know what the uspo is like or if there is a way to store session variables and then use them later to perform some validation in the front

Thank you very much, and excellent work with serenity / js.

**Comment by jan-molak** [comment]
Hey @camillomurcia and thanks for your kind words!

It sounds like you might be after the ability to [`TakeNotes`](https://serenity-js.org/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html).

Let me know if that helps!

Jan

**Comment by camillomurcia** [comment]
Or if I mean this, that the actor can remember something later in the test!

I have already implemented it.

Thank you

**Comment by jan-molak** [comment]
Cool, happy to have helped! 😄
