### ISSUE TITLE
Request to get the 'Select' interaction back

### ISSUE THREAD

**Issue by Ijee** [serenity-js/serenity-js#572]
As it currently stands the Select.the(...) functionality has been removed since 2.0 of Serenity-JS but is still really useful.

It can still be found in the 1.x branch [here](https://github.com/serenity-js/serenity-js/blob/1.x/packages/serenity-js/src/serenity-protractor/screenplay/interactions/select.ts) and with some typing changes can still be used as it would have been in 1.x.

@jan-molak mentioned some changes that he would like to make before re-releasing this functionality

**Comment by skotti-de** [comment]
I agree, having the interaction back would be quite nice.

**Comment by nbarrett** [comment]
Maybe I can try and rebase [PR #373](https://github.com/serenity-js/serenity-js/pull/373) and then implement the vocabulary that @jan-molak suggested [here](https://github.com/serenity-js/serenity-js/pull/373#issuecomment-584591531)?

**Comment by jan-molak** [comment]
Thanks @nbarrett, that would be great :-)

**Comment by jan-molak** [comment]
Introduced in Serenity/JS 2.14.0
