### ISSUE TITLE
Question about screenshots on serenity report

### ISSUE THREAD

**Issue by jacquecosta** [serenity-js/serenity-js#582]
Looking at the report generated on [template's project for protractor and cucumber](https://github.com/serenity-js/serenity-js-cucumber-protractor-template), I have noticed this behaviour:

- Following the screenshots's trail I had this result:

> 1) Given Callie decides to use the Super Calculator
> 2) Callie navigates to '/protractor-demo/'
> 3) When she adds 19 and 23
> 4) Callie enters a left operand of 19
> 5) Callie enters a right operand of 23
> 6) Callie confirms calculation
> 7) Callie enters 19 into the left operand input
> 8) Callie waits up to 5s until the left operand input does become visible
> 9) Callie clicks on the left operand input
> 10) Callie selects the + operator...

Resuming, after step 6 you have more details about step 3. So, the details of a scenario turns a bit confuse when 'read' only by the screenshots.

- While in console the result is similar to:

> Given Callie decides to use the Super Calculator
>      ✓ Callie navigates to '/protractor-demo/' 
> When she adds 19 and 23
>      Callie enters a left operand of 19
>        ✓ Callie enters 19 into the left operand input 
>        ✓ Callie waits up to 5s until the left operand input does become visible 
>        ✓ Callie clicks on the left operand input
>      ✓ Callie selects the + operator 
> Callie enters a right operand of 23
>        ✓ Callie enters 23 into the right operand input
> Callie confirms calculation
>        ✓ Callie clicks on the "Go" button 
> Then she should see that the result is 42
>      ✓ Callie ensures that the text of the result does equal '42'

Are there a explanation about this or a way better to present screenshots (like only in Tasks calls or Step calls) ?

**Comment by jan-molak** [comment]
Thanks @jacquecosta, you're right, screenshots in the slideshow view seem to be out of order. @wakaleo and I will investigate this.

**Comment by jan-molak** [comment]
Hey @jacquecosta - this issue is now fixed in `@serenity-js/serenity-bdd` v `2.8.1`. Thanks for reporting it!
