### ISSUE TITLE
add support for storing the answer under a custom string

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#586]
Hi,

It would be nice to have support for storing the answer in a custom string and reusing it at any given time in the process. 

```js
TakeNote.of(LastResponse.body()).as('first response'),
```

**Comment by jan-molak** [comment]
This is available in the latest release, check out [the docs](https://serenity-js.org/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html) and [unit tests](https://serenity-js.org/modules/core/test-file/spec/screenplay/abilities/TakeNotes.spec.ts.html) for examples.
