### ISSUE TITLE
Question on changed Target.of functionality

### ISSUE THREAD

**Issue by puddles-1** [serenity-js/serenity-js#598]
I'm currently upgrading from serenity-js 1.x to serenity-js 2.0 and the tests I have heavily use the old target.of functionality of being able to replace tokens such as "{0}", I'm wondering why this was changed and if there is any plans to reintroduce this or should i be trying to rewrite my tests another way. This is an example of what i was using before and I would like some advice how best to refactor this to work with serenity-js 2.0

```
performAs(actor: PerformsActivities): PromiseLike<void> {
        return actor.attemptsTo(
            Click.on(
                InventorySearchTable.Column_Header.of(this.fieldName).called(
                    `${this.fieldName} column header of table`,
                ),
            ),
        );
    }

static Column_Header = Target.the('column header of table').located(
        by.xpath(
            '//div[contains(@class, "ag-header-cell-label")] //span[text()[contains(.,"{0}")]]',
        ),
    );
```

**Comment by jan-molak** [comment]
Hi @puddles-1 and thanks for staying up to date with the framework!

The `Target.of` API in Serenity/JS v. 2 is an improvement on version 1 as it allows you to locate elements in relation to other elements as opposed to merely doing a string replacement (see the [specs](https://github.com/serenity-js/serenity-js/blob/master/packages/protractor/spec/screenplay/questions/Target.spec.ts)). 

For example:

```typescript
    class ShoppingList {
        static App                  = Target.the('shopping list app').located(by.id('shopping-list-app'));
        static Progress             = Target.the('progress bar').located(by.css('.progress')).of(ShoppingList.App);
        static Number_Of_Items_Left = Target.the('number of items left').of(ShoppingList.Progress).located(by.css('span'));

        static Header       = Target.the('header').located(by.tagName('h1'));
        static List         = Target.the('shopping list').located(by.tagName('ul'));
        static Items        = Target.all('items').of(ShoppingList.App).located(by.tagName('li'));
        static Bought_Items = Target.all('bought items').located(by.css('.bought')).of(ShoppingList.List);
    }
```

What you can do in your example, though, is to turn the `Column_Header` into a function:

```typescript
performAs(actor: PerformsActivities): PromiseLike<void> {
        return actor.attemptsTo(
            Click.on(
                InventorySearchTable.columnHeaderCalled(this.fieldName),
            ),
        );
    }

static columnHeaderCalled = (headerName: string) =>
    Target.the(`${ headerName } column header of table`).located(
        by.xpath(
            `//div[contains(@class, "ag-header-cell-label")] //span[text()[contains(.,"${ headerName }")]]`,
        ),
    );
```

Please note that in the example above I've also used [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to generate both the locator and the name of the target.

Does this help?
Jan

**Comment by puddles-1** [comment]
Hi Jan,
Thanks for the prompt answer. This is very helpful and will get me going again.

Cheers
