### ISSUE TITLE
How to retain two different values of same target element before and after state change

### ISSUE THREAD

**Issue by Manishrn** [serenity-js/serenity-js#600]
Hi @jan-molak 

I am trying to validate a table row, The values I need to validate is before and after sorting of perticular column in the row.
The change in the values which needs to be validated are on same Target element (on the same row).
With the help of TakeNote.of and Note.of implemetation I am able to remember/get the text values. However when I sort the table the and get the text values again then values which I had earlier will be lost.
Is there a way by which we can keep both the values (before and after sort) and compare ?

Regards,
Manish

**Comment by jan-molak** [comment]
Hey @Manishrn,

Do you need to store _both_ values? Or could you just store the first one and then read the new value when performing the assertion? Check out [this example](https://serenity-js.org/modules/core/class/src/screenplay/questions/Note.ts~Note.html).

If for some reason you have to retain both values, then you'd need #586

Hope this helps,
Jan

**Comment by Manishrn** [comment]
Hi @jan-molak 

Your suggested approach worked. Thank you :)
It would be really nice once #586 ready.


Regards,
Manish

**Comment by jan-molak** [comment]
Cool, thanks for letting me know! Please feel free to upvote #586

Best,
Jan
