### ISSUE TITLE
Potential bug with Text.ofAll()

### ISSUE THREAD

**Issue by Ijee** [serenity-js/serenity-js#603]
As I mentioned on gitter currently Text.ofAll() does not return an array when your target points towards a select and you want to get the option text. Instead it will return a string that contains new line breaks as \n.

```
<html>
  <select>
    <h1>Category</h1>
    <option>Feature</option>
    <option>Bug</option>
   </select>
</html>
```

Here text.ofAll(Target.the('Category select').located(by.css('html &gt; select')); would currently only return 

`Feature\nBug\n` as the actual value as a string on the site.

It only does that currently for html selects and works for every other html strcuture I used it on.

**I added a reproduceable unit test on my fork [here](https://github.com/Ijee/serenity-js-text-ofall-test/blob/master/packages/protractor/spec/screenplay/questions/Text.spec.ts)** 

In the meantime can I somehow get the values myself and transform them to an array so I can easily compare them for my tests? As I have quite a lot of those tests spread around in one of my test repos a lot of tests currently fail.

**Comment by Ijee** [comment]
I haven't 100% confirmed it yet but Text.of() also seems to not get the actual selected visible text from a target that points to a select.

**Comment by jan-molak** [comment]
Hi @Ijee,

Thanks for providing a test case!

Given a HTML snippet like in the example above:
```html
<html>
  <select>
    <h1>Category</h1>
    <option>Feature</option>
    <option>Bug</option>
   </select>
</html>
```
and the question:
```typescript
Text.ofAll(Target.the('Category select').located(by.css('html > select'));
```
what you're effectively saying is "give me text of all the `select` elements". 

However, because there's only one `select` element, you're being given the text that element contains, which is the visible text of all its nested elements - so `h1` and `option`s.

Could you try adding `option` to the selector and let me know if that helps:
```typescript
Text.ofAll(Target.the('Category select').located(by.css('html > select option'));
```

Thanks,
Jan

**Comment by Ijee** [comment]
So the thing is. 
`Text.of(Target.the('Category select').located.(by.css('html > select'));`
returns an array that returns the visible text for all visible options. Whereas I expected that Text.of() to just return the current visible selected option text and `Text.ofAll(Target.the('Category select').located.(by.css('html > select'));` to return an array with all visible option texts.

Hope that makes sense. I am not sure that I really want different Targets for the same HTML Element when I want all visible text options or just the selected one.

**Comment by nbarrett** [comment]
Hi @Ijee - maybe [this PR](https://github.com/serenity-js/serenity-js/pull/373#issuecomment-650453652) might provide you with more flexibility in getting the exact text you want? Hopefully will be merged soon @jan-molak?

**Comment by Ijee** [comment]
@nbarrett that really looks like what I was looking for / expected. I like it!

**Comment by Ijee** [comment]
So it's been  a year and I still have this problem.

The thing is that I know what you mean but I don't see myself writing multiple targets for selects. I just don't see why that is necessary. This way I'd  have to have a different target if I wanted to select a specific value / option text and another one if I wanted to check the currently selected value or am I missing something? 

I got quite a lot of problems with my tests for a while now and I am basically still stuck on the old 1.x version due to a big amount of tests just failing..

I mean yeah it is kind of my problem because in the old version I did a lot of custom Questions to get the desired result like this
```
const optionsQuestion = Question.about(
            'all select option texts',
            () => targetElementFinder.map(ele => ele.getText().then(val => val.trim())) as PromiseLike<string[]>,
        );
```
This Question basically just got all the option text and I could simply assert them with my test case.

If I knew how to make them work again I'd do so in a hearbeat.

**Comment by jan-molak** [comment]
Closing the ticket since like @nbarrett has mentioned - Serenity/JS has added an interaction to [`Select`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Select.ts~Select.html) and a question about [`Selected`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/Selected.ts~Selected.html).

Hope they'll make your life easier, @Ijee :-)
