### ISSUE TITLE
Retry Failed Test with Protractor Flake

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#605]
Hi @jan-molak, Greetings!

Its being a long since i have started working with Serenity JS, which really helped us achieve the best results into test automation. Thanks again.

Now, i am trying my hands with Protractor Flake with serenity framework. I saw many posts.. even here with the configurations to retest the failed scenarios.

When i run the test with protractor flake  it do gives me the failed scenarios. Now if a feature which has two scenarios then also it runs the whole feature instead of the failed test scenario. Any suggestions please.

Thanks,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax, welcome back!

Have you looked at the new [`@serenity-js/mocha`](https://serenity-js.org/modules/mocha/) module? It integrates with Mocha 8 which supports [re-running failed scenarios](https://serenity-js.org/modules/mocha/class/src/adapter/MochaConfig.ts~MochaConfig.html#instance-member-retries).

Let me know if that solves your issue!

Thanks,
Jan

**Comment by AbhineetSharmax** [comment]
@jan-molak , Thank you for your help. We somehow managed to run flakes and its running the failed scenarios in a sequence.
