### ISSUE TITLE
Connect to database using serenity JS (postgres)

### ISSUE THREAD

**Issue by ghost** [serenity-js/serenity-js#611]
Hi,

I'm trying to connect to a postgresql database, by following the instructions in this post
https://github.com/serenity-js/serenity-js/issues/94

However, when I execute the question, I keep getting undefined.
Any ideas what can be wrong?

Here is the Ability
```typescript
const { Client } = require('pg');

const sql = new Client({
    // config
});

export class InteractWithDatabase implements Ability {

  static using() {
    return new InteractWithDatabase();
  }

  static as(actor: UsesAbilities): InteractWithDatabase {
    return actor.abilityTo(InteractWithDatabase);
  }

  constructor() {
  }

  execute(query: string): PromiseLike<any> {
    return sql.connect().then(() => {
      return sql.query${query}
    }).then((result: any) => {
      console.dir(result)
    }).catch((err: any) => {
      // ... error checks
    })
  }
}
```

Here is the Interaction

```typescript
export class ExecuteSqlQuery implements Interaction {

  static using(query: string) {
    return new ExecuteSqlQuery(query);

  }

  performAs(actor: UsesAbilities): PromiseLike<any> {
    return InteractWithDatabase.as(actor).execute(this.query);
  }

  constructor(private query: string) {
  }
}
```

Here is the Question
```typescript
export const UserData = (query) => Question.about(`user data stored in the database`, 
    actor => InteractWithDatabase.as(actor).execute(query)
);
```

Here is the usage of the question
```typescript
actorInTheSpotlight().answer(UserData('select * from TABLE  limit 1')).then(result => console.log(result))
```

Any ideas on what can be wrong?

**Comment by jan-molak** [comment]
Hey @rodrigo-costa-sofist,

The general structure looks OK, but have a look at the ability:

```typescript
export class InteractWithDatabase implements Ability {

  static using() {
    return new InteractWithDatabase();
  }

  static as(actor: UsesAbilities): InteractWithDatabase {
    return actor.abilityTo(InteractWithDatabase);
  }

  constructor() {
  }

  execute(query: string): PromiseLike<any> {
    return sql.connect().then(() => {
      return sql.query${query}
    }).then((result: any) => {
        // this statement doesn't return the `result`, 
        // only prints it to the console and then returns void
      console.dir(result)                
    }).catch((err: any) => {
      // ... error checks                  // <- if an error is caught, what does this statement return?
    })
  }
}
```
I have a feeling that either there's an error somewhere with the connection/statement execution and it's swallowed by InteractWithDatabase, or the `result` is not returned in `then`

Does this help?

Jan

**Comment by rodrigo-costa-sofist** [comment]
Hello mr @jan-molak , you were totally right!

I had to return the result, and I also console.log() the err statement, so I could see that I was actually not being able to authenticate on the postgres database, due to a wrong parameter.

So, now my connection with the database is working totally right!

I realized that I was using the parameter 'username' when it is 'user' actually.
This is how the ability is now.

`import { Ability, UsesAbilities } from "@serenity-js/core/lib/screenplay";
// const sql = require('pg')

const { Client } = require('pg');

const sql = new Client({
    // type: "postgress",
    host: 'myhost.com',
    port: 0000,
    user: 'user-to-authenticate',
    password: 'my-password',
    database: 'mydatabase',
});


export class InteractWithDatabase implements Ability {

  static using() {
    return new InteractWithDatabase();
  }

  static as(actor: UsesAbilities): InteractWithDatabase {
    return actor.abilityTo(InteractWithDatabase);
  }

  constructor() {
  }

  execute(query: string): PromiseLike<any> {
    return sql.connect().then(() => {
      return sql.query(query)
    }).then((result: any) => {
      return result
    }).catch((err: any) => {
      console.log(err)
    })
  }
}

`


Thank you very much!

**Comment by rodrigo-costa-sofist** [comment]
Hi @jan-molak , just one more question... what would be the correct way to end the connection pooling?

Due to, as it is an Ability, when I have to execute more than one sql query, I get this error "Cannot use a pool after calling end on the pool" when I try to end the connection pooling this way:

`typescript
  execute(query: string): PromiseLike<any> {
    return sql.connect().then(() => {
      return sql.query(query)
    }).then((result: any) => {
      return result
    }).catch((err: any) => {
      console.log(err)
    })
  }
`

**Comment by jan-molak** [comment]
Hey @ghost! Serenity/JS v 2.19 introduced support for automatically initialisable/discardable abilities.

```typescript
import { Ability, actorCalled, configure, Discardable, Initialisable, Question, UsesAbilities } from '@serenity-js/core';
import { ConsoleReporter } from '@serenity-js/console-reporter';
import { Ensure, equals } from '@serenity-js/assertions';

const { Client } = require('pg');                                               // Node.js client for PostgreSQL

configure({
    crew: [
        ConsoleReporter.forDarkTerminals(),
    ],
});

class QueryPostgresDB implements Initialisable, Discardable, Ability {      // New interfaces: Initialisable and Discardable
    static as = (actor: UsesAbilities) => actor.abilityTo(QueryPostgresDB); // retrieve actor's ability to QueryPostgresDB

    constructor(private readonly client) { }

    initialise      = () => this.client.connect();                          // connect to DB when actor starts
    isInitialised   = () => this.client._connected;                         // ensure we only connect once

    discard = () => this.client.end();                                      // disconnect when the actor is dismissed

    query = (query: string) => this.client.query(query);                    // custom integration APIs, i.e. "query"
}

const CurrentDBUser = () =>                                                 // Custom Question using QueryPostgresDB
    Question.about('current db user', actor =>
        QueryPostgresDB.as(actor).query('SELECT current_user')
            .then(result => result.rows[0].current_user)
    );

describe('Serenity/JS 2.19.0', () => {
    it('can initialise and discard abilities automatically', () =>
        actorCalled('Debbie')
            .whoCan(new QueryPostgresDB(new Client()))
            .attemptsTo(
                Ensure.that(CurrentDBUser(), equals('jan'))
            ));
});

```

Hope this helps!
