### ISSUE TITLE
Unable to customize serenity-bdd test report

### ISSUE THREAD

**Issue by puddles-1** [serenity-js/serenity-js#625]
I'm looking to add a project title to my tests report and I noticed that the environment arguments that are supported by the serenity cli are not supported by serenity-bdd.  For example I would like to set the argument of `-Dserenity.project.name` to something of my choosing, however serenity-bdd doesn't support this (or the `--project` argument doesn't seem to do what it should).  A solution might be to in  `serenity-bdd/src/cli/commands/run.ts` to pass on the environment arguments passed to serenity-bdd e.g something like 
```
InvokeSerenityBDD.at(pathToArtifact)
         .withProperties(SystemProperties.from(...process.env(), ...{
                    'serenity.compress.filenames': `${ argv.shortFilenames }`,
                    'LOG_LEVEL': argv.log,
                    'logback.configurationFile': path.resolve(moduleRoot, './resources/logback.config.xml'),
                }))
```
I'm happy to open a pull request if you would like me too.

**Comment by jan-molak** [comment]
Hi @puddles-1! A pull request would be great, thanks!

**Comment by jan-molak** [comment]
Hi @puddles-1! You should be able to specify any configuration properties in [`serenity.properties`](https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html) file placed in your project root.

Hope this helps!

**Comment by puddles-1** [comment]
@jan-molak thanks very helpful!
