### ISSUE TITLE
Unexpected end of json input and type errors

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#626]
Hi @jan-molak , greetings!

Again with some trouble, i am here to seek help. I am unable to figure out, when i give run to protractor in parallel (8 instances), i see 'unexpected end of json input' for the very first features running in the test-suite.

Also, i see it throws, type error: 
![IMG_20200728_162038](https://user-images.githubusercontent.com/40024241/88656727-6562f780-d0ee-11ea-9aa7-724f106119fc.jpg)
cannot find property {static.method_name} of undefined.

Would request you to help me here.Thanks.

Best Regards,
Abhineet Sharma

**Comment by AbhineetSharmax** [comment]
![IMG_20200728_162038](https://user-images.githubusercontent.com/40024241/88656842-8fb4b500-d0ee-11ea-8096-d8767b37a7a7.jpg)

**Comment by jan-molak** [comment]
Hi there! Would you be able to create a minimal reproducible example demonstrating the issue?
