### ISSUE TITLE
cucumberOpts.require path causing  ☕ImplementationPendingError: Step not implemented

### ISSUE THREAD

**Issue by zuyetawarmatik** [serenity-js/serenity-js#632]
I was using sucsessfully protractor-cucumber-framework for my Angular E2E before, so in protractor.conf.js, I used to specify the require path like this, which is relative to protractor.conf.js:

```
cucumberOpts: {
  require: ['./specs/**/*.spec.ts'],
  strict: true
}
```

but when coming to @serenity-js/protractor/adapter as framework, I encountered `☕ImplementationPendingError: Step not implemented`, after much headache, I need to fix the path to be relative to the project root

```
cucumberOpts: {
  require: ['e2e/src/specs/**/*.spec.ts'],
  strict: true
}
```

To me, @serenity-js/protractor/adapter is not handling the cucumberOpts path correctly, as specs path is still able to use protractor.conf.js-relative path like this `specs: ['src/features/**/*.feature']`, but not `specs: ['e2e/src/features/**/*.feature']`. This issue may need to be addressed by a fix, or some example Angular project needs to note on this.

**Comment by jan-molak** [comment]
Hi @zuyetawarmatik and welcome to the Serenity/JS community 👋 

Based on what I gathered from the ticket, I'm guessing that the folder structure you use looks more or less like this:

```
e2e
  src
    specs
    features
```

What I'd like to understand is where in this structure are:
- step definition files
- protractor.conf.js
- feature files

I'd also like to understand whether your `protractor` and `cucumber` modules are installed globally or within the project, and what versions of those dependencies you're using, and how you're running your tests (what's the `cwd`)

What would be of great help if you could create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) repo on Github that demonstrates the issue you're seeing. You could use the [Serenity/JS Cucumber Protractor template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) as a starting point.

Thanks!
Jan

**Comment by zuyetawarmatik** [comment]
Hi @jan-molak,

Here is the minimal not-working example of an Angular structure with Serenity E2E test https://github.com/zuyetawarmatik/temp-angular-serenity, note that it's doesn't touch the Angular part (just for minimality). To run, use `npm run e2e`.

To make it running, as I mentioned, in protractor.conf.js, you either change cucumberOpts.require to `e2e/src/specs/**/*.spec.ts` instead of `src/...`, or use `protractor-cucumber-framework` as frameworkPath.
