### ISSUE TITLE
What is the Proper way to interact with select field?

### ISSUE THREAD

**Issue by rodrigo-costa-sofist** [serenity-js/serenity-js#633]
Hi!

I have a select field that I have to interact with in my test.
The way that I'm trying to do it is by clicking on the select field, then click on the select option... however, this is not working correctly.

So, I would like to know what is the proper way to interact with it in Serenity JS?

This is the element that I have to do it.

![image](https://user-images.githubusercontent.com/45850178/90322455-a5b5d880-df2a-11ea-816f-0db5c0705f8c.png)

**Comment by jan-molak** [comment]
Hi @rodrigo-costa-sofist! @nbarrett is working on adding support for select fields in #373, which should land in `@serenity-js/protractor` soon.
