### ISSUE TITLE
[bug] - When scenario outline is on a feature which has more scenarios and uses background, it is not presented properly at the serenity report

### ISSUE THREAD

**Issue by ralves20** [serenity-js/serenity-js#635]
Hi

I'm using Serenity js 2.14 and I realized that when I have a feature file which has many scenarios and this feature uses background, the scenario is not generated correctly at the serenity report.
e.g.
scenario written in a feature with other scenarios and background:
![image](https://user-images.githubusercontent.com/40844089/90557654-38e04f80-e171-11ea-863d-79997a6d9e4a.png)

how this scenario is presented at the serenity report
![image](https://user-images.githubusercontent.com/40844089/90557735-5b726880-e171-11ea-8621-4a47ca599924.png)

![image](https://user-images.githubusercontent.com/40844089/90558123-efdccb00-e171-11ea-8dae-445873884916.png)

**however when my scenario is isolated at a feature file and does not uses scenario background, the scenario is presented correctly at the report**

e.g
scenario written in a isolated feature without background usage:
![image](https://user-images.githubusercontent.com/40844089/90557901-9bd1e680-e171-11ea-8015-6d031c3b2c2a.png)

then the scenario at the report is generated correctly:
![image](https://user-images.githubusercontent.com/40844089/90557985-b5732e00-e171-11ea-9914-a6666c6087c2.png)

![image](https://user-images.githubusercontent.com/40844089/90558048-cd4ab200-e171-11ea-88bb-d9de929f60f8.png)

**Comment by jan-molak** [comment]
Hi @ralves20! Would you be able to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) based on the [Serenity/JS Cucumber Protractor template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) and publish it to Github so that I can try to reproduce the issue you're seeing?

Thanks!
Jan

**Comment by jan-molak** [comment]
Hi @ralves20! I wasn't able to reproduce the issue you were seeing, and since I haven't heard back from you I'm assuming this ticket can be closed.

Please note that Serenity/JS v 2.20 has just been released and it adds support for Cucumber 7, which I thought you might be interested in.
