### ISSUE TITLE
docs: screenplay_pattern_model.png -- UML Diagram shows aggregation at wrong endpoint

### ISSUE THREAD

**Issue by jenisys** [serenity-js/serenity-js#639]
The UML diagram of the "Screenplay Pattern" (docs/images/screenplay_pattern_model.png) is used on many pages in the documentation (handbook, website).

PROBLEM:
The UML diagram of the "Screenplay Pattern" shows "caret" for the aggregation on the wrong side / endpoint of the relation.
The current diagram states via UML conventions:

* Ability contains / aggregates many Actor(s)
* Interaction(s) contains many Task(s) (or: is made up of them)

AFFECTED RELATIONS:
* Actor -- Abilities
* Tasks -- Interactions

CURRENT STATE:
Actor has many Abilities:  `Actor --<> Abilities`
Tasks are made up of many Interactions: `Tasks --<> Interactions`

SHOULD BE:
Actor has many Abilities:  `Actor <>-- Abilities`
Tasks are made up of many Interactions: `Tasks <>-- Interactions`

SEE ALSO:
* [docs/images/screenplay_pattern_model.png](https://github.com/serenity-js/serenity-js/blob/master/docs/images/screenplay_pattern_model.png)

**Comment by jan-molak** [comment]
Hi @jenisys and welcome to the Serenity/JS community!

Excellent catch, thanks! I'll push a fix shortly.

Best,
Jan
