### ISSUE TITLE
Screenshots are not getting properly appended in the html reports

### ISSUE THREAD

**Issue by MJavedAli** [serenity-js/serenity-js#657]
When generating aggregate reports after running the same scenario twice  -> the failed screenshot of the latest run gets appended to all previous scenario in html report.

**Comment by jan-molak** [comment]
Hi @MJavedAli! HTML reports are produced by Serenity BDD, which relies on `.json` files and `.png` screenshots that Serenity/JS generates in the output directory, such as `target/site/serenity`. If you don't clear that directory between the runs, Serenity BDD assumes that all its contents should be reported on.

Does this help?
Jan

**Comment by jan-molak** [comment]
@MJavedAli - I haven't heard from you in a while so will assume that you're no longer experiencing this issue. Please feel free to open another ticket if this is not the case.
