### ISSUE TITLE
Custom task message

### ISSUE THREAD

**Issue by eyesopen** [serenity-js/serenity-js#660]
Hello,

I would like to request a way to define custom text of the Task. There was a similar request [here](https://github.com/serenity-js/serenity-js/issues/586), but it was only applied to Notes. Following same logic i would imagine following:

```
Enter.theValue(password).into(passwordInput).as(`#actor enters ******* into ${passwordInput}`)
```

Or
```
Check.whether(condition, met).andIfSo(actions).as(`#actor checks if ${condition} is ${met}`) 
```

**Comment by jan-molak** [comment]
Hi @eyesopen!

To give an interaction more meaningful, domain-specific name you can wrap it in a task:
```typescript
import { Task } from '@serenity-js/core';

const AuthenticateWithPassword = (password: string) => 
    Task.where(`#actor authenticates with password`, 
        Enter.theValue(password).into(passwordInput)
    ),
```

And if you're after masking the password so that it doesn't appear in the logs and reports you could go with a custom question along those lines:

```typescript
import { Question } from '@serenity-js/core';

const Password = (password: string) =>
    Question.about('their password', actor => password)
```

and then:

```typescript
actorCalled('Patrick').attemptsTo(
    Enter.theValue(Password('P@ssw0rd')).into(passwordInput),
);
```

Does this help?

Jan

**Comment by eyesopen** [comment]
This is nice!
I originally solved it by writing custom Enter task (reimplementing it with desired message), but this seems like a better way.
The reason for this request where i run into unnecessary or too technical messages while implementing repeat task
```
performAs(actor) {
    this.repeatCount++;
    return actor.attemptsTo(
      ...this.tasks,
      Check
        .whether(this.target, not(this.expectation))
        .andIfSo(
          EnsureRepeatNeeded.at(this.repeatCount).outOf(this.maxRetries).errorMessage(this.error),
          Wait.for(this.repeatDelay),
          this,
        ),
    );
  }
```
Where EnsureRepeatNeeded does
```
Ensure.that(this.currentRetry, isLessThan(this.maxRetries)).otherwiseFailWith(AssertionError, this.error),
```
It is called like this:
```
   Repeat.actions(
      Click.on(searchButton),
      WaitForResultsLoaded.until(pageLoader, not(isPresent())),
    ).until(Text.of(status), not(includes('Waiting')))
     .orFailWithError('Not resolved within expected time window')
     .after(maxRepeatCount),
  )
```
Which results in 
```
[protractor]                 User performs Repeat
[protractor]                   ✓ User clicks on the search button (61ms)
[protractor]                   User performs WaitForResultsLoaded
[protractor]                     ✓ User waits up to 20s until the Page loader does not become present (1s 554ms)
***[protractor]                   User ensures that the text of the status does include 'Waiting'
[protractor]                     Validate the operation timeout
***[protractor]                       ✓ User ensures that 4 does have value that's less than 10 (0ms)
[protractor]                     ✓ User waits for 5s (5s 1ms)
[protractor]                     User performs Repeat...
```
this gives multiple "faulty" texts like:
- **ensure** message instead of **check** for status check. Even now reading the fragment makes me lift an eyebrow :D
- check for timeout at EnsureRepeatNeeded gives totally technical message which i could rephrase to 'Attempt 4 of 10'

Given the custom message i would have probably skipped couple of random tasks as well as the goal of them was to hide the undesired text, but it is still there, just deeper... The only way to rid of them would be to reiplement the existing tasks or maybe something can be achieved with custom Questions, but i dont understand them well...

And i dont speak TypeScript :)

**Comment by jan-molak** [comment]
Got it, thanks for providing the context! 

I like your idea with `Repeat`; Serenity/JS has a task to [`Loop.over(things)`](https://serenity-js.org/modules/core/class/src/screenplay/tasks/Loop.ts~Loop.html), but we could introduce some additional loops if folks need them.

> ensure message instead of check for status check

This was a bug, fixed in 2.19.9 #713

**Comment by tfarrar** [comment]
@eyesopen When using this `EnsureRepeatNeeded.at(this.repeatCount).outOf(this.maxRetries).errorMessage(this.error) `  How did fail after the last repeat?   

This is what I was doing 
`import { Actor, Interaction } from '@serenity-js/core';
import { Check,equals,Ensure } from '@serenity-js/assertions';


class EnsureRepeatNeeded extends Interaction {
  
    static maxRepeatCount: number;
    static count: number;
    static errorMsg: string;

    static at(count: number ) {
        this.count=count;
        return this;
    }
    static outOf(maxRepeatCount: number ) {
        this.maxRepeatCount=maxRepeatCount;
        return this;
    }
    static errrorMessage(errorMsg: string ) {
        this.errorMsg=errorMsg;
        return new EnsureRepeatNeeded();
    }

    constructor() {
        super();
    }



    performAs(actor: Actor): PromiseLike<void> {
        return actor.attemptsTo(
            Check
            .whether( EnsureRepeatNeeded.count >= EnsureRepeatNeeded.maxRepeatCount, equals<boolean>(true))
            .andIfSo(

                Ensure.that(false, equals(true))
    
            )
        );
    }

    toString(): string {
        return `#actor performs Repeat... `;
    }

}
export { EnsureRepeatNeeded };`

**Comment by eyesopen** [comment]
@tfarrar EnsureRepeatNeeded just asserts. If it were to reach the max allowed retry the Ensure fails and test execution is  stopped.

```javascript
const { isLessThan, Ensure } = require('@serenity-js/assertions');
const { Task, AssertionError } = require('@serenity-js/core');

class EnsureRepeatNeeded extends Task {
  static at(currentRetry) {
    return new EnsureRepeatNeeded(currentRetry);
  }

  outOf(maxRetries) {
    this.maxRetries = maxRetries;
    return this;
  }

  errorMessage(error) {
    this.error = error || this.error;
    return this;
  }

  constructor(currentRetry) {
    super();
    this.error = 'Timeout: action did not complete within expection period';
    this.maxRetries = 10;
    this.currentRetry = currentRetry;
  }

  performAs(actor) {
    return actor.attemptsTo(
      Ensure.that(this.currentRetry, isLessThan(this.maxRetries)).otherwiseFailWith(AssertionError, this.error),
    );
  }

  toString() {
    return 'Validate the operation timeout';
  }
}

module.exports = {
  EnsureRepeatNeeded,
};
```
The only reason for this task was to hide the value "User ensures that 4 does have value that's less than 10 (0ms)", the ensure can simply be moved out to repeat and all will still work.

```javascript
Check
        .whether(this.target, not(this.expectation))
        .andIfSo(
          Ensure.that(this.repeatCount, isLessThan(this.maxRetries)).otherwiseFailWith(AssertionError, this.error),
          Wait.for(this.repeatDelay),
          this,
        ),
```

**Comment by tfarrar** [comment]
Thank you @eyesopen  and @jan-molak.
I got it all to work to together with following custom repeat.

```
        Repeat.actions(
                GetRequestDetails.fromKIRKE(Number('103907'),new GetUrl(process.env.ENV).kirke_token)
           )
        .until(
            LastResponse.body<Array<requestDetail>>().map(actor => body => body.item[0].currentStatusId),
            containAtLeastOneItemThat(not(equals(3)))
            )
          .waitFor(Duration.ofSeconds(2))
          .orFailWithError('failed to get correct status')
          .after(2),
```
