### ISSUE TITLE
Negative test cases , Wait / Expect

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#663]
Hi @jan-molak,
 
Greetings,

Thank you for all the efforts for bringing 2.0. I am currently trying to migrate 1.0 version to 2.0, and have started working with the protractor-cucumber template . I have started to move my test scenarios to the latest serenity 2.0 and changing the imports and conditions where ever needed and its really easy thanks to you.

The question i had was in previous version, 'Is' was available to work with conditions like,

Wait.upTo(Wait.duration.ofSeconds(30)).until(BasePage.loading, Is.invisible()),

please help me change this line to test it for negative scenarios where i would like to wait until that element goes invisible from the screen. I saw isVisible() is available. Please help me here. Thanks.

Best Regards,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax!

All you need to do is compose [`not`](https://serenity-js.org/modules/assertions/function/index.html#static-function-not) and [`isVisible`](https://serenity-js.org/modules/protractor/function/index.html#static-function-isVisible):

```typescript
import { not } from '@serenity-js/assertions';
import { isVisible } from '@serenity-js/protractor';

Wait.upTo(Wait.duration.ofSeconds(30)).until(BasePage.loading, not(isVisible())),
```

Let me know if this helps!

Best,
Jan

**Comment by AbhineetSharmax** [comment]
Thank you @jan-molak i'll try it out Thanks again. 😊
