### ISSUE TITLE
Issues with serenity BDD reporting

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#679]
Hi @jan-molak , 

Greetings!

I have successfully migrated our code from serenity 1.0 to 2.0 with ease, thanks to you again. 💯
There are few issues that i am facing and couldn't sort them out.

We have around 120 features files in our project, using protractor-cucumber with serenity-js version 2.0.16.

Issues with serenity reports:
1. 
During our overnight runs, sometimes we are facing issues like follows,
![IMG_20201014_101945__01](https://user-images.githubusercontent.com/40024241/95945207-91e20200-0e07-11eb-9d02-a57354eb3801.jpg)

2.
Reports which are getting generated giving different numbers as per summary.txt generated while npm run test:report.

3.
Observed the test failure overview doesn't shows the error cause.
![IMG_20201014_102012](https://user-images.githubusercontent.com/40024241/95945368-eeddb800-0e07-11eb-9f36-6b93805cec34.jpg)

Please help me here with your guidance. Thank you.

Best Regards,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax - It's really hard to tell without being able to see the reports or your test suite... I've just published a new version of the `@serenity-js/serenity-bdd` module, though, so please update to 2.17.2 and let me know if the issue is still there?

**Comment by AbhineetSharmax** [comment]
Thanks alot @jan-molak , i will update to the latest version, might be using (2.0.16).
 : )

Best Regards,
Abhineet Sharma
