### ISSUE TITLE
Change log  detail page is not working on serenity-js official site

### ISSUE THREAD

**Issue by SJ1591** [serenity-js/serenity-js#686]
I was going through the documentation of serenity-js where I encounter issue here https://serenity-js.org/changelog.html and I landed on 404 page when I tried to open any random changelog detail page
Example : 
 https://serenity-js.org/CHANGELOG.html#2-13-1-2020-08-05-

![20201023_224012.jpg](https://user-images.githubusercontent.com/18211007/97033290-be70e900-1580-11eb-9ffd-340ea282f48a.jpg)

@jan-molak

**Comment by SJ1591** [comment]
@jan-molak I think the url for changelog changes to uppercase when I click on any log details like this one
https://serenity-js.org/CHANGELOG.html#2-13-1-2020-08-05-

but I changed it lowercase and it seems to be working 

https://serenity-js.org/changelog.html#2-13-1-2020-08-05-  seems to be working.

**Comment by jan-molak** [comment]
Hey @SJ1591 - thanks for reporting this issue. Let me sort it out :-)
