### ISSUE TITLE
Missing report in serenity-js-jasmine-protractor-template 

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#691]
Hi

When using the serenity-js-jasmine-protractor-template I am not getting the SerenityBDD report. More specific, the result json is missing after test execution.

Steps to reproduce:
- Clone serenity-js-jasmine-protractor-template
- npm ci
- npm test

The json in ./target/site/serenity is not generated. The report itself is created but has no results.

The full-stack-acceptance-testing-demo works for me in the same environment. Report is generated as expected.

node v14.15.0
npm v6.14.8
Java OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
Chrome v6.0.4240.111 
Windows 10 (Version 2004)

**Comment by jan-molak** [comment]
Well spotted, @viper3400, thanks for reporting the issue! 
It looks like dependabot messed up `package-lock.json` when updating `@serenity-js/*` dependencies in template projects.

All the templates should be fine now, so please let me know if you notice anything out of order.

Thanks!
Jan

**Comment by viper3400** [comment]
Hi @jan-molak 

Tried the serenity-js-jasmine-protractor-template. Json and report are now generated as expected.

Thanks for your quick support.
Jan

**Comment by jan-molak** [comment]
Thanks for re-testing. And welcome to the Serenity/JS community ☺️
