### ISSUE TITLE
Problem accessing "external helpers"

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#706]
Hi,

I would like to use serenity-js but I have to use some kind of external libraries of "helpers".

Following the instructions here https://serenity-js.org/handbook/design/interactions.html, I created an example based on the serenity-js-jamsmine-protracotr-template
1) the ./lib/ExternalLibrary.ts (the one I wan't to use)
2) the ./src/abilities/UseExternalLibrary.ts (as the ability to use the external lib)
3) the ./src/interactions/DoSomeMagic.ts (as the interaction to use the ability)
4) enhanced the ./spec/example.spec to instruct the actor to DoSomeMagic()
5) enabled the actors in ./src/actors.ts to use the ability UseExternalLibrary

When running the test, this test will raise a:

``` "ConfigurationError: Jasmine can't UseExternalLibrary yet. Did you give them the ability to do so?" ```

(I think this was done in step 5)

I also created a "native" example (folder spec-native) which runs without erros.

What am I doing wrong?

You can view and clone the code from here https://github.com/viper3400/serenity-js-playground/tree/UseExternalLibrary

**Comment by jan-molak** [comment]
I think I see what's going on.

In `Actors` we have:

```
export class Actors implements Cast {
    prepare(actor: Actor): Actor {
        return actor.whoCan(
            BrowseTheWeb.using(protractor.browser),
            UseExternalLibrary        // <- this should be an instance of the ability, so:
            UseExternalLibrary.of(externalLibrary)
        );
    }
}
```

The ability itself looks good; Remember you'll also need to return from [`doSomeMagic`](https://github.com/viper3400/serenity-js-playground/blob/UseExternalLibrary/src/abilities/UseExternalLibrary.ts#L17) to avoid ignoring the `Promise` an `async` function returns in your `ExternalLibrary`.

You're on the right track, though!

Is the custom integration you're working on something you'd like to share with the wider community?

**Comment by viper3400** [comment]
Hi Jan, 

thanks for that, that did the trick. I didn't got this. 

Actually, it's not very sophisticated what I'm trying and there is nothing worth to share. I tried to wrap up some existing page objects and navigation helpers (and their helpers ...) stuff from our outer business framework protractor tests (like navigation and login stuff) in order to reuse it in a new module to give the screenplay approach a chance.

I first thought I could wrap around it the way serenity-js/protractor - BrowseTheWeb.manage() ability does but finally ended up to wrap the functions I really need within interactions and using my own targets and task.

Nevertheless, thanks for you support, it helped me either way.

Regards, Jan
