### ISSUE TITLE
Assertions / Check: Misleading Message in Report ?!

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#713]
https://github.com/serenity-js/serenity-js/blob/249afdbead1f9ca9319dc6f44b3d7a30a162cecb/packages/assertions/src/Check.ts#L103

The check assertion returns the same message as ensure, therefore the report is a bit misleading.  Is this intended?
Shouldn't it be something like: "#actor checks that ${ this.actual } does ${ this.expectation } ?

**Comment by jan-molak** [comment]
Nice catch! You're on a roll tonight! 👍🏻

**Comment by jan-molak** [comment]
Fixed in `2.19.9`
