### ISSUE TITLE
Images not displayed in report if source path gets to long

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#714]
Hi @jan-molak 

When it goes, it goes. Found another one, which is not a bug at all, but a kind of limitation, which I like to address to the community in case others having the same issue: 

While verifying fix for  #634  I wondered why there are still images not displayed in my report. Being as descriptive as they are, the PNG file names of the created screenshots could become very long.

Given a deep folder structure and the fact, that I'll open the index.html of report directly from Windows Explorer, the src attribute of the images point to a ```file://``` source, which will easily exceed the browsers URL limitations (maybe around the 256 characters limit, did not figure this out completely). 

One won't be able to open this image in the browser directly when passing the URL into the address bar, as well

![grafik](https://user-images.githubusercontent.com/11006334/102367203-c7e36400-3fb9-11eb-97ec-148e9254022c.png)

As workaround, I just copied my report into ```c:/tmp``` and the images could be displayed.

(Don't know if this issue only applies to Windows.)

Maybe file names could be shortened in future, but that won't solve the problem in some edge cases at all.

**Comment by jan-molak** [comment]
Hey @viper3400 thanks for reporting this issue; I'd like to dive into it a bit deeper.

I believe that a browser URL can have up to [2000 characters](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers), so I don't think we're hitting that limit.

What we might be hitting, however, are [limits of the Windows OS](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) where it seems like the total length of a file system path cannot exceed 260 characters. My original understanding was that the file _name_ needs to be shorter than ~250, but it looks like this limit applies to the entire path.

I think there are two options for the `ArtifactArchiver` here:
- it could be made configurable to enable or disable the human-friendly segment of the artifact name altogether
- alternatively, it could calculate the length of the path it would like to store an artifact at, and truncate the human-friendly segment as much as needed to meet the limit of being under 260 chars

The third option I guess would be for people using WIndows to [enable long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later), but that's a bit hairy.

Thoughts?

**Comment by viper3400** [comment]
Hi @jan-molak 

Actually, on the OS I found this issue (Windows Version 1903) the long paths are already enabled:

![grafik](https://user-images.githubusercontent.com/11006334/102632379-4e7d7a00-414f-11eb-9d1a-e965200816eb.png)

So I think, there must be another reason for this. As well, not every user may have access to the Windows registry (maybe in a restricted business environment, where in addition registry settings could be overwritten by group policies at every time.)

Given, that the reason for this is not quite clear, I think it will be difficult to calculate the limit. As well this option will fail, if the report will be copied to another location, where the limits will not be the same.

So I would suggest the option of disabling the human-friendly segment by configuration, which seems the simplest solution at all ( I don't know, if the report generation makes any other usage of the name to generate descriptions or so, but I suppose all data is taken from the JSONs.)

Thanks for your support.
Regards, Jan.

**Comment by viper3400** [comment]
Hi @jan-molak 

I've done some enhanced testing with this and this seems not to be as simple. I've [enabled long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation). But, as written at the bottom of the Microsoft article just some of the Windows APIs support long paths. So,  I haven't been able to create a folder/file structure in Windows Explorer longer [than 247 chars](https://social.technet.microsoft.com/Forums/windows/en-US/43945b2c-f123-46d7-9ba9-dd6abc967dd4/maximum-path-length-limitation-on-windows-is-255-or-247) at all. You can copy & paste files in deeper structures, though. But then you can't change long file names any more at this depth. Seems fuzzy.

I've seen, you've already a file name limit in place here: https://github.com/serenity-js/serenity-js/blob/3507e04d97f85d219c003669e6f2c6778e7fa366/packages/core/src/stage/crew/artifact-archiver/ArtifactArchiver.ts#L81

So still advocating for a further file name limitation.

**Comment by jan-molak** [comment]
Hey @viper3400  and thanks for such thorough research! I think `2.19.10` should address the issue you're seeing as the file name will now never exceed ~90 characters.

Thanks for your help and let me know if you spot any other issues!

Jan
