### ISSUE TITLE
IsTrue() is not working as expected

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#719]
Use case - I want to assert that whether output of Text.of(target) contains the word “Good”. 

We don’t have any direct method. So I have written separate logic and assign  to the variable 

When I use this variable with Ensure.that method and it is failing. Refer the screenshot 

Even, I tried like this Ensure.that(true, isTrue()) it is showing the below error
AssertionError: expected true to be false. Not sure why it is showing this error message 

Is serenity asset has any method for asserting two string with equalIgnoreCase 

![8FDE259A-8023-4B56-BF1E-663377BA5477](https://user-images.githubusercontent.com/28629290/103491170-1a5cb700-4de7-11eb-9666-867399c006a9.jpeg)

**Comment by jan-molak** [comment]
Wouldn't it be easier to use [`matches`](https://serenity-js.org/modules/assertions/function/index.html#static-function-matches)?

```
Ensure.that(Text.of(portal), matches(/Good/))
```

See [some more examples](https://serenity-js.org/modules/assertions/test-file/spec/expectations/matches.spec.ts.html)
