### ISSUE TITLE
API - serenity report - Not showing soap response in pretty view

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#722]
One of my api response in xml format. After successful run, in the report, response is showing in single line. 
How to display the report in pretty xml format.  
![F56C3BEC-1937-409F-89AE-08FE7A201458](https://user-images.githubusercontent.com/28629290/104828449-1725ea00-582f-11eb-8499-33afdf190605.jpeg)

**Comment by jan-molak** [comment]
Hey @Krithikmano, to make this work out of the box, `HTTPRequestResponse` would need to be smarter about the content type of the response and format it accordingly. I've marked this ticket as a good idea for an enhancement, thanks for reporting it!

**Comment by jan-molak** [comment]
OK, so this turned out to be much easier to improve than I though. A fix is coming soon.

**Comment by jan-molak** [comment]
Version **2.20.1** preserves the original formatting of the response, for example:
```
actorCalled('Apisitt').attemptsTo(
  Send.a(GetRequest.to('https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'))
)
```
Gives us:
<img width="1116" alt="Screenshot 2021-01-23 at 02 44 56" src="https://user-images.githubusercontent.com/1089173/105566797-0214f380-5d26-11eb-918d-24e560110f08.png">
