### ISSUE TITLE
Report - Gui screenshot address bar is missing

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#746]
In the report, Screenshot is taking each page. But it is missing to take the address bar. I could see all screenshots without address bar. 

Because my use case is need to navigate different page and validate url and other element in the page.

**Comment by viper3400** [comment]
Hi @Krithikmano 

I'm not sure that this is an issue of Serenity/JS. This seems a limitation of Protractor - or better - the webdriver specification at all:
- https://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.takeScreenshot
- https://www.w3.org/TR/webdriver2/#take-screenshot

**Comment by jan-molak** [comment]
To add to what @viper3400 has said, if you need to report the current URL explicitly (i.e. to prove that the URL has changed after navigation), you can:
- use the interaction to [`Log`](https://serenity-js.org/modules/core/class/src/screenplay/interactions/Log.ts~Log.html) the [`Website.url()`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/Website.ts~Website.html#static-method-url) - `actor.attemptsTo(Log.the(Website.url()))`
- perform an [assertion](https://serenity-js.org/modules/assertions/), which will result in the assertion subject being reported, i.e. `actor.attemptsTo(Ensure.that(Website.url(), endsWith('/some/path')))`

Please also note that the interaction to [`Navigate.to(url)`](https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Navigate.ts~Navigate.html#static-method-to) reports the URL your actor is visiting.

Hope this helps!
