### ISSUE TITLE
Browser open with `Not Secure | data;` and then closes

### ISSUE THREAD

**Issue by dileepkeeppalli** [serenity-js/serenity-js#77]
Facing an issue when doing `npm test` on the cloned repo which open the browser with `Not Secure | data;` and then closes window immediately.

**Comment by dileepkeeppalli** [comment]
![serinityissue](https://user-images.githubusercontent.com/13331639/29117106-9db8bdc0-7d1a-11e7-9f83-09fc7f1e8739.png)

**Comment by marktigno** [comment]
Add this to your protractor.conf.js file:

    capabilities: {
    browserName: 'chrome', 
    
    chromeOptions: {
            args: [
                'incognito',
                'disable-extensions',
                '--allow-running-insecure-content'
            ]
        }
    }

I hope this might be helpful to you.

**Comment by marktigno** [comment]
Actually the browser will display that at start of the test then eventually loads the page that you set on the `baseUrl` so I think that's normal. Except if it loads that for too long so there might be other problems on it.

**Comment by jan-molak** [comment]
Hi @dileepkeeppalli, it seems like @marktigno's suggestion should help to resolve the issue so I'll close this ticket. Please feel free to open a new one should you require further assistance.
