### ISSUE TITLE
How to implement Traditional for Loop in screenplay

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#782]
one of my requirement is as below. I can achieve this by using traditional for loop. How can this will be done with Serenity screenplay

**Example** : In the web page, flight information(flight number, name,fromCity, toCity, Time?..) are displayed in horizontal tiles. I need to validate all the flight information against API by based on flight number. 

**Notes**:  
1. In the page, number of flight tiles will be displayed based on the users search
2. Validating the all flight information with API based on **flight id**
3. FligthAPI - This is the api, which will provide the flight information in Arrays like { Flights: [{},{},{},...}

**Example**
```
FlightNumber= element.all(xpathOfFlightNumber)
FlightName = element.all(xpathOfFlightName)
fromCity = element.all(xpathOfFromCity)
toCity = element.all(xpathOfToCity)
time = element.all(xpathOfTime)

    for (var i = 0; i < await this.FlightNumber.count(); i++) {
      let flightNumber = await this.FlightNumber.getText(i)
      let flightName = await this.FlightName.get(i).getText()
      let fromCity = await this.fromCity.get(i).getText()
      let toCity = await this.toCity.get(i).getText()
      let time = await this.time.get(i).getText()
      expect(flightNumber).to.equal(await new FlightApi.getFlightId(flightNumber))
      expect(FlightName).to.equal(await new FlightApi.getFlightName(flightNumber))))
      expect(fromCity).to.equal(await new FlightApi.geFromCityName(flightNumber)))
      expect(toCity).to.equal(await new FlightApi.getToCityName(flightNumber)))
      expect(time).to.equal(await new FlightApi.getTime(flightNumber)))
}
```

**Comment by jan-molak** [comment]
Hey @Krithikmano, check out [`Loop`](https://serenity-js.org/modules/core/class/src/screenplay/tasks/Loop.ts~Loop.html)

**Comment by Krithikmano** [comment]
@jan-molak i already referred  the Loop. But if you look my code,  flightnumber value should be referenced to other loops like flightname, fromCity. 

In serenity Loop function how to reference the flightnumber loop to other loops. I could not find any example for referencing one value to other loop.

**Comment by jan-molak** [comment]
Hey @Krithikmano - I'll close this ticket so we can track it under a more general one - #823
