### ISSUE TITLE
Report - web screenshot is not taking after api call

### ISSUE THREAD

**Issue by varshanharshank** [serenity-js/serenity-js#790]
I successfully implemented screenplay framework and I could run script and generate report for API and  UI.

Webpage screenshot is not showing in the report if script has api and UI. It means that my script first hit api then it will run the web page related scripts. In this case, api related information is embedded in the report but webpage screenshot is not showing. 

Note:
I just comment the api script and ran only ui script that time screenshot is showing in the report. 

Please suggest how to resolve it.

**Comment by jan-molak** [comment]
Hi @varshanharshank! It's difficult to tell without seeing your code. If you believe it's a bug in Serenity/JS, would you be able to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a repo on GitHub?

**Comment by viper3400** [comment]
Hi @varshanharshank , it's been a while here. Are you still facing problems when using Serenity/JS? In this case, I suggest to provide more context about your issues, so that we've got a chance to help. Or can we close this issue?

**Comment by viper3400** [comment]
Okay, so let's close this one. Whenever you face this problem again, I'd suggest to raise a new issue here, providing a bit more context and we see, how we can help out.
