### ISSUE TITLE
Documentation Issue: Deadlink to GitHub Documentation in Handbook

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#803]
Hi Jan,

https://github.com/serenity-js/serenity-js/blob/e316536177f4c83c85d7fae17a351a9a3e22754a/documentation/website/src/handbook/integration/versioning.md

```You can watch the Serenity/JS GitHub repository to be notified of experimental APIs.```

The link under "watch" is dead.  Where should it point to?

Maybe to  https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github

This is 2 times on the page, once in section 'Deprecated APIs', once in 'Experimental APIs'.

**Comment by jan-molak** [comment]
Well spotted, thanks! Looks like GitHub has moved that page.
