### ISSUE TITLE
How to check if file is downloaded?

### ISSUE THREAD

**Issue by tsche123** [serenity-js/serenity-js#813]
In Serenity JS (with Cucumber) we have a test scenario, where when the user clicks the button, then a .json file is downloaded.
Is there any way in serenity js to check if the file was really downloaded? (it's not downloaded through api call).

**Comment by jan-molak** [comment]
Hi @tsche123 - you'll need a custom question for that, and the way you'd write it depends on what is you want to test.

Are you interested in what the downloaded file contains, what it's called, or just that it exists?

The most basic implementation would look something like this:

```typescript
import * as fs from 'fs';
import { actorCalled, Question } from '@serenity-js/core';
import { Ensure, isGreaterThan } from '@serenity-js/assertions';

const DownloadedFileSize = (pathToFile: string) =>
  Question.about<number>(`size of ${ pathToFile}`, actor => {
     const stats = fs.statSync(pathToFile);
     const fileSizeInBytes = stats.size;
     return fileSizeInBytes;
  }):

actorCalled('Alice').attemptsTo(
  Ensure.that(DownloadedFileSize('/path/to/file.txt'), isGreaterThan(0)),
);
 ```

**Comment by tsche123** [comment]
Hi @jan-molak, thank you so much, that's what I needed :)

**Comment by jan-molak** [comment]
Excellent, thanks for confirming :-) And welcome to the Serenity/JS community!
