### ISSUE TITLE
Jasmine tags

### ISSUE THREAD

**Issue by DicksengA** [serenity-js/serenity-js#824]
Is there a way to use tags in jasmine and have them appear in serenity reports

**Comment by viper3400** [comment]
Hi @DicksengA 

I've discussed this once with @jan-molak :  https://gitter.im/serenity-js/Lobby?at=605b01c33a9448256c27c653

The only working solution I've found was the following tag function:

```ts
// tags.ts
import { serenity } from '@serenity-js/core';
import { SceneTagged } from '@serenity-js/core/lib/events';
import { Tags } from '@serenity-js/core/lib/model';

export function tags(tags: string[]) {
    const tagArray = tags.map((t) => Tags.from(t)).reduce((acc, current) => acc.concat(current), []);
    tagArray.forEach((tag) => {
        serenity.announce(new SceneTagged(serenity.currentSceneId(), tag, serenity.currentTime()));
    });
}

```
Then you can use this in the beforeEach of the jasmine.spec.ts files (to have each test step tagged with the tag):

```ts
import { tags } from './tags';

//...

   beforeEach(() => {
        tags(['@issue:JIRA-911']);
    });

//...
```

**Comment by DicksengA** [comment]
tested its working. Thanks
