### ISSUE TITLE
Question: can we integrate serenitjs with jest test runner in Angular web app

### ISSUE THREAD

**Issue by Manish123chandel** [serenity-js/serenity-js#830]
Hi @jan-molak @wakaleo  ,

Do we have this flexibility to test our Angular webapp with the use of jest for runner , jasmine with serenityjs.

i tried multiple combination,
if i try to do unittest fro angular webapp, with jasmin has its default test runner kama,
 but we dont go with karma as karma has lot of cons.
i decided to go with jasmin with jest runner and I able to manage the run the test.

Now for reporting purpose, i want to integrate with serenityJS.

Can you pls refer any doc for integration with serenityjs with jest runner.

Please help.

**Comment by jan-molak** [comment]
Hi @Manish123chandel - you can definitely use Serenity/JS with [plain Jasmine](https://github.com/serenity-js/serenity-js/tree/master/examples/jasmine-rest-api-level-testing). I'm not sure if Jest supports Jasmine reporters though and didn't have a chance to try that yet.
