### ISSUE TITLE
Issue when running tests on Angular Web App using serenityJS + Jasmine

### ISSUE THREAD

**Issue by zhenwei94** [serenity-js/serenity-js#831]
Hi @jan-molak and @wakaleo, we are trying to run component testing on Angular web app using serenityJS + Jasmine but encountered the error below. Any idea how we can resolve this issue?

![image](https://user-images.githubusercontent.com/43293569/117243713-558cf680-ae6a-11eb-8adc-4f8c0a25b858.png)

**Comment by jan-molak** [comment]
Hi @zhenwei94! It's hard to tell without seeing the code. Would you be able to create a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_working_example) so I can try to reproduce the issue?

Also, you do have `zone-testing` in your `src/test.ts`, right?

```typescript
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
```

**Comment by viper3400** [comment]
Hi @zhenwei94 

Are your sure you can simply kick out Karma as test runner to do unit / component test in Angular as try in your `app.component.spec.ts` (https://blog.bitsrc.io/understanding-test-configurations-in-angular-2f8b3d1fbd00) ?

Not sure, if Serenity/JS is still capable of this, at all: https://serenity-js.org/handbook/integration/architecture.html

**Comment by viper3400** [comment]
Hi @zhenwei94 , it's been a while, have you found a solution for this? I had a look into your repository again. I still think that this is not necessarily a problem of Serenity/JS at all but with the Jasmine setup in the project.

**Comment by viper3400** [comment]
Let's close this issue. You can request to reopen this issue at any time, if it's still a problem on your side. Maybe you have new information and we could try to dive a bit deeper.
