### ISSUE TITLE
Unable to get clean build from master

### ISSUE THREAD

**Issue by nbarrett** [serenity-js/serenity-js#89]
Hi @jan-molak - I have an open PR #73 which I'm struggling to make progress on, but realise that much of my problem is not being able to get a clean build and/or understand the test failures (even on master). In an attempt to initialise my environment cleanly I tried this:
```
npm run lerna clean
rm -rf node_modules
npm install
npm run verify
```

However, even with the above,  I can never get a build to pass on my machine and get these kinds of errors:

```
lerna ERR! execute 
lerna ERR! execute   45 passing (2m)
lerna ERR! execute   5 failing
lerna ERR! execute 
lerna ERR! execute   1) When waiting for things to happen, a test scenario using Active Wait (setTimeout) to determine if an element is not present in the DOM will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   2) When waiting for things to happen, a test scenario using Passive Wait ($timeout) will fail if the timeout is too short:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   3) When waiting for things to happen, a test scenario using Active Wait ($timeout) to determine if an element is not present in the DOM will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   4) When waiting for things to happen, a test scenario using Passive Wait ($interval) will pass if the timeout is long enough:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   5) When waiting for things to happen, a test scenario "before each" hook: ret for "can rely on a default timeout provided by Wait.until(..) to be sensibly long enough":
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
```

I did also have some problems with the version of node until I downgraded from 7.10.0
 to v6.9.5, but the documentation and engines section of package.json states  `"node": ">= 6.9.x"` which could be misleading to a new starter that might have a newer version of node installed. When node was 7.10.0 `npm run verify`, seemed to fail catastrophically 😭 

If you can provide some assistance with the following this would be really helpful please to those people that wish to submit PRs:
- How a clean build environment for the serenity-js project can be initialised, ready for the creation of PRs.
- How to generate/find a report that shows the failing serenity-js tests. The output sent to the command line is overwhelmingly verbose, so pinpointing the error is very hard. Given that the tests being run are serenity specs, is there an html report I can produce so that I can look at the failures? When I run `npm run report` I get the following which is a coverage report I think, which is not what I want:
```
> serenity-js@0.0.1 report /Users/nick/dev/git-personal/serenity-js
> npm run coverage:merge && npm run coverage:report


> serenity-js@0.0.1 coverage:merge /Users/nick/dev/git-personal/serenity-js
> istanbul-merge --out=./target/coverage/coverage-final.json ./target/coverage/**/coverage-final.json


> serenity-js@0.0.1 coverage:report /Users/nick/dev/git-personal/serenity-js
> nyc report --reporter=html --reporter=lcov --temp-directory=./target/coverage --report-dir=./target/coverage
```
- If the above could be put on the serenity-js documentation, this would be very helpful as don't think this exists yet. If it does, then I can't find it!

Thanks a lot Jan in advance. I'm happy to do the documentation btw, I just don't know what to put in it yet 😢

**Comment by jan-molak** [comment]
Hey @nbarrett, is this ticket still relevant given that you've managed to successfully submit #73 ?

**Comment by nbarrett** [comment]
Hi Jan, yes I think it is - putting aside the situation that I can rarely get a clean run of all tests,  I think there are still some gaps in the serenity-js documentation that explain how to build and run the tests and to also generate the serenity reports for the specs in the base product. See above note about that ⬆️

**Comment by jan-molak** [comment]
Hey @nbarrett - I've [added a section](https://serenity-js.org/contributing.html#proposing-enhancements) to the new Serenity/JS handbook that _starts to_ explain how to run the build locally. You know your help is always greatly appreciated, so please free to expand my initial note!
