### ISSUE TITLE
Can we configure the size of screenshot? 

### ISSUE THREAD

**Issue by lucieneven** [serenity-js/serenity-js#910]
Hello folks,

I have a generic question about taking screenshot. Usually it works fine, but since we need test a single page application, from what I see, sometimes the screenshot can't take the whole picture. 

See the picture where we wanted to take the screenshot, 

http://pimuer.com/test/b.jpg

And what we got actually is like 

http://pimuer.com/test/a.jpg

It does make sense, but if we can configure somewhat the size of screenshot, it'll be cool. 

Our customer likes the screenshot very much. But then they raised this question and I don't know how to improve. 

Please shed some light here, thanks!

Lucien

**Comment by viper3400** [comment]
H @lucieneven,

at the moment, Serenity/JS just wraps the Protractor "takeScreenshot" function (https://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.takeScreenshot) and therefor uses the strategy described there. 

I think, you can just adjust the  `--window-size` chrome option in the `protracor.conf.ts` in your projects base path - well - to adjust the browser window (and screenshot) size at all.

I'm also not sure about the structure of your page under test just by looking at the screenshots you've provided. Maybe you have to use `Scroll` (https://serenity-js.org/modules/protractor/class/src/screenplay/interactions/Scroll.ts~Scroll.html) to get to a special part of your page and to get a screenshot of that part?

**Comment by lucieneven** [comment]
Hello @viper3400 

I appreciate your answer very much. I believe it works fine when adjusting chrome option in the protractor.conf.ts. 

Also, scroll to one part of page and get a screenshot there, it's even better, since it's not necessary to change the global configuration for the window size. 

I'll give a try soon. But most likely it is not concern any more. Thanks again for the wonderful support here!
