### ISSUE TITLE
Serenityjs API documentation

### ISSUE THREAD

**Issue by vijay-kumar-singh** [serenity-js/serenity-js#96]
Dear Jan,

In order to develop robust Serenityjs based automation application, i want to understand more about its APIs details for various classes like Actor, Stage... so that i can use those api while developing application and hence able to utilize full strength of serenityjs.

I have gone through Serenityjs package source code and can see very useful methods of various classes which can be utilized in better way and help to write better code.
I am wondering if Serenityjs API details available  like API details [https://angular.io/api](https://angular.io/api) is available for Angular.

Regards,
Vijay Singh

**Comment by jan-molak** [comment]
Thanks for this feedback, you're absolutely correct. I've been looking for a good api docs generator for quite some time now. Regretfully, [ESDoc](https://esdoc.org/), which I really like, doesn't seem to support TypeScript... Suggestions welcome!

**Comment by nbarrett** [comment]
This may be a completely different area to what you are looking for, but how about something along the [swagger](https://swagger.io/) lines? I see a few typescript references e.g. [here](https://www.npmjs.com/package/swagger-ts) and [here](https://github.com/lukeautry/tsoa) , and also this [article](https://medium.com/willsonic/swagger-nodejs-typescript-tsoa-15a3f10fabaf)....

**Comment by jan-molak** [comment]
Thanks @nbarrett, Swagger is lovely, but to my knowledge only works with HTTP APIs. What I'm looking for is something that could parse the JSDoc and generate API documentation. I'm open to suggestions and ideas!

**Comment by vijay-kumar-singh** [comment]
What about this [https://github.com/TypeStrong/typedoc](https://github.com/TypeStrong/typedoc)
This is also Documentation generator for TypeScript projects.

**Comment by jan-molak** [comment]
Thanks @vijay-kumar-singh, I looked at it last year and it seemed to be in a bit of an early stage. I'm sure it must've progressed since then, though! 
If anybody would like to research that or other document generation tool and perhaps submit a PR I'd be more than happy to support you.

**Comment by WebTestNinja** [comment]
Hi Jan, I have verified with latest serenityjs but still i can see duplicate feature name in report.

**Comment by stckcrsh** [comment]
+1 please give us something like the angular api docs

**Comment by jan-molak** [comment]
@stckcrsh - that's my ambition too! Stay tuned :-)

**Comment by jan-molak** [comment]
@vijay-kumar-singh, @nbarrett , @WebTestNinja , @stckcrsh - Serenity/JS v2 has been released yesterday together with [a new website](https://serenity-js.org) and [API docs](https://serenity-js.org/modules).

While the docs are by no means as comprehensive as I'm planning them to be, they're an evolving project that's continuously improving 😄 

I'd love to hear your thoughts and feedback!
