### ISSUE TITLE
Structure is valid?

### ISSUE THREAD

**Issue by camillomurcia** [serenity-js/serenity-js#964]
Hello, I hope you are well.

I wanted to show you how you see the use of this archetype using the Screenplay pattern. I have made an example of automation with this archetype, I wanted to know your opinion about this, since I did not find a topic about this anywhere.

With jasmine

```
spec
├── screenplay
│    ├── ui
│    ├── tasks
│    ├── interactions
│    └── questions
│
└── archive.ts <- where the tests are housed for execution
```

With Cucumber

```
feature
├── step_definitions
│   └── archive.steps.ts <- Contains the step definitions
├── screenplay
│    ├── ui
│    ├── tasks
│    ├── interactions
│    └── questions
│
└── archive.feature <- Contains the scenarios in gherkin
```

**Comment by jan-molak** [comment]
Hi @camillomurcia! Perfect timing, I've just released a [new project template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) demonstrating Serenity/JS Screenplay Pattern implementation with WebdriverIO and Cucumber.

To answer your question about the archetype structure, I think it depends on a number of factors - are the tests in the same repo as the system under test, or are they an independent project? Is Cucumber the only test runner being used, or is Screenplay code shared with other test runners? Do you want to share test code across repositories? What slicing makes the most sense in the case of your system? By type (ui/tasks/interactions), by feature (product_seach/basket/checkout), by sub-system, etc.

I'd suggest this conversation I had with @AbhineetSharmax at #295 as a starting point.
In particular, note that with Serenity/JS you can organise `.feature` files into folders, which might affect where you want to place the integration code.

In the new project template I mentioned earlier, I've gone with a rather simple structure:
```
features                <- anything Cucumber-related
  step-definitions
    steps.ts
  authentication        <- feature files related to the "authentication" module of the test app
    form_authentication.feature
    narrative.md
  support               <- cucumber config, parameter types, etc.
test                    <- Serenity Screenplay code, sliced by module of "The Internet" test app
  authentication
    ui                  <- lean page objects, "package-private", never used in Cucumber scenarios
    Authenticate.ts     <- tasks related to the authentication module, used in Cucumber scenarios
    VerifyAuthentication.ts
```

Does it make sense?

**Comment by camillomurcia** [comment]
ohh ok, it makes sense.

The project is separate from the system repository.

The reason why I thought of this archetype in this way is because of the reason to separate and have the tasks, interactions, etc. in each folder

I leave you the example of how I did it with Jasmine but it is something "similar" for cucumber of how I am handling it (I have a project in cucumber with Protractor and one that I am doing with the new integration but I have not uploaded it yet) 

[Project Example With Jasmine](https://github.com/camillomurcia/serenity-js-jasmine-protractor-example)
